Doxygen: OutputCodeList Class Reference
OutputCodeList Class Reference
#include <outputlist.h>
Public Member Functions
OutputCodeList ()=default
virtual ~OutputCodeList ()=default
OutputType type () const override
void add (CodeOutputInterface *codeGen)
void setId (int id) override
void setEnabledFiltered (OutputType o, bool enabled)
void codify (const QCString &s) override
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip) override
void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor) override
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo) override
void startCodeLine (bool hasLineNumbers) override
void endCodeLine () override
void startFontClass (const QCString &c) override
void endFontClass () override
void writeCodeAnchor (const QCString &name) override
void startCodeFragment (const QCString &style) override
void endCodeFragment (const QCString &style) override
Public Member Functions inherited from CodeOutputInterface
CodeOutputInterface ()=default
CodeOutputInterface (const CodeOutputInterface &)=delete
CodeOutputInterface & operator= (const CodeOutputInterface &)=delete
virtual ~CodeOutputInterface ()=default
virtual OutputType type () const =0
virtual int id () const
Identifier for the output file.
virtual void setId (int id)
virtual void setEnabled (bool e)
virtual bool isEnabled () const
virtual void codify (const QCString &s)=0
virtual void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)=0
virtual void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)=0
virtual void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)=0
virtual void startCodeLine (bool hasLineNumbers)=0
virtual void endCodeLine ()=0
virtual void startFontClass (const QCString &clsName)=0
virtual void endFontClass ()=0
virtual void writeCodeAnchor (const QCString &name)=0
virtual void setCurrentDoc (const Definition *context, const QCString &anchor, bool isSourceFile)
virtual void addWord (const QCString &word, bool hiPriority)
virtual void startCodeFragment (const QCString &style)=0
virtual void endCodeFragment (const QCString &style)=0
Private Member Functions
template<typename T , class... Ts, class... As>
void forall (void(T::*methodPtr)(Ts...), As &&... args)
Private Attributes
std::vector< CodeOutputInterface * > m_outputCodeList
Detailed Description
Definition at line 34 of file outputlist.h.
Constructor & Destructor Documentation
OutputCodeList()
OutputCodeList::OutputCodeList () default
~OutputCodeList()
virtual OutputCodeList::~OutputCodeList () virtual default
Member Function Documentation
add()
void OutputCodeList::add (CodeOutputInterface * codeGen) inline
Definition at line 42 of file outputlist.h.
    {
      m_outputCodeList.push_back(codeGen);
    }
References m_outputCodeList.
Referenced by OutputList::add(), OutputList::operator=(), and OutputList::OutputList().
codify()
void OutputCodeList::codify (const QCString & s) inline override virtual
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 61 of file outputlist.h.
    { forall(&CodeOutputInterface::codify,s); }
References CodeOutputInterface::codify(), and forall().
endCodeFragment()
void OutputCodeList::endCodeFragment (const QCString & style) inline override virtual
Ends a block of code
Implements CodeOutputInterface.
Definition at line 86 of file outputlist.h.
    { forall(&CodeOutputInterface::endCodeFragment,style); }
References CodeOutputInterface::endCodeFragment(), and forall().
endCodeLine()
void OutputCodeList::endCodeLine () inline override virtual
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 76 of file outputlist.h.
    { forall(&CodeOutputInterface::endCodeLine); }
References CodeOutputInterface::endCodeLine(), and forall().
endFontClass()
void OutputCodeList::endFontClass () inline override virtual
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 80 of file outputlist.h.
    { forall(&CodeOutputInterface::endFontClass); }
References CodeOutputInterface::endFontClass(), and forall().
forall()
template<typename T , class... Ts, class... As> void OutputCodeList::forall (void(T::*)(Ts...) methodPtr, As &&... args) inline private
Definition at line 92 of file outputlist.h.
    {
      for (const auto &og : m_outputCodeList)
      {
        if (og->isEnabled()) (og->*methodPtr)(std::forward<As>(args)...);
      }
    }
References m_outputCodeList.
Referenced by codify(), endCodeFragment(), endCodeLine(), endFontClass(), setId(), startCodeFragment(), startCodeLine(), startFontClass(), writeCodeAnchor(), writeCodeLink(), writeLineNumber(), and writeTooltip().
setEnabledFiltered()
void OutputCodeList::setEnabledFiltered (OutputType o, bool enabled) inline
Definition at line 51 of file outputlist.h.
    {
      for (const auto &og : m_outputCodeList)
      {
        if (og->type()==o) og->setEnabled(enabled);
      }
    }
References m_outputCodeList.
Referenced by OutputList::syncEnabled().
setId()
void OutputCodeList::setId (int id) inline override virtual
Reimplemented from CodeOutputInterface.
Definition at line 46 of file outputlist.h.
    {
      CodeOutputInterface::setId(id);
      forall(&CodeOutputInterface::setId,id);
    }
References forall(), and CodeOutputInterface::setId().
Referenced by OutputList::operator=(), OutputList::OutputList(), and OutputList::startFile().
startCodeFragment()
void OutputCodeList::startCodeFragment (const QCString & style) inline override virtual
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 84 of file outputlist.h.
    { forall(&CodeOutputInterface::startCodeFragment,style); }
References forall(), and CodeOutputInterface::startCodeFragment().
Referenced by MemberDefImpl::_writeMultiLineInitializer(), ConceptDefImpl::writeDefinition(), DefinitionImpl::writeInlineCode(), VhdlDocGen::writeSource(), and FileDefImpl::writeSourceBody().
startCodeLine()
void OutputCodeList::startCodeLine (bool hasLineNumbers) inline override virtual
Implements CodeOutputInterface.
Definition at line 74 of file outputlist.h.
    { forall(&CodeOutputInterface::startCodeLine,hasLineNumbers); }
References forall(), and CodeOutputInterface::startCodeLine().
startFontClass()
void OutputCodeList::startFontClass (const QCString & clsName) inline override virtual
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 78 of file outputlist.h.
    { forall(&CodeOutputInterface::startFontClass,c); }
References forall(), and CodeOutputInterface::startFontClass().
Referenced by startFonts().
type()
OutputType OutputCodeList::type () const inline override virtual
Implements CodeOutputInterface.
Definition at line 40 of file outputlist.h.
{ return OutputType::List; }
Referenced by writeCodeLink().
writeCodeAnchor()
void OutputCodeList::writeCodeAnchor (const QCString & name) inline override virtual
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 82 of file outputlist.h.
    { forall(&CodeOutputInterface::writeCodeAnchor,name); }
References forall(), and CodeOutputInterface::writeCodeAnchor().
writeCodeLink()
void OutputCodeList::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) inline override virtual
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 63 of file outputlist.h.
    { forall(&CodeOutputInterface::writeCodeLink,type,ref,file,anchor,name,tooltip); }
References forall(), type(), and CodeOutputInterface::writeCodeLink().
writeLineNumber()
void OutputCodeList::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) inline override virtual
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 68 of file outputlist.h.
    { forall(&CodeOutputInterface::writeLineNumber,ref,file,anchor,lineNumber,writeLineAnchor); }
References forall(), and CodeOutputInterface::writeLineNumber().
writeTooltip()
void OutputCodeList::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) inline override virtual
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 71 of file outputlist.h.
    { forall(&CodeOutputInterface::writeTooltip,id,docInfo,decl,desc,defInfo,declInfo); }
References forall(), and CodeOutputInterface::writeTooltip().
Member Data Documentation
m_outputCodeList
std::vector< CodeOutputInterface* > OutputCodeList::m_outputCodeList private
Definition at line 99 of file outputlist.h.
Referenced by add(), forall(), and setEnabledFiltered().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/outputlist.h