Doxygen: /home/runner/work/doxygen/doxygen/src/markdown.cpp File Reference
markdown.cpp File Reference
#include <stdio.h>
#include <unordered_map>
#include <functional>
#include <atomic>
#include "markdown.h"
#include "growbuf.h"
#include "debug.h"
#include "util.h"
#include "doxygen.h"
#include "commentscan.h"
#include "entry.h"
#include "commentcnv.h"
#include "config.h"
#include "section.h"
#include "message.h"
#include "portable.h"
#include "regex.h"
#include "fileinfo.h"
#include "utf8.h"
Classes
class Trace
struct TableCell
struct MarkdownOutlineParser::Private
Macros
#define ENABLE_TRACING
#define IOSTREAM stdout
#define DATA_BUFSIZE 20
#define PRETTY_FUNC __PRETTY_FUNCTION__
#define TRACE(data) Trace trace_(PRETTY_FUNC,data);
#define TRACE_MORE(...) trace_.trace(__VA_ARGS__);
#define TRACE_RESULT(v) trace_.setResult(v);
#define isIdChar(i)
#define extraChar(i)
#define isOpenEmphChar(i)
#define ignoreCloseEmphChar(i)
#define isLiTag(i)
Enumerations
enum class ExplicitPageResult { explicitPage , explicitMainPage , notExplicit }
enum Alignment { AlignNone , AlignLeft , AlignCenter , AlignRight }
Functions
int isNewline (const char *data)
static QCString escapeDoubleQuotes (const QCString &s)
static QCString escapeSpecialChars (const QCString &s)
static void convertStringFragment (QCString &result, const char *data, int size)
static Alignment markersToAlignment (bool leftMarker, bool rightMarker)
helper function to convert presence of left and/or right alignment markers to a alignment value
static QCString getFilteredImageAttributes (const char *fmt, const QCString &attrs)
parse the image attributes and return attributes for given format
bool isBlockQuote (const char *data, int size, int indent)
returns TRUE if this line starts a block quote
static int isLinkRef (const char *data, int size, QCString &refid, QCString &link, QCString &title)
returns end of the link ref if this is indeed a link reference.
static bool isHRuler (const char *data, int size)
static QCString extractTitleId (QCString &title, int level)
static bool isEmptyLine (const char *data, int size)
static int computeIndentExcludingListMarkers (const char *data, int size)
static int isListMarker (const char *data, int size)
static bool isEndOfList (const char *data, int size)
static bool isFencedCodeBlock (const char *data, int size, int refIndent, QCString &lang, int &start, int &end, int &offset)
static bool isCodeBlock (const char *data, int offset, int size, int &indent)
int findTableColumns (const char *data, int size, int &start, int &end, int &columns)
Finds the location of the table's contains in the string data.
static bool isTableBlock (const char *data, int size)
Returns TRUE iff data points to the start of a table block.
static bool hasLineBreak (const char *data, int size)
static ExplicitPageResult isExplicitPage (const QCString &docs)
QCString markdownFileNameToId (const QCString &fileName)
processes string s and converts markdown into doxygen/html commands.
Variables
const char * g_utf8_nbsp = "\xc2\xa0"
const char * g_doxy_nbsp = "&_doxy_nbsp;"
const int codeBlockIndent = 4
Macro Definition Documentation
DATA_BUFSIZE
#define DATA_BUFSIZE 20
Definition at line 69 of file markdown.cpp.
ENABLE_TRACING
#define ENABLE_TRACING
Definition at line 64 of file markdown.cpp.
extraChar
#define extraChar (i)
Value:
  (data[i]=='-' || data[i]=='+' || data[i]=='!' || \
   data[i]=='?' || data[i]=='$' || data[i]=='@' || \
   data[i]=='&' || data[i]=='*' || data[i]=='%')
Definition at line 192 of file markdown.cpp.
ignoreCloseEmphChar
#define ignoreCloseEmphChar (i)
Value:
  (data[i]=='('  || data[i]=='{' || data[i]=='[' || (data[i]=='<' && data[i+1]!='/') || \
   data[i]=='\\' || \
   data[i]=='@')
Definition at line 205 of file markdown.cpp.
IOSTREAM
#define IOSTREAM stdout
Definition at line 68 of file markdown.cpp.
isIdChar
#define isIdChar (i)
Value:
  ((data[i]>='a' && data[i]<='z') || \
   (data[i]>='A' && data[i]<='Z') || \
   (data[i]>='0' && data[i]<='9') || \
   (static_cast<unsigned char>(data[i])>=0x80))
Definition at line 186 of file markdown.cpp.
isLiTag
#define isLiTag (i)
Value:
   (data[(i)]=='<' && \
   (data[(i)+1]=='l' || data[(i)+1]=='L') && \
   (data[(i)+2]=='i' || data[(i)+2]=='I') && \
   (data[(i)+3]=='>'))
Definition at line 2081 of file markdown.cpp.
isOpenEmphChar
#define isOpenEmphChar (i)
Value:
  (data[i]=='\n' || data[i]==' ' || data[i]=='\'' || data[i]=='<' || \
   data[i]=='>'  || data[i]=='{' || data[i]=='('  || data[i]=='[' || \
   data[i]==','  || data[i]==':' || data[i]==';')
Definition at line 198 of file markdown.cpp.
PRETTY_FUNC
#define PRETTY_FUNC __PRETTY_FUNCTION__
Definition at line 73 of file markdown.cpp.
TRACE
#define TRACE (data) Trace trace_(PRETTY_FUNC,data);
Definition at line 174 of file markdown.cpp.
TRACE_MORE
#define TRACE_MORE (...) trace_.trace(__VA_ARGS__);
Definition at line 175 of file markdown.cpp.
TRACE_RESULT
#define TRACE_RESULT (v) trace_.setResult(v);
Definition at line 176 of file markdown.cpp.
Enumeration Type Documentation
Alignment
enum Alignment
Enumerator
AlignNone
AlignLeft
AlignCenter
AlignRight
Definition at line 237 of file markdown.cpp.
{ AlignNone, AlignLeft, AlignCenter, AlignRight };
ExplicitPageResult
enum class ExplicitPageResult strong
Enumerator
explicitPage
docs start with a page command
explicitMainPage
docs start with a mainpage command
notExplicit
docs doesn't start with either page or mainpage
Definition at line 56 of file markdown.cpp.
{
  explicitPage,      /**< docs start with a page command */
  explicitMainPage,  /**< docs start with a mainpage command */
  notExplicit        /**< docs doesn't start with either page or mainpage */
};
Function Documentation
computeIndentExcludingListMarkers()
static int computeIndentExcludingListMarkers (const char * data, int size) static
Definition at line 2089 of file markdown.cpp.
{
  TRACE(data);
  int i=0;
  int indent=0;
  bool isDigit=FALSE;
  bool isLi=FALSE;
  bool listMarkerSkipped=FALSE;
  while (i<size &&
         (data[i]==' ' ||                                    // space
          (!listMarkerSkipped &&                             // first list marker
           (data[i]=='+' || data[i]=='-' || data[i]=='*' ||  // unordered list char
            (data[i]=='#' && i>0 && data[i-1]=='-') ||       // -# item
            (isDigit=(data[i]>='1' && data[i]<='9')) ||      // ordered list marker?
            (isLi=(i<size-3 && isLiTag(i)))                  // <li> tag
           )
          )
         )
        )
  {
    if (isDigit) // skip over ordered list marker '10. '
    {
      int j=i+1;
      while (j<size && ((data[j]>='0' && data[j]<='9') || data[j]=='.'))
      {
        if (data[j]=='.') // should be end of the list marker
        {
          if (j<size-1 && data[j+1]==' ') // valid list marker
          {
            listMarkerSkipped=TRUE;
            indent+=j+1-i;
            i=j+1;
            break;
          }
          else // not a list marker
          {
            break;
          }
        }
        j++;
      }
    }
    else if (isLi)
    {
      i+=3; // skip over <li>
      indent+=3;
      listMarkerSkipped=TRUE;
    }
    else if (data[i]=='-' && i<size-2 && data[i+1]=='#' && data[i+2]==' ')
    { // case "-# "
      listMarkerSkipped=TRUE; // only a single list marker is accepted
      i++; // skip over #
      indent++;
    }
    else if (data[i]!=' ' && i<size-1 && data[i+1]==' ')
    { // case "- " or "+ " or "* "
      listMarkerSkipped=TRUE; // only a single list marker is accepted
    }
    if (data[i]!=' ' && !listMarkerSkipped)
    { // end of indent
      break;
    }
    indent++,i++;
  }
  //printf("{%s}->%d\n",QCString(data).qPrint(left(size)),indent);
  TRACE_RESULT(indent);
  return indent;
}
References FALSE, isLiTag, TRACE, TRACE_RESULT, and TRUE.
Referenced by isCodeBlock(), and isListMarker().
convertStringFragment()
static void convertStringFragment (QCString & result, const char * data, int size) static
Definition at line 327 of file markdown.cpp.
{
  TRACE(result);
  if (size<0) size=0;
  result = QCString(data,static_cast<size_t>(size));
  TRACE_RESULT(result);
}
References TRACE, and TRACE_RESULT.
Referenced by Markdown::extractPageTitle(), Markdown::isAtxHeader(), isFencedCodeBlock(), isLinkRef(), Markdown::processBlocks(), Markdown::processCodeSpan(), Markdown::processHtmlTagWrite(), and Markdown::processLink().
escapeDoubleQuotes()
static QCString escapeDoubleQuotes (const QCString & s) static
Definition at line 260 of file markdown.cpp.
{
  TRACE(s);
  if (s.isEmpty()) return s;
  GrowBuf growBuf;
  const char *p=s.data();
  char c,pc='\0';
  while ((c=*p++))
  {
    switch (c)
    {
      case '"':  if (pc!='\\')  { growBuf.addChar('\\'); } growBuf.addChar(c);   break;
      default:   growBuf.addChar(c); break;
    }
    pc=c;
  }
  growBuf.addChar(0);
  TRACE_RESULT(growBuf.get());
  return growBuf.get();
}
References GrowBuf::addChar(), QCString::data(), GrowBuf::get(), QCString::isEmpty(), TRACE, and TRACE_RESULT.
Referenced by Markdown::writeMarkdownImage().
escapeSpecialChars()
static QCString escapeSpecialChars (const QCString & s) static
Definition at line 281 of file markdown.cpp.
{
  TRACE(s);
  if (s.isEmpty()) return s;
  bool insideQuote=FALSE;
  GrowBuf growBuf;
  const char *p=s.data();
  char c,pc='\0';
  while ((c=*p++))
  {
    switch (c)
    {
      case '"':  if (pc!='\\')  { insideQuote=!insideQuote; } growBuf.addChar(c);   break;
      case '<':
      case '>':  if (!insideQuote)
                 {
                   growBuf.addChar('\\');
                   growBuf.addChar(c);
                   if ((p[0] == ':') && (p[1] == ':'))
                   {
                     growBuf.addChar('\\');
                     growBuf.addChar(':');
                     p++;
                   }
                 }
                 else
                 {
                   growBuf.addChar(c);
                 }
                 break;
      case '\\': if (!insideQuote) { growBuf.addChar('\\'); } growBuf.addChar('\\'); break;
      case '@':  if (!insideQuote) { growBuf.addChar('\\'); } growBuf.addChar('@'); break;
      // commented out next line due to regression when using % to suppress a link
      //case '%':  if (!insideQuote) { growBuf.addChar('\\'); } growBuf.addChar('%'); break;
      case '#':  if (!insideQuote) { growBuf.addChar('\\'); } growBuf.addChar('#'); break;
      case '$':  if (!insideQuote) { growBuf.addChar('\\'); } growBuf.addChar('$'); break;
      case '&':  if (!insideQuote) { growBuf.addChar('\\'); } growBuf.addChar('&'); break;
      default:   growBuf.addChar(c); break;
    }
    pc=c;
  }
  growBuf.addChar(0);
  TRACE_RESULT(growBuf.get());
  return growBuf.get();
}
References GrowBuf::addChar(), QCString::data(), FALSE, GrowBuf::get(), QCString::isEmpty(), TRACE, and TRACE_RESULT.
Referenced by Markdown::processCodeSpan().
extractTitleId()
static QCString extractTitleId (QCString & title, int level) static
Definition at line 1974 of file markdown.cpp.
{
  TRACE(title);
  // match e.g. '{#id-b11} ' and capture 'id-b11'
  static const reg::Ex r2(R"({#(\a[\w-]*)}\s*$)");
  reg::Match match;
  std::string ti = title.str();
  if (reg::search(ti,match,r2))
  {
    std::string id = match[1].str();
    title = title.left(match.position());
    //printf("found match id='%s' title=%s\n",id.c_str(),qPrint(title));
    TRACE_RESULT(QCString(id));
    return QCString(id);
  }
  if ((level > 0) && (level <= Config_getInt(TOC_INCLUDE_HEADINGS)))
  {
    static AtomicInt autoId { 0 };
    QCString id;
    id.sprintf("autotoc_md%d",autoId++);
    //printf("auto-generated id='%s' title='%s'\n",qPrint(id),qPrint(title));
    TRACE_RESULT(id);
    return id;
  }
  //printf("no id found in title '%s'\n",qPrint(title));
  return "";
}
References AtomicInt, Config_getInt, QCString::left(), reg::search(), QCString::sprintf(), QCString::str(), TRACE, and TRACE_RESULT.
Referenced by Markdown::extractPageTitle(), Markdown::isAtxHeader(), and Markdown::processBlocks().
findTableColumns()
int findTableColumns (const char * data, int size, int & start, int & end, int & columns)
Finds the location of the table's contains in the string data.
Only one line will be inspected.
Parameters
[in] data pointer to the string buffer.
[in] size the size of the buffer.
[out] start offset of the first character of the table content
[out] end offset of the last character of the table content
[out] columns number of table columns found
Returns
The offset until the next line in the buffer.
Definition at line 2343 of file markdown.cpp.
{
  TRACE(data);
  int i=0,n=0;
  int eol;
  // find start character of the table line
  while (i<size && data[i]==' ') i++;
  if (i<size && data[i]=='|' && data[i]!='\n') i++,n++; // leading | does not count
  start = i;
  // find end character of the table line
  //while (i<size && data[i]!='\n') i++;
  //eol=i+1;
  int j = 0;
  while (i<size && (j = isNewline(data + i))==0) i++;
  eol=i+j;
  i--;
  while (i>0 && data[i]==' ') i--;
  if (i>0 && data[i-1]!='\\' && data[i]=='|') i--,n++; // trailing or escaped | does not count
  end = i;
  // count columns between start and end
  columns=0;
  if (end>start)
  {
    i=start;
    while (i<=end) // look for more column markers
    {
      if (data[i]=='|' && (i==0 || data[i-1]!='\\')) columns++;
      if (columns==1) columns++; // first | make a non-table into a two column table
      i++;
    }
  }
  if (n==2 && columns==0) // table row has | ... |
  {
    columns++;
  }
  //printf("findTableColumns(start=%d,end=%d,columns=%d) eol=%d\n",
  //    start,end,columns,eol);
  TRACE_RESULT(eol);
  return eol;
}
References end(), eol, isNewline(), TRACE, and TRACE_RESULT.
Referenced by isTableBlock(), and Markdown::writeTableBlock().
getFilteredImageAttributes()
static QCString getFilteredImageAttributes (const char * fmt, const QCString & attrs) static
parse the image attributes and return attributes for given format
Definition at line 360 of file markdown.cpp.
{
  StringVector attrList = split(attrs.str(),",");
  for (const auto &attr_ : attrList)
  {
    QCString attr = QCString(attr_).stripWhiteSpace();
    int i = attr.find(':');
    if (i>0) // has format
    {
      QCString format = attr.left(i).stripWhiteSpace().lower();
      if (format == fmt) // matching format
      {
        return attr.mid(i+1); // keep part after :
      }
    }
    else // option that applies to all formats
    {
      return attr;
    }
  }
  return QCString();
}
References QCString::find(), QCString::left(), QCString::lower(), QCString::mid(), split(), QCString::str(), and QCString::stripWhiteSpace().
Referenced by Markdown::writeMarkdownImage().
hasLineBreak()
static bool hasLineBreak (const char * data, int size) static
Definition at line 2632 of file markdown.cpp.
{
  TRACE(data);
  int i=0;
  int j=0;
  // search for end of line and also check if it is not a completely blank
  while (i<size && data[i]!='\n')
  {
    if (data[i]!=' ' && data[i]!='\t') j++; // some non whitespace
    i++;
  }
  if (i>=size) { TRACE_RESULT(0); return 0; } // empty line
  if (i<2)     { TRACE_RESULT(0); return 0; } // not long enough
  bool res = (j>0 && data[i-1]==' ' && data[i-2]==' '); // non blank line with at two spaces at the end
  TRACE_RESULT(res);
  return res;
}
References TRACE, and TRACE_RESULT.
Referenced by Markdown::writeOneLineHeaderOrRuler().
isBlockQuote()
bool isBlockQuote (const char * data, int size, int indent)
returns TRUE if this line starts a block quote
Definition at line 1822 of file markdown.cpp.
{
  TRACE(data);
  int i = 0;
  while (i<size && data[i]==' ') i++;
  if (i<indent+codeBlockIndent) // could be a quotation
  {
    // count >'s and skip spaces
    int level=0;
    while (i<size && (data[i]=='>' || data[i]==' '))
    {
      if (data[i]=='>') level++;
      i++;
    }
    // last characters should be a space or newline,
    // so a line starting with >= does not match, but only when level equals 1
    bool res = (level>0 && i<size && ((data[i-1]==' ') || data[i]=='\n')) || (level > 1);
    TRACE_RESULT(res);
    return res;
  }
  else // too much indentation -> code block
  {
    TRACE_RESULT(FALSE);
    return FALSE;
  }
  //return i<size && data[i]=='>' && i<indent+codeBlockIndent;
}
References codeBlockIndent, FALSE, TRACE, and TRACE_RESULT.
Referenced by Markdown::processQuotations().
isCodeBlock()
static bool isCodeBlock (const char * data, int offset, int size, int & indent) static
Definition at line 2253 of file markdown.cpp.
{
  TRACE(data);
  //printf("<isCodeBlock(offset=%d,size=%d,indent=%d)\n",offset,size,indent);
  // determine the indent of this line
  int i=0;
  int indent0=0;
  while (i<size && data[i]==' ') indent0++,i++;
  if (indent0<codeBlockIndent)
  {
    //printf(">isCodeBlock: line is not indented enough %d<4\n",indent0);
    TRACE_RESULT(FALSE);
    return FALSE;
  }
  if (indent0>=size || data[indent0]=='\n') // empty line does not start a code block
  {
    //printf("only spaces at the end of a comment block\n");
    TRACE_RESULT(FALSE);
    return FALSE;
  }
  i=offset;
  int nl=0;
  int nl_pos[3];
  // search back 3 lines and remember the start of lines -1 and -2
  while (i>0 && nl<3)
  {
    int j = i-offset-1;
    int nl_size = isNewline(data+j);
    if (nl_size>0)
    {
      nl_pos[nl++]=j+nl_size;
    }
    i--;
  }
  // if there are only 2 preceding lines, then line -2 starts at -offset
  if (i==0 && nl==2) nl_pos[nl++]=-offset;
  //printf("  nl=%d\n",nl);
  if (nl==3) // we have at least 2 preceding lines
  {
    //printf("  positions: nl_pos=[%d,%d,%d] line[-2]='%s' line[-1]='%s'\n",
    //    nl_pos[0],nl_pos[1],nl_pos[2],
    //    qPrint(QCString(data+nl_pos[1]).left(nl_pos[0]-nl_pos[1]-1)),
    //    qPrint(QCString(data+nl_pos[2]).left(nl_pos[1]-nl_pos[2]-1)));
    // check that line -1 is empty
    if (!isEmptyLine(data+nl_pos[1],nl_pos[0]-nl_pos[1]-1))
    {
      TRACE_RESULT(FALSE);
      return FALSE;
    }
    // determine the indent of line -2
    indent=std::max(indent,computeIndentExcludingListMarkers(data+nl_pos[2],nl_pos[1]-nl_pos[2]));
    //printf(">isCodeBlock local_indent %d>=%d+%d=%d\n",
    //    indent0,indent,codeBlockIndent,indent0>=indent+codeBlockIndent);
    // if the difference is >4 spaces -> code block
    bool res = indent0>=indent+codeBlockIndent;
    TRACE_RESULT(res);
    return res;
  }
  else // not enough lines to determine the relative indent, use global indent
  {
    // check that line -1 is empty
    if (nl==1 && !isEmptyLine(data-offset,offset-1))
    {
      TRACE_RESULT(FALSE);
      return FALSE;
    }
    //printf(">isCodeBlock global indent %d>=%d+4=%d nl=%d\n",
    //    indent0,indent,indent0>=indent+4,nl);
    bool res = indent0>=indent+codeBlockIndent;
    TRACE_RESULT(res);
    return res;
  }
}
References codeBlockIndent, computeIndentExcludingListMarkers(), FALSE, isEmptyLine(), isNewline(), TRACE, and TRACE_RESULT.
Referenced by Markdown::processBlocks().
isEmptyLine()
static bool isEmptyLine (const char * data, int size) static
Definition at line 2067 of file markdown.cpp.
{
  TRACE(data);
  int i=0;
  while (i<size)
  {
    if (data[i]=='\n') { TRACE_RESULT(TRUE);  return TRUE; }
    if (data[i]!=' ')  { TRACE_RESULT(FALSE); return FALSE; }
    i++;
  }
  TRACE_RESULT(TRUE);
  return TRUE;
}
References FALSE, TRACE, TRACE_RESULT, and TRUE.
Referenced by isCodeBlock(), Markdown::processBlocks(), and Markdown::processQuotations().
isEndOfList()
static bool isEndOfList (const char * data, int size) static
Definition at line 2169 of file markdown.cpp.
{
  TRACE(data);
  int dots=0;
  int i=0;
  // end of list marker is an otherwise empty line with a dot.
  while (i<size)
  {
    if (data[i]=='.')
    {
      dots++;
    }
    else if (data[i]=='\n')
    {
      break;
    }
    else if (data[i]!=' ' && data[i]!='\t') // bail out if the line is not empty
    {
      TRACE_RESULT(FALSE);
      return FALSE;
    }
    i++;
  }
  TRACE_RESULT(dots==1);
  return dots==1;
}
References FALSE, TRACE, and TRACE_RESULT.
Referenced by Markdown::processBlocks(), and Markdown::processQuotations().
isExplicitPage()
static ExplicitPageResult isExplicitPage (const QCString & docs) static
Definition at line 3257 of file markdown.cpp.
{
  TRACE(docs);
  int i=0;
  const char *data = docs.data();
  if (data)
  {
    int size=docs.size();
    while (i<size && (data[i]==' ' || data[i]=='\n'))
    {
      i++;
    }
    if (i<size+1 &&
        (data[i]=='\\' || data[i]=='@') &&
        (qstrncmp(&data[i+1],"page ",5)==0 || qstrncmp(&data[i+1],"mainpage",8)==0)
       )
    {
      if (qstrncmp(&data[i+1],"page ",5)==0)
      {
        TRACE_RESULT(ExplicitPageResult::explicitPage);
        return ExplicitPageResult::explicitPage;
      }
      else
      {
        TRACE_RESULT(ExplicitPageResult::explicitMainPage);
        return ExplicitPageResult::explicitMainPage;
      }
    }
  }
  TRACE_RESULT(ExplicitPageResult::notExplicit);
  return ExplicitPageResult::notExplicit;
}
References QCString::data(), explicitMainPage, explicitPage, notExplicit, qstrncmp(), QCString::size(), TRACE, and TRACE_RESULT.
Referenced by MarkdownOutlineParser::parseInput().
isFencedCodeBlock()
static bool isFencedCodeBlock (const char * data, int size, int refIndent, QCString & lang, int & start, int & end, int & offset) static
Definition at line 2196 of file markdown.cpp.
{
  TRACE(data);
  // rules: at least 3 ~~~, end of the block same amount of ~~~'s, otherwise
  // return FALSE
  int i=0;
  int indent=0;
  int startTildes=0;
  while (i<size && data[i]==' ') indent++,i++;
  if (indent>=refIndent+4)
  {
    //printf("content is part of code block: indent=%d refIndent=%d\n",indent,refIndent);
    TRACE_RESULT(FALSE);
    return FALSE;
  } // part of code block
  char tildaChar='~';
  if (i<size && data[i]=='`') tildaChar='`';
  while (i<size && data[i]==tildaChar) startTildes++,i++;
  if (startTildes<3)
  {
    //printf("no fence marker found #tildes=%d\n",startTildes);
    TRACE_RESULT(FALSE);
    return FALSE;
  } // not enough tildes
  if (i<size && data[i]=='{') i++; // skip over optional {
  int startLang=i;
  while (i<size && (data[i]!='\n' && data[i]!='}' && data[i]!=' ')) i++;
  convertStringFragment(lang,data+startLang,i-startLang);
  while (i<size && data[i]!='\n') i++; // proceed to the end of the line
  start=i;
  while (i<size)
  {
    if (data[i]==tildaChar)
    {
      end=i;
      int endTildes=0;
      while (i<size && data[i]==tildaChar) endTildes++,i++;
      while (i<size && data[i]==' ') i++;
      if (i==size || data[i]=='\n')
      {
        if (endTildes==startTildes)
        {
          offset=i;
          //printf("found end marker at offset %d\n",offset);
          TRACE_RESULT(TRUE);
          return TRUE;
        }
      }
    }
    i++;
  }
  //printf("no end marker found!\n");
  TRACE_RESULT(FALSE);
  return FALSE;
}
References convertStringFragment(), end(), FALSE, TRACE, TRACE_RESULT, and TRUE.
Referenced by Markdown::processBlocks(), and Markdown::processQuotations().
isHRuler()
static bool isHRuler (const char * data, int size) static
Definition at line 1944 of file markdown.cpp.
{
  TRACE(data);
  int i=0;
  if (size>0 && data[size-1]=='\n') size--; // ignore newline character
  while (i<size && data[i]==' ') i++;
  if (i>=size) { TRACE_RESULT(FALSE); return FALSE; } // empty line
  char c=data[i];
  if (c!='*' && c!='-' && c!='_')
  {
    TRACE_RESULT(FALSE); return FALSE; // not a hrule character
  }
  int n=0;
  while (i<size)
  {
    if (data[i]==c)
    {
      n++; // count rule character
    }
    else if (data[i]!=' ')
    {
      TRACE_RESULT(FALSE);
      return FALSE; // line contains non hruler characters
    }
    i++;
  }
  TRACE_RESULT(n>=3);
  return n>=3; // at least 3 characters needed for a hruler
}
References FALSE, TRACE, and TRACE_RESULT.
Referenced by Markdown::writeOneLineHeaderOrRuler().
isLinkRef()
static int isLinkRef (const char * data, int size, QCString & refid, QCString & link, QCString & title) static
returns end of the link ref if this is indeed a link reference.
Definition at line 1851 of file markdown.cpp.
{
  TRACE(data);
  //printf("isLinkRef data={%s}\n",data);
  // format: start with [some text]:
  int i = 0;
  while (i<size && data[i]==' ') i++;
  if (i>=size || data[i]!='[') { TRACE_RESULT(0); return 0; }
  i++;
  int refIdStart=i;
  while (i<size && data[i]!='\n' && data[i]!=']') i++;
  if (i>=size || data[i]!=']') { TRACE_RESULT(0); return 0; }
  convertStringFragment(refid,data+refIdStart,i-refIdStart);
  if (refid.isEmpty()) { TRACE_RESULT(0); return 0; }
  //printf("  isLinkRef: found refid='%s'\n",qPrint(refid));
  i++;
  if (i>=size || data[i]!=':') { TRACE_RESULT(0); return 0; }
  i++;
  // format: whitespace* \n? whitespace* (<url> | url)
  while (i<size && data[i]==' ') i++;
  if (i<size && data[i]=='\n')
  {
    i++;
    while (i<size && data[i]==' ') i++;
  }
  if (i>=size) { TRACE_RESULT(0); return 0; }
  if (i<size && data[i]=='<') i++;
  int linkStart=i;
  while (i<size && data[i]!=' ' && data[i]!='\n') i++;
  int linkEnd=i;
  if (i<size && data[i]=='>') i++;
  if (linkStart==linkEnd) { TRACE_RESULT(0); return 0; } // empty link
  convertStringFragment(link,data+linkStart,linkEnd-linkStart);
  //printf("  isLinkRef: found link='%s'\n",qPrint(link));
  if (link=="@ref" || link=="\\ref")
  {
    int argStart=i;
    while (i<size && data[i]!='\n' && data[i]!='"') i++;
    QCString refArg;
    convertStringFragment(refArg,data+argStart,i-argStart);
    link+=refArg;
  }
  title.resize(0);
  // format: (whitespace* \n? whitespace* ( 'title' | "title" | (title) ))?
  int eol=0;
  while (i<size && data[i]==' ') i++;
  if (i<size && data[i]=='\n')
  {
    eol=i;
    i++;
    while (i<size && data[i]==' ') i++;
  }
  if (i>=size)
  {
    //printf("end of isLinkRef while looking for title! i=%d\n",i);
    TRACE_RESULT(i);
    return i; // end of buffer while looking for the optional title
  }
  char c = data[i];
  if (c=='\'' || c=='"' || c=='(') // optional title present?
  {
    //printf("  start of title found! char='%c'\n",c);
    i++;
    if (c=='(') c=')'; // replace c by end character
    int titleStart=i;
    // search for end of the line
    while (i<size && data[i]!='\n') i++;
    eol = i;
    // search back to matching character
    int end=i-1;
    while (end>titleStart && data[end]!=c) end--;
    if (end>titleStart)
    {
      convertStringFragment(title,data+titleStart,end-titleStart);
    }
    //printf("  title found: '%s'\n",qPrint(title));
  }
  while (i<size && data[i]==' ') i++;
  //printf("end of isLinkRef: i=%d size=%d data[i]='%c' eol=%d\n",
  //    i,size,data[i],eol);
  if      (i>=size)       { TRACE_RESULT(i);   return i; }    // end of buffer while ref id was found
  else if (eol)           { TRACE_RESULT(eol); return eol; }  // end of line while ref id was found
  TRACE_RESULT(0);
  return 0;                            // invalid link ref
}
References convertStringFragment(), end(), eol, QCString::isEmpty(), QCString::resize(), TRACE, and TRACE_RESULT.
Referenced by Markdown::processBlocks().
isListMarker()
static int isListMarker (const char * data, int size) static
Definition at line 2158 of file markdown.cpp.
{
  TRACE(data);
  int normalIndent = 0;
  while (normalIndent<size && data[normalIndent]==' ') normalIndent++;
  int listIndent = computeIndentExcludingListMarkers(data,size);
  int result = listIndent>normalIndent ? listIndent : 0;
  TRACE_RESULT(result);
  return result;
}
References computeIndentExcludingListMarkers(), TRACE, and TRACE_RESULT.
Referenced by Markdown::processBlocks(), and Markdown::processQuotations().
isNewline()
int isNewline (const char * data) inline
Definition at line 250 of file markdown.cpp.
{
  // normal newline
  if (data[0] == '\n') return 1;
  // artificial new line from ^^ in ALIASES
  if (data[0] == '\\' && qstrncmp(data+1,"ilinebr ",7)==0) return data[8]==' ' ? 9 : 8;
  return 0;
}
References qstrncmp().
Referenced by Markdown::findEndOfLine(), findTableColumns(), and isCodeBlock().
isTableBlock()
static bool isTableBlock (const char * data, int size) static
Returns TRUE iff data points to the start of a table block.
Definition at line 2388 of file markdown.cpp.
{
  TRACE(data);
  int cc0,start,end;
  // the first line should have at least two columns separated by '|'
  int i = findTableColumns(data,size,start,end,cc0);
  if (i>=size || cc0<1)
  {
    //printf("isTableBlock: no |'s in the header\n");
    TRACE_RESULT(FALSE);
    return FALSE;
  }
  int cc1;
  int ret = findTableColumns(data+i,size-i,start,end,cc1);
  int j=i+start;
  // separator line should consist of |, - and : and spaces only
  while (j<=end+i)
  {
    if (data[j]!=':' && data[j]!='-' && data[j]!='|' && data[j]!=' ')
    {
      //printf("isTableBlock: invalid character '%c'\n",data[j]);
      TRACE_RESULT(FALSE);
      return FALSE; // invalid characters in table separator
    }
    j++;
  }
  if (cc1!=cc0) // number of columns should be same as previous line
  {
    TRACE_RESULT(FALSE);
    return FALSE;
  }
  i+=ret; // goto next line
  int cc2;
  findTableColumns(data+i,size-i,start,end,cc2);
  //printf("isTableBlock: %d\n",cc1==cc2);
  TRACE_RESULT(cc1==cc2);
  return cc1==cc2;
}
References end(), FALSE, findTableColumns(), TRACE, and TRACE_RESULT.
Referenced by Markdown::processBlocks().
markdownFileNameToId()
QCString markdownFileNameToId (const QCString & fileName)
processes string s and converts markdown into doxygen/html commands.
Definition at line 3462 of file markdown.cpp.
{
  TRACE(fileName);
  std::string absFileName = FileInfo(fileName.str()).absFilePath();
  QCString baseFn  = stripFromPath(absFileName.c_str());
  int i = baseFn.findRev('.');
  if (i!=-1) baseFn = baseFn.left(i);
  QCString baseName = baseFn;
  char *p = baseName.rawData();
  char c;
  while ((c=*p))
  {
    if (!isId(c)) *p='_'; // escape characters that do not yield an identifier by underscores
    p++;
  }
  //printf("markdownFileNameToId(%s)=md_%s\n",qPrint(fileName),qPrint(baseName));
  QCString res = "md_"+baseName;
  TRACE_RESULT(res);
  return res;
}
References FileInfo::absFilePath(), QCString::findRev(), isId(), QCString::left(), QCString::rawData(), QCString::str(), stripFromPath(), TRACE, and TRACE_RESULT.
Referenced by DocRef::DocRef(), DocSecRefItem::parse(), and MarkdownOutlineParser::parseInput().
markersToAlignment()
static Alignment markersToAlignment (bool leftMarker, bool rightMarker) static
helper function to convert presence of left and/or right alignment markers to a alignment value
Definition at line 338 of file markdown.cpp.
{
  //printf("markerToAlignment(%d,%d)\n",leftMarker,rightMarker);
  if (leftMarker && rightMarker)
  {
    return AlignCenter;
  }
  else if (leftMarker)
  {
    return AlignLeft;
  }
  else if (rightMarker)
  {
    return AlignRight;
  }
  else
  {
    return AlignNone;
  }
}
References AlignCenter, AlignLeft, AlignNone, and AlignRight.
Referenced by Markdown::writeTableBlock().
Variable Documentation
codeBlockIndent
const int codeBlockIndent = 4
Definition at line 244 of file markdown.cpp.
Referenced by isBlockQuote(), isCodeBlock(), Markdown::processBlocks(), and Markdown::writeCodeBlock().
g_doxy_nbsp
const char* g_doxy_nbsp = "&_doxy_nbsp;"
Definition at line 243 of file markdown.cpp.
Referenced by Markdown::addStrEscapeUtf8Nbsp(), Markdown::detab(), and Markdown::process().
g_utf8_nbsp
const char* g_utf8_nbsp = "\xc2\xa0"
Definition at line 242 of file markdown.cpp.
Referenced by Markdown::addStrEscapeUtf8Nbsp().