Doxygen: /home/runner/work/doxygen/doxygen/src/debug.cpp File Reference
debug.cpp File Reference
#include <stdarg.h>
#include <algorithm>
#include <stdio.h>
#include <map>
#include <string>
#include <chrono>
#include "debug.h"
#include "message.h"
#include "qcstring.h"
Classes
class Timer
Functions
static char asciiToLower (char in)
static int labelToEnumValue (const QCString &l)
Variables
static std::map< std::string, Debug::DebugMask > s_labels
static Timer g_runningTime
Function Documentation
asciiToLower()
static char asciiToLower (char in) static
Definition at line 69 of file debug.cpp.
{
    if (in <= 'Z' && in >= 'A')
        return in - ('Z' - 'z');
    return in;
}
Referenced by labelToEnumValue().
labelToEnumValue()
static int labelToEnumValue (const QCString & l) static
Definition at line 75 of file debug.cpp.
{
  std::string s = l.str();
  std::transform(s.begin(),s.end(),s.begin(),asciiToLower);
  auto it = s_labels.find(s);
  return (it!=s_labels.end()) ? it->second : 0;
}
References asciiToLower(), s_labels, and QCString::str().
Referenced by Debug::setFlagStr().
Variable Documentation
g_runningTime
Timer g_runningTime static
Definition at line 138 of file debug.cpp.
Referenced by Debug::elapsedTime(), and Debug::startTimer().
s_labels
std::map< std::string, Debug::DebugMask > s_labels static
Initial value:
=
{
  { "findmembers",       Debug::FindMembers       },
  { "functions",         Debug::Functions         },
  { "variables",         Debug::Variables         },
  { "preprocessor",      Debug::Preprocessor      },
  { "nolineno",          Debug::NoLineNo          },
  { "classes",           Debug::Classes           },
  { "commentcnv",        Debug::CommentCnv        },
  { "commentscan",       Debug::CommentScan       },
  { "printtree",         Debug::PrintTree         },
  { "time",              Debug::Time              },
  { "extcmd",            Debug::ExtCmd            },
  { "markdown",          Debug::Markdown          },
  { "filteroutput",      Debug::FilterOutput      },
  { "lex",               Debug::Lex               },
  { "plantuml",          Debug::Plantuml          },
  { "fortranfixed2free", Debug::FortranFixed2Free },
  { "cite",              Debug::Cite              },
  { "rtf",               Debug::Rtf               },
  { "qhp",               Debug::Qhp               },
  { "tag",               Debug::Tag               },
}
Definition at line 29 of file debug.cpp.
Referenced by labelToEnumValue(), and Debug::printFlags().