Doxygen: ManCodeGenerator Class Reference
ManCodeGenerator Class Reference
Generator for Man page code fragments.
#include <mangen.h>
Public Member Functions
ManCodeGenerator (TextStream &t)
OutputType type () const override
void codify (const QCString &text) override
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip) override
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &) override
void writeLineNumber (const QCString &, const QCString &, const QCString &, int l, bool) override
void startCodeLine (bool) override
void endCodeLine () override
void startFontClass (const QCString &) override
void endFontClass () override
void writeCodeAnchor (const QCString &) override
void startCodeFragment (const QCString &style) override
void endCodeFragment (const QCString &) override
Public Member Functions inherited from CodeOutputInterface
CodeOutputInterface ()=default
CodeOutputInterface (const CodeOutputInterface &)=delete
CodeOutputInterface & operator= (const CodeOutputInterface &)=delete
virtual ~CodeOutputInterface ()=default
virtual OutputType type () const =0
virtual int id () const
Identifier for the output file.
virtual void setId (int id)
virtual void setEnabled (bool e)
virtual bool isEnabled () const
virtual void codify (const QCString &s)=0
virtual void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)=0
virtual void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)=0
virtual void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)=0
virtual void startCodeLine (bool hasLineNumbers)=0
virtual void endCodeLine ()=0
virtual void startFontClass (const QCString &clsName)=0
virtual void endFontClass ()=0
virtual void writeCodeAnchor (const QCString &name)=0
virtual void setCurrentDoc (const Definition *context, const QCString &anchor, bool isSourceFile)
virtual void addWord (const QCString &word, bool hiPriority)
virtual void startCodeFragment (const QCString &style)=0
virtual void endCodeFragment (const QCString &style)=0
Private Attributes
int m_col = 0
TextStream & m_t
Detailed Description
Generator for Man page code fragments.
Definition at line 24 of file mangen.h.
Constructor & Destructor Documentation
ManCodeGenerator()
ManCodeGenerator::ManCodeGenerator (TextStream & t) inline
Definition at line 27 of file mangen.h.
: m_t(t) {}
Member Function Documentation
codify()
void ManCodeGenerator::codify (const QCString & s) override virtual
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 148 of file mangen.cpp.
{
  //static char spaces[]="        ";
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    int spacesToNextTabStop;
    while (*p)
    {
      c=*p++;
      switch(c)
      {
        case '-':  m_t << "\\-"; break; // see  bug747780
        case '.':   m_t << "\\&."; break; // see  bug652277
        case '\t':  spacesToNextTabStop =
                          Config_getInt(TAB_SIZE) - (m_col%Config_getInt(TAB_SIZE));
                    m_t << Doxygen::spaces.left(spacesToNextTabStop);
                    m_col+=spacesToNextTabStop;
                    break;
        case '\n':  m_t << "\n"; m_col=0; break;
        case '\\':  m_t << "\\\\"; m_col++; break;
        case '\"':  // no break!
        default:    p=writeUTF8Char(m_t,p-1); m_col++; break;
      }
    }
    //printf("%s",str);fflush(stdout);
  }
}
References Config_getInt, QCString::data(), QCString::isEmpty(), QCString::left(), m_col, m_t, Doxygen::spaces, and writeUTF8Char().
Referenced by endCodeLine().
endCodeFragment()
void ManCodeGenerator::endCodeFragment (const QCString & style) override virtual
Ends a block of code
Implements CodeOutputInterface.
Definition at line 116 of file mangen.cpp.
{
  if (m_col>0) m_t << "\n";
  m_t << ".fi\n";
  m_col=0;
}
References m_col, and m_t.
endCodeLine()
void ManCodeGenerator::endCodeLine () inline override virtual
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 46 of file mangen.h.
{ codify("\n"); m_col=0; }
References codify(), and m_col.
endFontClass()
void ManCodeGenerator::endFontClass () inline override virtual
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 48 of file mangen.h.
{}
startCodeFragment()
void ManCodeGenerator::startCodeFragment (const QCString & style) override virtual
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 110 of file mangen.cpp.
{
  m_t << ".PP\n";
  m_t << ".nf\n";
}
References m_t.
startCodeLine()
void ManCodeGenerator::startCodeLine (bool) inline override virtual
Implements CodeOutputInterface.
Definition at line 45 of file mangen.h.
{}
startFontClass()
void ManCodeGenerator::startFontClass (const QCString & clsName) inline override virtual
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 47 of file mangen.h.
{}
type()
OutputType ManCodeGenerator::type () const inline override virtual
Implements CodeOutputInterface.
Definition at line 29 of file mangen.h.
{ return OutputType::Man; }
writeCodeAnchor()
void ManCodeGenerator::writeCodeAnchor (const QCString & name) inline override virtual
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 49 of file mangen.h.
{}
writeCodeLink()
void ManCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) override virtual
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 123 of file mangen.cpp.
{
  if (!name.isEmpty())
  {
    const char *p=name.data();
    char c=0;
    while ((c=*p++))
    {
      switch(c)
      {
        case '-':  m_t << "\\-"; break; // see  bug747780
        case '.':  m_t << "\\&."; break; // see  bug652277
        case '\\': m_t << "\\\\"; m_col++; break;
        case '\n': m_t << "\n"; m_col=0; break;
        case '\"':  c = '\''; // no break!
        default: m_t << c; m_col++; break;
      }
    }
    //printf("%s",str);fflush(stdout);
  }
}
References QCString::data(), QCString::isEmpty(), m_col, and m_t.
writeLineNumber()
void ManCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) inline override virtual
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 43 of file mangen.h.
    { m_t << l << " "; m_col=0; }
References m_col, and m_t.
writeTooltip()
void ManCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) inline override virtual
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 36 of file mangen.h.
                                {}
Member Data Documentation
m_col
int ManCodeGenerator::m_col = 0 private
Definition at line 54 of file mangen.h.
Referenced by codify(), endCodeFragment(), endCodeLine(), writeCodeLink(), and writeLineNumber().
m_t
TextStream& ManCodeGenerator::m_t private
Definition at line 55 of file mangen.h.
Referenced by codify(), endCodeFragment(), startCodeFragment(), writeCodeLink(), and writeLineNumber().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/mangen.h
/home/runner/work/doxygen/doxygen/src/mangen.cpp