Doxygen: TextGeneratorOLImpl Class Reference
TextGeneratorOLImpl Class Reference
Implements TextGeneratorIntf for an OutputDocInterface stream.
#include <util.h>
Public Member Functions
TextGeneratorOLImpl (BaseOutputDocInterface &od)
void writeString (const QCString &s, bool keepSpaces) const
void writeBreak (int indent) const
void writeLink (const QCString &extRef, const QCString &file, const QCString &anchor, const QCString &text) const
Public Member Functions inherited from TextGeneratorIntf
virtual ~TextGeneratorIntf ()=default
virtual void writeString (const QCString &, bool) const =0
virtual void writeBreak (int indent) const =0
virtual void writeLink (const QCString &extRef, const QCString &file, const QCString &anchor, const QCString &text) const =0
Private Attributes
BaseOutputDocInterface & m_od
Detailed Description
Implements TextGeneratorIntf for an OutputDocInterface stream.
Definition at line 72 of file util.h.
Constructor & Destructor Documentation
TextGeneratorOLImpl()
TextGeneratorOLImpl::TextGeneratorOLImpl (BaseOutputDocInterface & od)
Definition at line 101 of file util.cpp.
                                                                   : m_od(od)
{
}
Member Function Documentation
writeBreak()
void TextGeneratorOLImpl::writeBreak (int indent) const virtual
Implements TextGeneratorIntf.
Definition at line 130 of file util.cpp.
{
  m_od.lineBreak("typebreak");
  int i;
  for (i=0;i<indent;i++)
  {
    m_od.writeNonBreakableSpace(3);
  }
}
References BaseOutputDocInterface::lineBreak(), m_od, and BaseOutputDocInterface::writeNonBreakableSpace().
writeLink()
void TextGeneratorOLImpl::writeLink (const QCString & extRef, const QCString & file, const QCString & anchor, const QCString & text) const virtual
Implements TextGeneratorIntf.
Definition at line 140 of file util.cpp.
{
  //printf("TextGeneratorOlImpl::writeLink('%s')\n",text);
  m_od.writeObjectLink(extRef,file,anchor,text);
}
References m_od, and BaseOutputDocInterface::writeObjectLink().
writeString()
void TextGeneratorOLImpl::writeString (const QCString & s, bool keepSpaces) const virtual
Implements TextGeneratorIntf.
Definition at line 105 of file util.cpp.
{
  if (s.isEmpty()) return;
  //printf("TextGeneratorOlImpl::writeString('%s',%d)\n",s,keepSpaces);
  if (keepSpaces)
  {
    const char *p=s.data();
    if (p)
    {
      char cs[2];
      char c;
      cs[1]='\0';
      while ((c=*p++))
      {
        if (c==' ') m_od.writeNonBreakableSpace(1);
        else cs[0]=c,m_od.docify(cs);
      }
    }
  }
  else
  {
    m_od.docify(s);
  }
}
References QCString::data(), BaseOutputDocInterface::docify(), QCString::isEmpty(), m_od, and BaseOutputDocInterface::writeNonBreakableSpace().
Member Data Documentation
m_od
BaseOutputDocInterface& TextGeneratorOLImpl::m_od private
Definition at line 82 of file util.h.
Referenced by writeBreak(), writeLink(), and writeString().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/util.h
/home/runner/work/doxygen/doxygen/src/util.cpp