Doxygen: /home/runner/work/doxygen/doxygen/src/diagram.cpp File Reference
diagram.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <algorithm>
#include "diagram.h"
#include "image.h"
#include "classdef.h"
#include "config.h"
#include "message.h"
#include "util.h"
#include "doxygen.h"
#include "portable.h"
#include "indexlist.h"
#include "classlist.h"
#include "textstream.h"
#include "growbuf.h"
Classes
class DiagramItem
Class representing a single node in the built-in class diagram.
class DiagramRow
Class representing a row in the built-in class diagram.
class TreeDiagram
Class representing the tree layout for the built-in class diagram.
class DualDirIterator< C, I >
helper class representing an iterator that can iterate forwards or backwards
struct ClassDiagram::Private
Macros
#define IMAGE_EXT ".png"
Typedefs
using DiagramItemList = std::vector< DiagramItem * >
Functions
static uint protToMask (Protection p)
static uchar protToColor (Protection p)
static QCString protToString (Protection p)
static uint virtToMask (Specifier p)
static QCString convertToPSString (const QCString &s)
static Protection getMinProtectionLevel (const DiagramItemList &dil)
static void writeBitmapBox (DiagramItem *di, Image *image, uint x, uint y, uint w, uint h, bool firstRow, bool hasDocs, bool children=FALSE)
static void writeVectorBox (TextStream &t, DiagramItem *di, float x, float y, bool children=FALSE)
static void writeMapArea (TextStream &t, const ClassDef *cd, QCString relPath, uint x, uint y, uint w, uint h)
Variables
const uint maxTreeWidth = 8
const uint gridWidth = 100
const uint gridHeight = 100
const uint labelHorSpacing = 10
const uint labelVertSpacing = 32
const uint labelHorMargin = 6
const uint fontHeight = 12
Macro Definition Documentation
IMAGE_EXT
#define IMAGE_EXT ".png"
Typedef Documentation
DiagramItemList
using DiagramItemList = std::vector<DiagramItem*>
Definition at line 37 of file diagram.cpp.
Function Documentation
convertToPSString()
static QCString convertToPSString (const QCString & s) static
Definition at line 196 of file diagram.cpp.
{
  if (s.isEmpty()) return s;
  GrowBuf growBuf;
  const char *p=s.data();
  char c;
  while ((c=*p++))
  {
    switch (c)
    {
      case '(':  growBuf.addStr("\\("); break;
      case ')': growBuf.addStr("\\)"); break;
      default:   growBuf.addChar(c);   break;
    }
  }
  growBuf.addChar(0);
  return growBuf.get();
}
References GrowBuf::addChar(), GrowBuf::addStr(), QCString::data(), GrowBuf::get(), and QCString::isEmpty().
Referenced by ClassDiagram::writeFigure(), and writeVectorBox().
getMinProtectionLevel()
static Protection getMinProtectionLevel (const DiagramItemList & dil) static
Definition at line 216 of file diagram.cpp.
{
  auto it = dil.begin();
  Protection result = Protection::Private;
  if (it!=dil.end())
  {
    result=(*it)->protection();
    for (++it;it!=dil.end();++it)
    {
      Protection p=(*it)->protection();
      if (p!=result)
      {
        if (result==Protection::Protected && p==Protection::Public) result=p;
        else if (result==Protection::Private) result=p;
      }
    }
  }
  return result;
}
References Private, Protected, and Public.
Referenced by TreeDiagram::drawConnectors().
protToColor()
static uchar protToColor (Protection p) static
Definition at line 161 of file diagram.cpp.
{
  switch(p)
  {
    case Protection::Public:    return 6;
    case Protection::Package: // package is not possible!
    case Protection::Protected: return 5;
    case Protection::Private:   return 4;
  }
  return 0;
}
References Package, Private, Protected, and Public.
Referenced by TreeDiagram::drawConnectors().
protToMask()
static uint protToMask (Protection p) static
Definition at line 149 of file diagram.cpp.
{
  switch(p)
  {
    case Protection::Public:    return 0xffffffff;
    case Protection::Package: // package is not possible!
    case Protection::Protected: return 0xcccccccc;
    case Protection::Private:   return 0xaaaaaaaa;
  }
  return 0;
}
References Package, Private, Protected, and Public.
Referenced by TreeDiagram::drawConnectors().
protToString()
static QCString protToString (Protection p) static
Definition at line 173 of file diagram.cpp.
{
  switch(p)
  {
    case Protection::Public:    return "solid";
    case Protection::Package: // package is not possible!
    case Protection::Protected: return "dashed";
    case Protection::Private:   return "dotted";
  }
  return QCString();
}
References Package, Private, Protected, and Public.
Referenced by TreeDiagram::drawConnectors().
virtToMask()
static uint virtToMask (Specifier p) static
Definition at line 185 of file diagram.cpp.
{
  switch(p)
  {
    case Specifier::Normal:    return 0xffffffff;
    case Specifier::Virtual:   return 0xf0f0f0f0;
    default:        break;
  }
  return 0;
}
References Normal, and Virtual.
Referenced by writeBitmapBox().
writeBitmapBox()
static void writeBitmapBox (DiagramItem * di, Image * image, uint x, uint y, uint w, uint h, bool firstRow, bool hasDocs, bool children = FALSE) static
Definition at line 236 of file diagram.cpp.
{
  uchar colFill = hasDocs ? (firstRow ? 8 : 2) : 7;
  uchar colBorder = (firstRow || !hasDocs) ? 1 : 3;
  uint l = Image::stringLength(di->label());
  uint mask=virtToMask(di->virtualness());
  image->fillRect(x+1,y+1,w-2,h-2,colFill,mask);
  image->drawRect(x,y,w,h,colBorder,mask);
  image->writeString(x+(w-l)/2, y+(h-fontHeight)/2, di->label(),1);
  if (children)
  {
    uint i;
    for (i=0;i<5;i++)
    {
      image->drawHorzLine(y+h+i-6,x+w-2-i,x+w-2,firstRow?1:3,0xffffffff);
    }
  }
}
References Image::drawHorzLine(), Image::drawRect(), Image::fillRect(), fontHeight, DiagramItem::label(), Image::stringLength, virtToMask(), DiagramItem::virtualness(), and Image::writeString().
Referenced by TreeDiagram::drawBoxes().
writeMapArea()
static void writeMapArea (TextStream & t, const ClassDef * cd, QCString relPath, uint x, uint y, uint w, uint h) static
Definition at line 266 of file diagram.cpp.
{
  if (cd->isLinkable())
  {
    QCString ref=cd->getReference();
    t << "<area ";
    if (!ref.isEmpty())
    {
      t << externalLinkTarget(true);
    }
    t << "href=\"";
    t << externalRef(relPath,ref,TRUE);
    t << addHtmlExtensionIfMissing(cd->getOutputFileBase());
    if (!cd->anchor().isEmpty())
    {
      t << "#" << cd->anchor();
    }
    t << "\" ";
    QCString tooltip = cd->briefDescriptionAsTooltip();
    if (!tooltip.isEmpty())
    {
      t << "title=\"" << convertToHtml(tooltip) << "\" ";
    }
    t << "alt=\"" << convertToXML(cd->displayName());
    t << "\" shape=\"rect\" coords=\"" << x << "," << y << ",";
    t << (x+w) << "," << (y+h) << "\"/>\n";
  }
}
References addHtmlExtensionIfMissing(), ClassDef::anchor(), Definition::briefDescriptionAsTooltip(), convertToHtml(), convertToXML(), ClassDef::displayName(), externalLinkTarget(), externalRef(), ClassDef::getOutputFileBase(), ClassDef::getReference(), QCString::isEmpty(), ClassDef::isLinkable(), and TRUE.
Referenced by TreeDiagram::drawBoxes().
writeVectorBox()
static void writeVectorBox (TextStream & t, DiagramItem * di, float x, float y, bool children = FALSE) static
Definition at line 257 of file diagram.cpp.
{
  if (di->virtualness()==Specifier::Virtual) t << "dashed\n";
  t << " (" << convertToPSString(di->label()) << ") " << x << " " << y << " box\n";
  if (children) t << x << " " << y << " mark\n";
  if (di->virtualness()==Specifier::Virtual) t << "solid\n";
}
References convertToPSString(), DiagramItem::label(), Virtual, and DiagramItem::virtualness().
Referenced by TreeDiagram::drawBoxes().
Variable Documentation
fontHeight
const uint fontHeight = 12
Definition at line 147 of file diagram.cpp.
Referenced by writeBitmapBox(), and ClassDiagram::writeImage().
gridHeight
const uint gridHeight = 100
Definition at line 142 of file diagram.cpp.
Referenced by TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), and DiagramRow::insertClass().
gridWidth
const uint gridWidth = 100
Definition at line 141 of file diagram.cpp.
Referenced by TreeDiagram::computeLayout(), TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), DiagramRow::insertClass(), ClassDiagram::writeFigure(), and ClassDiagram::writeImage().
labelHorMargin
const uint labelHorMargin = 6
Definition at line 146 of file diagram.cpp.
Referenced by ClassDiagram::writeImage().
labelHorSpacing
const uint labelHorSpacing = 10
Definition at line 144 of file diagram.cpp.
Referenced by TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), and ClassDiagram::writeImage().
labelVertSpacing
const uint labelVertSpacing = 32
Definition at line 145 of file diagram.cpp.
Referenced by TreeDiagram::drawBoxes(), TreeDiagram::drawConnectors(), and ClassDiagram::writeImage().
maxTreeWidth
const uint maxTreeWidth = 8
Definition at line 140 of file diagram.cpp.
Referenced by TreeDiagram::computeLayout().