Doxygen: HtmlCodeGenerator Class Reference
HtmlCodeGenerator Class Reference
Generator for HTML code fragments.
#include <htmlgen.h>
Public Member Functions
HtmlCodeGenerator (TextStream &t, const QCString &relPath)
HtmlCodeGenerator (TextStream &t)
OutputType type () const override
void codify (const QCString &text) override
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip) override
void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo) override
void writeLineNumber (const QCString &, const QCString &, const QCString &, int, bool) override
void startCodeLine (bool) override
void endCodeLine () override
void startFontClass (const QCString &s) override
void endFontClass () override
void writeCodeAnchor (const QCString &anchor) override
void startCodeFragment (const QCString &style) override
void endCodeFragment (const QCString &) override
void setRelativePath (const QCString &path)
Public Member Functions inherited from CodeOutputInterface
CodeOutputInterface ()=default
CodeOutputInterface (const CodeOutputInterface &)=delete
CodeOutputInterface & operator= (const CodeOutputInterface &)=delete
virtual ~CodeOutputInterface ()=default
virtual OutputType type () const =0
virtual int id () const
Identifier for the output file.
virtual void setId (int id)
virtual void setEnabled (bool e)
virtual bool isEnabled () const
virtual void codify (const QCString &s)=0
virtual void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)=0
virtual void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)=0
virtual void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)=0
virtual void startCodeLine (bool hasLineNumbers)=0
virtual void endCodeLine ()=0
virtual void startFontClass (const QCString &clsName)=0
virtual void endFontClass ()=0
virtual void writeCodeAnchor (const QCString &name)=0
virtual void setCurrentDoc (const Definition *context, const QCString &anchor, bool isSourceFile)
virtual void addWord (const QCString &word, bool hiPriority)
virtual void startCodeFragment (const QCString &style)=0
virtual void endCodeFragment (const QCString &style)=0
Private Member Functions
void _writeCodeLink (const QCString &className, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void docify (const QCString &str)
Private Attributes
TextStream & m_t
int m_col = 0
QCString m_relPath
bool m_lineOpen = false
Detailed Description
Generator for HTML code fragments.
Definition at line 22 of file htmlgen.h.
Constructor & Destructor Documentation
HtmlCodeGenerator() [1/2]
HtmlCodeGenerator::HtmlCodeGenerator (TextStream & t, const QCString & relPath)
Definition at line 696 of file htmlgen.cpp.
  : m_t(t), m_relPath(relPath)
{
}
HtmlCodeGenerator() [2/2]
HtmlCodeGenerator::HtmlCodeGenerator (TextStream & t)
Definition at line 692 of file htmlgen.cpp.
                                                  : m_t(t)
{
}
Member Function Documentation
_writeCodeLink()
void HtmlCodeGenerator::_writeCodeLink (const QCString & className, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) private
Definition at line 860 of file htmlgen.cpp.
{
  if (!ref.isEmpty())
  {
    m_t << "<a class=\"" << className << "Ref\" ";
    m_t << externalLinkTarget();
  }
  else
  {
    m_t << "<a class=\"" << className << "\" ";
  }
  m_t << "href=\"";
  m_t << externalRef(m_relPath,ref,TRUE);
  if (!f.isEmpty()) m_t << addHtmlExtensionIfMissing(f);
  if (!anchor.isEmpty()) m_t << "#" << anchor;
  m_t << "\"";
  if (!tooltip.isEmpty()) m_t << " title=\"" << convertToHtml(tooltip) << "\"";
  m_t << ">";
  docify(name);
  m_t << "</a>";
  m_col+=name.length();
}
References addHtmlExtensionIfMissing(), convertToHtml(), docify(), externalLinkTarget(), externalRef(), QCString::isEmpty(), QCString::length(), m_col, m_relPath, m_t, and TRUE.
Referenced by writeCodeLink(), and writeLineNumber().
codify()
void HtmlCodeGenerator::codify (const QCString & s) override virtual
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 706 of file htmlgen.cpp.
{
  int tabSize = Config_getInt(TAB_SIZE);
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    int spacesToNextTabStop;
    while (*p)
    {
      c=*p++;
      switch(c)
      {
        case '\t': spacesToNextTabStop =
                         tabSize - (m_col%tabSize);
                   m_t << Doxygen::spaces.left(spacesToNextTabStop);
                   m_col+=spacesToNextTabStop;
                   break;
        case '\n': m_t << "\n"; m_col=0;
                   break;
        case '\r': break;
        case '<':  m_t << "&lt;"; m_col++;
                   break;
        case '>':  m_t << "&gt;"; m_col++;
                   break;
        case '&':  m_t << "&amp;"; m_col++;
                   break;
        case '\'': m_t << "&#39;"; m_col++; // &apos; is not valid XHTML
                   break;
        case '"':  m_t << "&quot;"; m_col++;
                   break;
        case '\\':
                   if (*p=='<')
                     { m_t << "&lt;"; p++; }
                   else if (*p=='>')
                     { m_t << "&gt;"; p++; }
                   else if (*p=='(')
                     { m_t << "\\&zwj;("; m_col++;p++; }
                   else if (*p==')')
                     { m_t << "\\&zwj;)"; m_col++;p++; }
                   else
                     m_t << "\\";
                   m_col++;
                   break;
        default:
          {
            uchar uc = static_cast<uchar>(c);
            if (uc<32)
            {
              m_t << "&#x24" << hex[uc>>4] << hex[uc&0xF] << ";";
              m_col++;
            }
            else
            {
              p=writeUTF8Char(m_t,p-1);
              m_col++;
            }
          }
          break;
      }
    }
  }
}
References Config_getInt, QCString::data(), hex, QCString::isEmpty(), QCString::left(), m_col, m_t, Doxygen::spaces, and writeUTF8Char().
Referenced by writeLineNumber().
docify()
void HtmlCodeGenerator::docify (const QCString & str) private
Definition at line 770 of file htmlgen.cpp.
{
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    while (*p)
    {
      c=*p++;
      switch(c)
      {
        case '<':  m_t << "&lt;"; break;
        case '>':  m_t << "&gt;"; break;
        case '&':  m_t << "&amp;"; break;
        case '"':  m_t << "&quot;"; break;
        case '\\':
          if (*p=='<')
            { m_t << "&lt;"; p++; }
          else if (*p=='>')
            { m_t << "&gt;"; p++; }
          else if (*p=='(')
            { m_t << "\\&zwj;("; p++; }
          else if (*p==')')
            { m_t << "\\&zwj;)"; p++; }
          else
            m_t << "\\";
          break;
        default:
          {
            uchar uc = static_cast<uchar>(c);
            if (uc<32 && !isspace(c))
            {
              m_t << "&#x24" << hex[uc>>4] << hex[uc&0xF] << ";";
            }
            else
            {
              m_t << c;
            }
          }
          break;
      }
    }
  }
}
References QCString::data(), hex, QCString::isEmpty(), and m_t.
Referenced by _writeCodeLink(), and writeTooltip().
endCodeFragment()
void HtmlCodeGenerator::endCodeFragment (const QCString & style) override virtual
Ends a block of code
Implements CodeOutputInterface.
Definition at line 1012 of file htmlgen.cpp.
{
  //endCodeLine checks is there is still an open code line, if so closes it.
  endCodeLine();
  m_t << "</div><!-- fragment -->";
}
References endCodeLine(), and m_t.
endCodeLine()
void HtmlCodeGenerator::endCodeLine () override virtual
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 978 of file htmlgen.cpp.
{
  if (m_col == 0)
  {
    m_t << " ";
    m_col++;
  }
  if (m_lineOpen)
  {
    m_t << "</div>\n";
    m_lineOpen = FALSE;
  }
}
References FALSE, m_col, m_lineOpen, and m_t.
Referenced by endCodeFragment().
endFontClass()
void HtmlCodeGenerator::endFontClass () override virtual
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 997 of file htmlgen.cpp.
{
  m_t << "</span>";
}
References m_t.
setRelativePath()
void HtmlCodeGenerator::setRelativePath (const QCString & path)
Definition at line 701 of file htmlgen.cpp.
{
  m_relPath = path;
}
References m_relPath.
Referenced by HtmlGenerator::startFile().
startCodeFragment()
void HtmlCodeGenerator::startCodeFragment (const QCString & style) override virtual
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 1007 of file htmlgen.cpp.
{
  m_t << "<div class=\"fragment\">";
}
References m_t.
startCodeLine()
void HtmlCodeGenerator::startCodeLine (bool) override virtual
Implements CodeOutputInterface.
Definition at line 968 of file htmlgen.cpp.
{
  m_col=0;
  if (!m_lineOpen)
  {
    m_t << "<div class=\"line\">";
    m_lineOpen = TRUE;
  }
}
References m_col, m_lineOpen, m_t, and TRUE.
startFontClass()
void HtmlCodeGenerator::startFontClass (const QCString & clsName) override virtual
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 992 of file htmlgen.cpp.
{
  m_t << "<span class=\"" << s << "\">";
}
References m_t.
type()
OutputType HtmlCodeGenerator::type () const inline override virtual
Implements CodeOutputInterface.
Definition at line 28 of file htmlgen.h.
{ return OutputType::Html; }
Referenced by writeCodeLink().
writeCodeAnchor()
void HtmlCodeGenerator::writeCodeAnchor (const QCString & name) override virtual
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 1002 of file htmlgen.cpp.
{
  m_t << "<a id=\"" << anchor << "\" name=\"" << anchor << "\"></a>";
}
References m_t.
writeCodeLink()
void HtmlCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) override virtual
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 845 of file htmlgen.cpp.
{
  const char *hl = codeSymbolType2Str(type);
  QCString hlClass = "code";
  if (hl)
  {
    hlClass+=" hl_";
    hlClass+=hl;
  }
  _writeCodeLink(hlClass,ref,f,anchor,name,tooltip);
}
References _writeCodeLink(), codeSymbolType2Str(), and type().
writeLineNumber()
void HtmlCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) override virtual
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 816 of file htmlgen.cpp.
{
  const int maxLineNrStr = 10;
  char lineNumber[maxLineNrStr];
  char lineAnchor[maxLineNrStr];
  qsnprintf(lineNumber,maxLineNrStr,"%5d",l);
  qsnprintf(lineAnchor,maxLineNrStr,"l%05d",l);
  if (!m_lineOpen)
  {
    m_t << "<div class=\"line\">";
    m_lineOpen = TRUE;
  }
  if (writeLineAnchor) m_t << "<a id=\"" << lineAnchor << "\" name=\"" << lineAnchor << "\"></a>";
  m_t << "<span class=\"lineno\">";
  if (!filename.isEmpty())
  {
    _writeCodeLink("line",ref,filename,anchor,lineNumber,QCString());
  }
  else
  {
    codify(lineNumber);
  }
  m_t << "</span>";
  m_col=0;
}
References _writeCodeLink(), codify(), QCString::isEmpty(), m_col, m_lineOpen, m_t, qsnprintf, and TRUE.
writeTooltip()
void HtmlCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) override virtual
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 886 of file htmlgen.cpp.
{
  m_t << "<div class=\"ttc\" id=\"" << id << "\">";
  m_t << "<div class=\"ttname\">";
  if (!docInfo.url.isEmpty())
  {
    m_t << "<a href=\"";
    m_t << externalRef(m_relPath,docInfo.ref,TRUE);
    m_t << addHtmlExtensionIfMissing(docInfo.url);
    if (!docInfo.anchor.isEmpty())
    {
      m_t << "#" << docInfo.anchor;
    }
    m_t << "\">";
  }
  docify(docInfo.name);
  if (!docInfo.url.isEmpty())
  {
    m_t << "</a>";
  }
  m_t << "</div>";
  if (!decl.isEmpty())
  {
    m_t << "<div class=\"ttdeci\">";
    docify(decl);
    m_t << "</div>";
  }
  if (!desc.isEmpty())
  {
    m_t << "<div class=\"ttdoc\">";
    docify(desc);
    m_t << "</div>";
  }
  if (!defInfo.file.isEmpty())
  {
    m_t << "<div class=\"ttdef\"><b>Definition:</b> ";
    if (!defInfo.url.isEmpty())
    {
      m_t << "<a href=\"";
      m_t << externalRef(m_relPath,defInfo.ref,TRUE);
      m_t << addHtmlExtensionIfMissing(defInfo.url);
      if (!defInfo.anchor.isEmpty())
      {
        m_t << "#" << defInfo.anchor;
      }
      m_t << "\">";
    }
    m_t << defInfo.file << ":" << defInfo.line;
    if (!defInfo.url.isEmpty())
    {
      m_t << "</a>";
    }
    m_t << "</div>";
  }
  if (!declInfo.file.isEmpty())
  {
    m_t << "<div class=\"ttdecl\"><b>Declaration:</b> ";
    if (!declInfo.url.isEmpty())
    {
      m_t << "<a href=\"";
      m_t << externalRef(m_relPath,declInfo.ref,TRUE);
      m_t << addHtmlExtensionIfMissing(declInfo.url);
      if (!declInfo.anchor.isEmpty())
      {
        m_t << "#" << declInfo.anchor;
      }
      m_t << "\">";
    }
    m_t << declInfo.file << ":" << declInfo.line;
    if (!declInfo.url.isEmpty())
    {
      m_t << "</a>";
    }
    m_t << "</div>";
  }
  m_t << "</div>\n";
}
References addHtmlExtensionIfMissing(), DocLinkInfo::anchor, SourceLinkInfo::anchor, docify(), externalRef(), SourceLinkInfo::file, QCString::isEmpty(), SourceLinkInfo::line, m_relPath, m_t, DocLinkInfo::name, DocLinkInfo::ref, SourceLinkInfo::ref, TRUE, DocLinkInfo::url, and SourceLinkInfo::url.
Member Data Documentation
m_col
int HtmlCodeGenerator::m_col = 0 private
Definition at line 59 of file htmlgen.h.
Referenced by _writeCodeLink(), codify(), endCodeLine(), startCodeLine(), and writeLineNumber().
m_lineOpen
bool HtmlCodeGenerator::m_lineOpen = false private
Definition at line 61 of file htmlgen.h.
Referenced by endCodeLine(), startCodeLine(), and writeLineNumber().
m_relPath
QCString HtmlCodeGenerator::m_relPath private
Definition at line 60 of file htmlgen.h.
Referenced by _writeCodeLink(), setRelativePath(), and writeTooltip().
m_t
TextStream& HtmlCodeGenerator::m_t private
Definition at line 58 of file htmlgen.h.
Referenced by _writeCodeLink(), codify(), docify(), endCodeFragment(), endCodeLine(), endFontClass(), startCodeFragment(), startCodeLine(), startFontClass(), writeCodeAnchor(), writeLineNumber(), and writeTooltip().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/htmlgen.h
/home/runner/work/doxygen/doxygen/src/htmlgen.cpp