Doxygen: /home/runner/work/doxygen/doxygen/src/conceptdef.h File Reference
conceptdef.h File Reference
#include "definition.h"
#include "filedef.h"
Classes
class ConceptDef
class ConceptDefMutable
class ConceptLinkedMap
class ConceptLinkedRefMap
Functions
ConceptDefMutable * createConceptDef (const QCString &fileName, int startLine, int startColumn, const QCString &name, const QCString &tagRef=QCString(), const QCString &tagFile=QCString())
ConceptDef * createConceptDefAlias (const Definition *newScope, const ConceptDef *cd)
ConceptDef * toConceptDef (Definition *d)
ConceptDef * toConceptDef (DefinitionMutable *d)
const ConceptDef * toConceptDef (const Definition *d)
ConceptDefMutable * toConceptDefMutable (Definition *d)
ConceptDefMutable * toConceptDefMutable (const Definition *d)
ConceptDef * getConcept (const QCString &key)
ConceptDefMutable * getConceptMutable (const QCString &key)
ConceptDef * getResolvedConcept (const Definition *scope, const QCString &name)
Function Documentation
createConceptDef()
ConceptDefMutable * createConceptDef (const QCString & fileName, int startLine, int startColumn, const QCString & name, const QCString & tagRef = QCString(), const QCString & tagFile = QCString())
Definition at line 87 of file conceptdef.cpp.
{
  return new ConceptDefImpl(fileName,startLine,startColumn,name,tagRef,tagFile);
}
Referenced by addConceptToContext().
createConceptDefAlias()
ConceptDef * createConceptDefAlias (const Definition * newScope, const ConceptDef * cd)
Definition at line 144 of file conceptdef.cpp.
{
  ConceptDef *acd = new ConceptDefAliasImpl(newScope,cd);
  return acd;
}
getConcept()
ConceptDef * getConcept (const QCString & key)
Definition at line 753 of file conceptdef.cpp.
{
  if (n.isEmpty()) return 0;
  return Doxygen::conceptLinkedMap->find(n);
}
References Doxygen::conceptLinkedMap, LinkedMap< T, Hash, KeyEqual, Map >::find(), and QCString::isEmpty().
Referenced by getConceptMutable(), getResolvedConcept(), if(), and resolveLink().
getConceptMutable()
ConceptDefMutable * getConceptMutable (const QCString & key) inline
Definition at line 88 of file conceptdef.h.
{
  return toConceptDefMutable(getConcept(key));
}
References getConcept(), and toConceptDefMutable().
Referenced by addConceptToContext().
getResolvedConcept()
ConceptDef * getResolvedConcept (const Definition * scope, const QCString & name)
Definition at line 759 of file conceptdef.cpp.
{
  ConceptDef *cd=0;
  while (d && d!=Doxygen::globalScope)
  {
    cd = getConcept(d->name()+"::"+name);
    if (cd) return cd;
    d = d->getOuterScope();
  }
  cd = getConcept(name);
  return cd;
}
References getConcept(), Definition::getOuterScope(), Doxygen::globalScope, and Definition::name().
Referenced by generateClassOrGlobalLink().
toConceptDef() [1/3]
const ConceptDef * toConceptDef (const Definition * d)
Definition at line 715 of file conceptdef.cpp.
{
  if (d && (typeid(*d)==typeid(ConceptDefImpl) || typeid(*d)==typeid(ConceptDefAliasImpl)))
  {
    return static_cast<const ConceptDef*>(d);
  }
  else
  {
    return 0;
  }
}
toConceptDef() [2/3]
ConceptDef * toConceptDef (Definition * d)
Definition at line 690 of file conceptdef.cpp.
{
  if (d && (typeid(*d)==typeid(ConceptDefImpl) || typeid(*d)==typeid(ConceptDefAliasImpl)))
  {
    return static_cast<ConceptDef*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by NamespaceDefImpl::addInnerCompound(), and ConceptDefAliasImpl::getCdAlias().
toConceptDef() [3/3]
ConceptDef * toConceptDef (DefinitionMutable * d)
Definition at line 702 of file conceptdef.cpp.
{
  Definition *d = toDefinition(md);
  if (d && typeid(*d)==typeid(ConceptDefImpl))
  {
    return static_cast<ConceptDef*>(d);
  }
  else
  {
    return 0;
  }
}
References toDefinition().
toConceptDefMutable() [1/2]
ConceptDefMutable * toConceptDefMutable (const Definition * d)
Definition at line 739 of file conceptdef.cpp.
{
  if (d && typeid(*d)==typeid(ConceptDefImpl))
  {
    return const_cast<ConceptDefMutable*>(static_cast<const ConceptDefMutable*>(d));
  }
  else
  {
    return 0;
  }
}
toConceptDefMutable() [2/2]
ConceptDefMutable * toConceptDefMutable (Definition * d)
Definition at line 727 of file conceptdef.cpp.
{
  if (d && typeid(*d)==typeid(ConceptDefImpl))
  {
    return static_cast<ConceptDefMutable*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by addConceptToContext(), addConceptToGroups(), distributeConceptGroups(), findSectionsInDocumentation(), generateConceptDocs(), generateNamespaceConceptDocs(), getConceptMutable(), and writeTagFile().