Doxygen: NamespaceDefImpl Class Reference
NamespaceDefImpl Class Reference
Public Member Functions
NamespaceDefImpl (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const QCString &ref=QCString(), const QCString &refFile=QCString(), const QCString &type=QCString(), bool isPublished=false)
virtual ~NamespaceDefImpl ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual QCString anchor () const
virtual void insertUsedFile (FileDef *fd)
virtual void writeDocumentation (OutputList &ol)
virtual void writeMemberPages (OutputList &ol)
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const
virtual void writeTagFile (TextStream &)
virtual void insertClass (ClassDef *cd)
virtual void insertConcept (ConceptDef *cd)
virtual void insertNamespace (NamespaceDef *nd)
virtual void insertMember (MemberDef *md)
virtual void computeAnchors ()
virtual void countMembers ()
virtual int numDocMembers () const
virtual void addUsingDirective (NamespaceDef *nd)
virtual const LinkedRefMap< NamespaceDef > & getUsedNamespaces () const
virtual void addUsingDeclaration (ClassDef *cd)
virtual const LinkedRefMap< ClassDef > & getUsedClasses () const
virtual void combineUsingRelations (NamespaceDefSet &visitedNamespace)
virtual QCString displayName (bool=TRUE) const
virtual QCString localName () const
virtual void setInline (bool isInline)
virtual bool isConstantGroup () const
virtual bool isModule () const
virtual bool isLibrary () const
virtual bool isInline () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual bool hasDetailedDescription () const
virtual void addMembersToMemberGroup ()
virtual void distributeMemberGroupDocumentation ()
virtual void findSectionsInDocumentation ()
virtual void sortMemberLists ()
virtual const Definition * findInnerCompound (const QCString &name) const
virtual void addInnerCompound (Definition *d)
virtual void addListReferences ()
virtual void setFileName (const QCString &fn)
virtual bool subGrouping () const
virtual MemberList * getMemberList (MemberListType lt) const
virtual const MemberLists & getMemberLists () const
virtual const MemberDef * getMemberByName (const QCString &) const
virtual const MemberGroupList & getMemberGroups () const
virtual ClassLinkedRefMap getClasses () const
virtual ClassLinkedRefMap getInterfaces () const
virtual ClassLinkedRefMap getStructs () const
virtual ClassLinkedRefMap getExceptions () const
virtual NamespaceLinkedRefMap getNamespaces () const
virtual ConceptLinkedRefMap getConcepts () const
virtual QCString title () const
virtual QCString compoundTypeString () const
virtual void setMetaData (const QCString &m)
virtual int countVisibleMembers () const
Public Member Functions inherited from DefinitionMixin< NamespaceDefMutable >
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~DefinitionMixin ()=default
virtual bool isAlias () const
virtual QCString name () const
virtual bool isAnonymous () const
virtual QCString localName () const
virtual QCString qualifiedName () const
virtual QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
virtual int docLine () const
virtual QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
virtual QCString briefDescriptionAsTooltip () const
virtual int briefLine () const
virtual QCString inbodyDocumentation () const
virtual QCString inbodyFile () const
virtual int inbodyLine () const
virtual QCString briefFile () const
virtual QCString getDefFileName () const
virtual QCString getDefFileExtension () const
virtual int getDefLine () const
virtual int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
virtual bool isHidden () const
virtual bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
virtual QCString externalReference (const QCString &relPath) const
virtual int getStartDefLine () const
virtual int getStartBodyLine () const
virtual int getEndBodyLine () const
virtual const FileDef * getBodyDef () const
virtual SrcLangExt getLanguage () const
virtual const GroupList & partOfGroups () const
virtual bool isLinkableViaGroup () const
virtual const RefItemVector & xrefListItems () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual Definition * getOuterScope () const
virtual const MemberVector & getReferencesMembers () const
virtual const MemberVector & getReferencedByMembers () const
virtual bool hasSections () const
virtual bool hasSources () const
virtual bool hasBriefDescription () const
virtual QCString id () const
virtual const SectionRefs & getSectionRefs () const
virtual void setName (const QCString &name)
virtual void setId (const QCString &name)
virtual void setDefFile (const QCString &df, int defLine, int defColumn)
virtual void setDocumentation (const QCString &doc, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const QCString &brief, const QCString &briefFile, int briefLine)
virtual void setInbodyDocumentation (const QCString &doc, const QCString &docFile, int docLine)
virtual void setReference (const QCString &r)
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)
virtual void setBodySegment (int defLine, int bls, int ble)
virtual void setBodyDef (const FileDef *fd)
virtual void addSourceReferencedBy (MemberDef *md)
virtual void addSourceReferences (MemberDef *md)
virtual void setRefItems (const RefItemVector &sli)
virtual void mergeRefItems (Definition *def)
virtual void mergeReferences (const Definition *other)
virtual void mergeReferencedBy (const Definition *other)
virtual void addInnerCompound (Definition *def)
virtual void setOuterScope (Definition *def)
virtual void setHidden (bool b)
virtual void setArtificial (bool b)
virtual void setLanguage (SrcLangExt lang)
virtual void writeSourceDef (OutputList &ol, const QCString &scopeName) const
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const
virtual bool hasSourceRefs () const
virtual bool hasSourceReffedBy () const
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const
virtual void makePartOfGroup (GroupDef *gd)
virtual void writeNavigationPath (OutputList &ol) const
virtual QCString navigationPathAsString () const
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const
virtual void writeSummaryLinks (OutputList &ol) const
virtual QCString pathFragment () const
virtual void writeDocAnchorsToTagFile (TextStream &fs) const
virtual void setLocalName (const QCString &name)
virtual void addSectionsToIndex ()
virtual void writeToc (OutputList &ol, const LocalToc &lt) const
virtual void computeTooltip ()
virtual void _setSymbolName (const QCString &name)
virtual QCString _symbolName () const
virtual void setMetaData (const QCString &m)=0
virtual void insertUsedFile (FileDef *fd)=0
virtual void writeDocumentation (OutputList &ol)=0
virtual void writeMemberPages (OutputList &ol)=0
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *currentMd) const =0
virtual void writeTagFile (TextStream &)=0
virtual void insertClass (ClassDef *cd)=0
virtual void insertConcept (ConceptDef *cd)=0
virtual void insertNamespace (NamespaceDef *nd)=0
virtual void insertMember (MemberDef *md)=0
virtual void computeAnchors ()=0
virtual void countMembers ()=0
virtual void addMembersToMemberGroup ()=0
virtual void distributeMemberGroupDocumentation ()=0
virtual void findSectionsInDocumentation ()=0
virtual void sortMemberLists ()=0
virtual void addInnerCompound (Definition *d)=0
virtual void addListReferences ()=0
virtual void setFileName (const QCString &fn)=0
virtual void combineUsingRelations (NamespaceDefSet &visitedNamespace)=0
virtual void addUsingDirective (NamespaceDef *nd)=0
virtual void addUsingDeclaration (ClassDef *cd)=0
virtual void setInline (bool isInline)=0
Public Member Functions inherited from DefinitionMutable
virtual void setName (const QCString &name)=0
virtual void setId (const QCString &name)=0
virtual void setDefFile (const QCString &df, int defLine, int defColumn)=0
virtual void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)=0
virtual void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)=0
virtual void setInbodyDocumentation (const QCString &d, const QCString &docFile, int docLine)=0
virtual void setReference (const QCString &r)=0
virtual void setBodySegment (int defLine, int bls, int ble)=0
virtual void setBodyDef (const FileDef *fd)=0
virtual void setRefItems (const RefItemVector &sli)=0
virtual void setOuterScope (Definition *d)=0
virtual void setHidden (bool b)=0
virtual void setArtificial (bool b)=0
virtual void setLanguage (SrcLangExt lang)=0
virtual void setLocalName (const QCString &name)=0
virtual void makePartOfGroup (GroupDef *gd)=0
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)=0
virtual void addSourceReferencedBy (MemberDef *d)=0
virtual void addSourceReferences (MemberDef *d)=0
virtual void mergeRefItems (Definition *d)=0
virtual void addInnerCompound (Definition *d)=0
virtual void addSectionsToIndex ()=0
virtual void mergeReferences (const Definition *other)=0
virtual void mergeReferencedBy (const Definition *other)=0
virtual void computeTooltip ()=0
virtual void writeSourceDef (OutputList &ol, const QCString &scopeName) const =0
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const =0
virtual bool hasSourceRefs () const =0
virtual bool hasSourceReffedBy () const =0
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const =0
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const =0
virtual void writeNavigationPath (OutputList &ol) const =0
virtual void writeQuickMemberLinks (OutputList &, const MemberDef *) const =0
virtual void writeSummaryLinks (OutputList &) const =0
virtual void writeDocAnchorsToTagFile (TextStream &) const =0
virtual void writeToc (OutputList &ol, const LocalToc &lt) const =0
virtual ~DefinitionMutable ()=default
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual int numDocMembers () const =0
virtual const LinkedRefMap< NamespaceDef > & getUsedNamespaces () const =0
virtual const LinkedRefMap< ClassDef > & getUsedClasses () const =0
virtual QCString displayName (bool=TRUE) const =0
virtual QCString localName () const =0
virtual bool isConstantGroup () const =0
virtual bool isModule () const =0
virtual bool isLibrary () const =0
virtual bool isInline () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool hasDetailedDescription () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual bool subGrouping () const =0
virtual MemberList * getMemberList (MemberListType lt) const =0
virtual const MemberLists & getMemberLists () const =0
virtual const MemberDef * getMemberByName (const QCString &) const =0
virtual int countVisibleMembers () const =0
virtual const MemberGroupList & getMemberGroups () const =0
virtual ClassLinkedRefMap getClasses () const =0
virtual ClassLinkedRefMap getInterfaces () const =0
virtual ClassLinkedRefMap getStructs () const =0
virtual ClassLinkedRefMap getExceptions () const =0
virtual NamespaceLinkedRefMap getNamespaces () const =0
virtual ConceptLinkedRefMap getConcepts () const =0
virtual QCString title () const =0
virtual QCString compoundTypeString () const =0
Public Member Functions inherited from Definition
virtual DefType definitionType () const =0
virtual CodeSymbolType codeSymbolType () const =0
virtual bool isAlias () const =0
virtual QCString name () const =0
virtual bool isAnonymous () const =0
virtual QCString displayName (bool includeScope=TRUE) const =0
virtual QCString localName () const =0
virtual QCString qualifiedName () const =0
virtual QCString symbolName () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString getSourceFileBase () const =0
virtual QCString getSourceAnchor () const =0
virtual QCString documentation () const =0
virtual int docLine () const =0
virtual QCString docFile () const =0
virtual QCString briefDescription (bool abbreviate=FALSE) const =0
virtual QCString briefDescriptionAsTooltip () const =0
virtual int briefLine () const =0
virtual QCString inbodyDocumentation () const =0
virtual QCString inbodyFile () const =0
virtual int inbodyLine () const =0
virtual QCString briefFile () const =0
virtual QCString getDefFileName () const =0
virtual QCString getDefFileExtension () const =0
virtual int getDefLine () const =0
virtual int getDefColumn () const =0
virtual bool hasDocumentation () const =0
virtual bool hasUserDocumentation () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isVisibleInProject () const =0
virtual bool isVisible () const =0
virtual bool isHidden () const =0
virtual bool isArtificial () const =0
virtual QCString getReference () const =0
virtual bool isReference () const =0
virtual QCString externalReference (const QCString &relPath) const =0
virtual int getStartDefLine () const =0
virtual int getStartBodyLine () const =0
virtual int getEndBodyLine () const =0
virtual const FileDef * getBodyDef () const =0
virtual SrcLangExt getLanguage () const =0
Returns the programming language this definition was written in.
virtual const GroupList & partOfGroups () const =0
virtual bool isLinkableViaGroup () const =0
virtual const RefItemVector & xrefListItems () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual Definition * getOuterScope () const =0
virtual const MemberVector & getReferencesMembers () const =0
virtual const MemberVector & getReferencedByMembers () const =0
virtual bool hasSections () const =0
virtual bool hasSources () const =0
virtual bool hasBriefDescription () const =0
returns TRUE if this class has a brief description
virtual QCString id () const =0
virtual const SectionRefs & getSectionRefs () const =0
returns the section dictionary, only of importance for pagedef
virtual QCString navigationPathAsString () const =0
virtual QCString pathFragment () const =0
virtual void _setSymbolName (const QCString &name)=0
virtual QCString _symbolName () const =0
virtual ~Definition ()=default
Private Types
enum { NAMESPACE , MODULE , CONSTANT_GROUP , LIBRARY }
Private Member Functions
void addMemberToList (MemberListType lt, MemberDef *md)
void writeMemberDeclarations (OutputList &ol, MemberListType lt, const QCString &title)
void writeMemberDocumentation (OutputList &ol, MemberListType lt, const QCString &title)
void writeDetailedDescription (OutputList &ol, const QCString &title)
void writeBriefDescription (OutputList &ol)
void startMemberDeclarations (OutputList &ol)
void endMemberDeclarations (OutputList &ol)
void writeClassDeclarations (OutputList &ol, const QCString &title, const ClassLinkedRefMap &d)
void writeConcepts (OutputList &ol, const QCString &title)
void writeInlineClasses (OutputList &ol)
void writeMemberGroups (OutputList &ol)
void writeAuthorSection (OutputList &ol)
void startMemberDocumentation (OutputList &ol)
void endMemberDocumentation (OutputList &ol)
void writeSummaryLinks (OutputList &ol) const
void addNamespaceAttributes (OutputList &ol)
void writeClassesToTagFile (TextStream &, const ClassLinkedRefMap &d)
void writeConceptsToTagFile (TextStream &)
void writeNamespaceDeclarations (OutputList &ol, const QCString &title, bool isConstantGroup=false)
Private Attributes
QCString fileName
FileList files
LinkedRefMap< NamespaceDef > m_usingDirList
LinkedRefMap< ClassDef > m_usingDeclList
LinkedRefMap< const Definition > m_innerCompounds
MemberLinkedRefMap m_allMembers
MemberLists m_memberLists
MemberGroupList m_memberGroups
ClassLinkedRefMap classes
ClassLinkedRefMap interfaces
ClassLinkedRefMap structs
ClassLinkedRefMap exceptions
ConceptLinkedRefMap m_concepts
NamespaceLinkedRefMap namespaces
bool m_subGrouping = false
enum NamespaceDefImpl:: { ... } m_type
bool m_isPublished = false
QCString metaData
bool m_inline = false
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeMember = 3 ,
TypeGroup = 4 , TypePackage = 5 , TypePage = 6 , TypeDir = 7 ,
TypeConcept = 8
}
Protected Member Functions inherited from DefinitionMixin< NamespaceDefMutable >
DefinitionMixin (const DefinitionMixin &def)=default
Detailed Description
Definition at line 52 of file namespacedef.cpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
NAMESPACE
MODULE
CONSTANT_GROUP
LIBRARY
Definition at line 158 of file namespacedef.cpp.
{ NAMESPACE, MODULE, CONSTANT_GROUP, LIBRARY } m_type;
Constructor & Destructor Documentation
NamespaceDefImpl()
NamespaceDefImpl::NamespaceDefImpl (const QCString & defFileName, int defLine, int defColumn, const QCString & name, const QCString & ref = QCString(), const QCString & refFile = QCString(), const QCString & type = QCString(), bool isPublished = false)
Definition at line 259 of file namespacedef.cpp.
                                             :
   DefinitionMixin(df,dl,dc,name)
  ,m_isPublished(isPublished)
{
  if (!fName.isEmpty())
  {
    if (!lref.isEmpty())
    {
      fileName = stripExtension(fName);
    }
    else
    {
      fileName = convertNameToFile(stripExtension(fName));
    }
  }
  else
  {
    setFileName(name);
  }
  setReference(lref);
  m_inline=FALSE;
  m_subGrouping=Config_getBool(SUBGROUPING);
  if (type=="module")
  {
    m_type = MODULE;
  }
  else if (type=="constants")
  {
    m_type = CONSTANT_GROUP;
  }
  else if (type=="library")
  {
    m_type = LIBRARY;
  }
  else
  {
    m_type = NAMESPACE;
  }
}
References Config_getBool, CONSTANT_GROUP, convertNameToFile(), FALSE, fileName, QCString::isEmpty(), LIBRARY, m_inline, m_subGrouping, m_type, MODULE, DefinitionMixin< NamespaceDefMutable >::name(), NAMESPACE, setFileName(), DefinitionMixin< NamespaceDefMutable >::setReference(), and stripExtension().
~NamespaceDefImpl()
NamespaceDefImpl::~NamespaceDefImpl () virtual
Definition at line 302 of file namespacedef.cpp.
{
}
Member Function Documentation
addInnerCompound()
void NamespaceDefImpl::addInnerCompound (Definition * d) virtual
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
Definition at line 353 of file namespacedef.cpp.
{
  //printf("%s:NamespaceDefImpl::addInnerCompound(%s)\n",qPrint(name()),qPrint(d->name()));
  m_innerCompounds.add(d->localName(),d);
  if (d->definitionType()==Definition::TypeNamespace)
  {
    insertNamespace(toNamespaceDef(d));
  }
  else if (d->definitionType()==Definition::TypeClass)
  {
    insertClass(toClassDef(d));
  }
  else if (d->definitionType()==Definition::TypeConcept)
  {
    insertConcept(toConceptDef(d));
  }
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::definitionType(), insertClass(), insertConcept(), insertNamespace(), Definition::localName(), m_innerCompounds, toClassDef(), toConceptDef(), toNamespaceDef(), Definition::TypeClass, Definition::TypeConcept, and Definition::TypeNamespace.
addListReferences()
void NamespaceDefImpl::addListReferences () virtual
Implements NamespaceDefMutable.
Definition at line 1204 of file namespacedef.cpp.
{
  //bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  {
    const RefItemVector &xrefItems = xrefListItems();
    addRefItem(xrefItems,
        qualifiedName(),
        getLanguage()==SrcLangExt_Fortran ?
          theTranslator->trModule(TRUE,TRUE) :
          theTranslator->trNamespace(TRUE,TRUE),
        getOutputFileBase(),displayName(),
        QCString(),
        this
        );
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->addListReferences(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
      ml->addListReferences(this);
    }
  }
}
References addRefItem(), displayName(), DefinitionMixin< NamespaceDefMutable >::getLanguage(), getOutputFileBase(), m_memberGroups, m_memberLists, MemberListType_documentationLists, DefinitionMixin< NamespaceDefMutable >::qualifiedName(), SrcLangExt_Fortran, theTranslator, Translator::trModule(), Translator::trNamespace(), TRUE, and DefinitionMixin< NamespaceDefMutable >::xrefListItems().
addMembersToMemberGroup()
void NamespaceDefImpl::addMembersToMemberGroup () virtual
Implements NamespaceDefMutable.
Definition at line 405 of file namespacedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ::addMembersToMemberGroup(ml.get(),&m_memberGroups,this);
    }
  }
  // add members inside sections to their groups
  for (const auto &mg : m_memberGroups)
  {
    if (mg->allMembersInSameSection() && m_subGrouping)
    {
      //printf("----> addToDeclarationSection(%s)\n",qPrint(mg->header()));
      mg->addToDeclarationSection();
    }
  }
}
References addMembersToMemberGroup(), m_memberGroups, m_memberLists, m_subGrouping, and MemberListType_declarationLists.
Referenced by addMembersToMemberGroup().
addMemberToList()
void NamespaceDefImpl::addMemberToList (MemberListType lt, MemberDef * md) private
Definition at line 1396 of file namespacedef.cpp.
{
  bool sortBriefDocs = Config_getBool(SORT_BRIEF_DOCS);
  bool sortMemberDocs = Config_getBool(SORT_MEMBER_DOCS);
  const auto &ml = m_memberLists.get(lt,MemberListContainer::Namespace);
  ml->setNeedsSorting(
      ((ml->listType()&MemberListType_declarationLists) && sortBriefDocs) ||
      ((ml->listType()&MemberListType_documentationLists) && sortMemberDocs));
  ml->push_back(md);
  if (ml->listType()&MemberListType_declarationLists)
  {
    MemberDefMutable *mdm = toMemberDefMutable(md);
    if (mdm)
    {
      mdm->setSectionList(this,ml.get());
    }
  }
}
References Config_getBool, MemberLists::get(), m_memberLists, MemberListType_declarationLists, MemberListType_documentationLists, MemberDefMutable::setSectionList(), and toMemberDefMutable().
Referenced by insertMember().
addNamespaceAttributes()
void NamespaceDefImpl::addNamespaceAttributes (OutputList & ol) private
Definition at line 889 of file namespacedef.cpp.
{
  // UNO IDL constant groups may be published
  if (getLanguage()==SrcLangExt_IDL && isConstantGroup() && m_isPublished)
  {
    ol.pushGeneratorState();
    ol.disableAllBut(OutputType::Html);
    ol.startLabels();
    ol.writeLabel("published",false);
    ol.endLabels();
    ol.popGeneratorState();
  }
}
References OutputList::disableAllBut(), OutputList::endLabels(), DefinitionMixin< NamespaceDefMutable >::getLanguage(), isConstantGroup(), m_isPublished, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), SrcLangExt_IDL, OutputList::startLabels(), and OutputList::writeLabel().
Referenced by writeDocumentation().
addUsingDeclaration()
void NamespaceDefImpl::addUsingDeclaration (ClassDef * cd) virtual
Implements NamespaceDefMutable.
Definition at line 1176 of file namespacedef.cpp.
{
  m_usingDeclList.add(cd->qualifiedName(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), m_usingDeclList, and Definition::qualifiedName().
Referenced by combineUsingRelations().
addUsingDirective()
void NamespaceDefImpl::addUsingDirective (NamespaceDef * nd) virtual
Implements NamespaceDefMutable.
Definition at line 1170 of file namespacedef.cpp.
{
  m_usingDirList.add(nd->qualifiedName(),nd);
  //printf("%s: NamespaceDefImpl::addUsingDirective: %s:%zu\n",qPrint(name()),qPrint(nd->qualifiedName()),m_usingDirList.size());
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), m_usingDirList, and Definition::qualifiedName().
Referenced by combineUsingRelations().
anchor()
virtual QCString NamespaceDefImpl::anchor () const inline virtual
Returns the anchor within a page where this item can be found
Implements NamespaceDef.
Definition at line 64 of file namespacedef.cpp.
{ return QCString(); }
codeSymbolType()
virtual CodeSymbolType NamespaceDefImpl::codeSymbolType () const inline virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 61 of file namespacedef.cpp.
    { return getLanguage()==SrcLangExt_Java ? CodeSymbolType::Package : CodeSymbolType::Namespace; }
References DefinitionMixin< NamespaceDefMutable >::getLanguage(), and SrcLangExt_Java.
combineUsingRelations()
void NamespaceDefImpl::combineUsingRelations (NamespaceDefSet & visitedNamespace) virtual
Implements NamespaceDefMutable.
Definition at line 1248 of file namespacedef.cpp.
{
  if (visitedNamespaces.find(this)!=visitedNamespaces.end()) return; // already processed
  visitedNamespaces.insert(this);
  LinkedRefMap<NamespaceDef> usingDirList = m_usingDirList;
  for (auto &nd : usingDirList)
  {
    NamespaceDefMutable *ndm = toNamespaceDefMutable(nd);
    if (ndm)
    {
      ndm->combineUsingRelations(visitedNamespaces);
    }
  }
  for (auto &nd : usingDirList)
  {
    // add used namespaces of namespace nd to this namespace
    for (const auto &und : nd->getUsedNamespaces())
    {
      addUsingDirective(und);
    }
    // add used classes of namespace nd to this namespace
    for (const auto &ucd : nd->getUsedClasses())
    {
      addUsingDeclaration(ucd);
    }
  }
}
References addUsingDeclaration(), addUsingDirective(), NamespaceDefMutable::combineUsingRelations(), m_usingDirList, and toNamespaceDefMutable().
compoundTypeString()
QCString NamespaceDefImpl::compoundTypeString () const virtual
Implements NamespaceDef.
Definition at line 1522 of file namespacedef.cpp.
{
  SrcLangExt lang = getLanguage();
  if (lang==SrcLangExt_Java)
  {
    return "package";
  }
  else if(lang==SrcLangExt_CSharp)
  {
    return "namespace";
  }
  else if (lang==SrcLangExt_Fortran)
  {
    return "module";
  }
  else if (lang==SrcLangExt_IDL)
  {
    if (isModule())
    {
      return "module";
    }
    else if (isConstantGroup())
    {
      return "constants";
    }
    else if (isLibrary())
    {
      return "library";
    }
    else
    {
      err_full(getDefFileName(),getDefLine(),"Internal inconsistency: namespace in IDL not module, library or constant group");
    }
  }
  return "namespace";
}
References err_full(), DefinitionMixin< NamespaceDefMutable >::getDefFileName(), DefinitionMixin< NamespaceDefMutable >::getDefLine(), DefinitionMixin< NamespaceDefMutable >::getLanguage(), isConstantGroup(), isLibrary(), isModule(), SrcLangExt_CSharp, SrcLangExt_Fortran, SrcLangExt_IDL, and SrcLangExt_Java.
computeAnchors()
void NamespaceDefImpl::computeAnchors () virtual
Implements NamespaceDefMutable.
Definition at line 548 of file namespacedef.cpp.
{
  MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
  if (allMemberList) allMemberList->setAnchors();
}
References getMemberList(), MemberListType_allMembersList, and MemberList::setAnchors().
countMembers()
void NamespaceDefImpl::countMembers () virtual
Implements NamespaceDefMutable.
Definition at line 1150 of file namespacedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    ml->countDecMembers();
    ml->countDocMembers();
  }
  for (const auto &mg : m_memberGroups)
  {
    mg->countDecMembers();
    mg->countDocMembers();
  }
}
References m_memberGroups, and m_memberLists.
countVisibleMembers()
int NamespaceDefImpl::countVisibleMembers () const virtual
Implements NamespaceDef.
Definition at line 1278 of file namespacedef.cpp.
{
  int count=0;
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Namespace))
  {
    if (lde->kind()==LayoutDocEntry::MemberDef)
    {
      const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
      if (lmd)
      {
        MemberList *ml = getMemberList(lmd->type);
        if (ml)
        {
          for (const auto &md : *ml)
          {
            if (md->visibleInIndex())
            {
              count++;
            }
          }
        }
      }
    }
  }
  return count;
}
References getMemberList(), LayoutDocManager::instance(), LayoutDocEntry::MemberDef, LayoutDocManager::Namespace, and LayoutDocEntryMemberDef::type.
definitionType()
virtual DefType NamespaceDefImpl::definitionType () const inline virtual
Use this for dynamic inspection of the type of the derived class
Implements NamespaceDef.
Definition at line 60 of file namespacedef.cpp.
{ return TypeNamespace; }
References Definition::TypeNamespace.
displayName()
QCString NamespaceDefImpl::displayName (bool includeScope = TRUE) const virtual
Returns the name of the definition as it appears in the output
Implements NamespaceDef.
Definition at line 1232 of file namespacedef.cpp.
{
  return makeDisplayName(this,includeScope);
}
References makeDisplayName().
Referenced by addListReferences(), title(), writeDocumentation(), writeMemberDocumentation(), and writeMemberPages().
distributeMemberGroupDocumentation()
void NamespaceDefImpl::distributeMemberGroupDocumentation () virtual
Implements NamespaceDefMutable.
Definition at line 318 of file namespacedef.cpp.
{
  for (const auto &mg : m_memberGroups)
  {
    mg->distributeMemberGroupDocumentation();
  }
}
References m_memberGroups.
endMemberDeclarations()
void NamespaceDefImpl::endMemberDeclarations (OutputList & ol) private
Definition at line 749 of file namespacedef.cpp.
{
  ol.endMemberSections();
}
References OutputList::endMemberSections().
Referenced by writeDocumentation().
endMemberDocumentation()
void NamespaceDefImpl::endMemberDocumentation (OutputList & ol) private
Definition at line 763 of file namespacedef.cpp.
{
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.enable(OutputType::Html);
    Doxygen::suppressDocWarnings = FALSE;
  }
}
References Config_getBool, OutputList::enable(), FALSE, and Doxygen::suppressDocWarnings.
Referenced by writeDocumentation().
findInnerCompound()
const Definition * NamespaceDefImpl::findInnerCompound (const QCString & name) const virtual
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
Definition at line 1186 of file namespacedef.cpp.
{
  if (n==0) return 0;
  const Definition *d = m_innerCompounds.find(n);
  if (d==0)
  {
    if (!m_usingDirList.empty())
    {
      d = m_usingDirList.find(n);
    }
    if (d==0 && !m_usingDeclList.empty())
    {
      d = m_usingDeclList.find(n);
    }
  }
  return d;
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::empty(), LinkedRefMap< T, Hash, KeyEqual, Map >::find(), m_innerCompounds, m_usingDeclList, and m_usingDirList.
findSectionsInDocumentation()
void NamespaceDefImpl::findSectionsInDocumentation () virtual
Implements NamespaceDefMutable.
Definition at line 326 of file namespacedef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
  for (const auto &mg : m_memberGroups)
  {
    mg->findSectionsInDocumentation(this);
  }
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_declarationLists)
    {
      ml->findSectionsInDocumentation(this);
    }
  }
}
References DefinitionMixin< NamespaceDefMutable >::briefDescription(), DefinitionMixin< NamespaceDefMutable >::docFile(), docFindSections(), DefinitionMixin< NamespaceDefMutable >::documentation(), m_memberGroups, m_memberLists, and MemberListType_declarationLists.
getClasses()
virtual ClassLinkedRefMap NamespaceDefImpl::getClasses () const inline virtual
Returns the classes contained in this namespace
Implements NamespaceDef.
Definition at line 105 of file namespacedef.cpp.
{ return classes; }
References classes.
getConcepts()
virtual ConceptLinkedRefMap NamespaceDefImpl::getConcepts () const inline virtual
Returns the concepts contained in this namespace
Implements NamespaceDef.
Definition at line 110 of file namespacedef.cpp.
{ return m_concepts; }
References m_concepts.
getExceptions()
virtual ClassLinkedRefMap NamespaceDefImpl::getExceptions () const inline virtual
Returns the Slice exceptions contained in this namespace
Implements NamespaceDef.
Definition at line 108 of file namespacedef.cpp.
{ return exceptions; }
References exceptions.
getInterfaces()
virtual ClassLinkedRefMap NamespaceDefImpl::getInterfaces () const inline virtual
Returns the Slice interfaces contained in this namespace
Implements NamespaceDef.
Definition at line 106 of file namespacedef.cpp.
{ return interfaces; }
References interfaces.
getMemberByName()
const MemberDef * NamespaceDefImpl::getMemberByName (const QCString & n) const virtual
Implements NamespaceDef.
Definition at line 1492 of file namespacedef.cpp.
{
  return m_allMembers.find(n);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::find(), and m_allMembers.
getMemberGroups()
virtual const MemberGroupList & NamespaceDefImpl::getMemberGroups () const inline virtual
Returns the user defined member groups
Implements NamespaceDef.
Definition at line 104 of file namespacedef.cpp.
{ return m_memberGroups; }
References m_memberGroups.
getMemberList()
MemberList * NamespaceDefImpl::getMemberList (MemberListType lt) const virtual
Implements NamespaceDef.
Definition at line 1444 of file namespacedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->listType()==lt)
    {
      return ml.get();
    }
  }
  return 0;
}
References m_memberLists.
Referenced by computeAnchors(), countVisibleMembers(), insertMember(), numDocMembers(), writeDocumentation(), writeMemberDeclarations(), writeMemberDocumentation(), writeQuickMemberLinks(), writeSummaryLinks(), and writeTagFile().
getMemberLists()
virtual const MemberLists & NamespaceDefImpl::getMemberLists () const inline virtual
Implements NamespaceDef.
Definition at line 102 of file namespacedef.cpp.
{ return m_memberLists; }
References m_memberLists.
getNamespaces()
virtual NamespaceLinkedRefMap NamespaceDefImpl::getNamespaces () const inline virtual
Returns the namespaces contained in this namespace
Implements NamespaceDef.
Definition at line 109 of file namespacedef.cpp.
{ return namespaces; }
References namespaces.
getOutputFileBase()
QCString NamespaceDefImpl::getOutputFileBase () const virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements NamespaceDef.
Definition at line 1181 of file namespacedef.cpp.
{
  return fileName;
}
References fileName.
Referenced by addListReferences(), writeBriefDescription(), writeDocumentation(), and writeTagFile().
getStructs()
virtual ClassLinkedRefMap NamespaceDefImpl::getStructs () const inline virtual
Returns the Slice structs contained in this namespace
Implements NamespaceDef.
Definition at line 107 of file namespacedef.cpp.
{ return structs; }
References structs.
getUsedClasses()
virtual const LinkedRefMap< ClassDef > & NamespaceDefImpl::getUsedClasses () const inline virtual
Implements NamespaceDef.
Definition at line 80 of file namespacedef.cpp.
{ return m_usingDeclList; }
References m_usingDeclList.
getUsedNamespaces()
virtual const LinkedRefMap< NamespaceDef > & NamespaceDefImpl::getUsedNamespaces () const inline virtual
Implements NamespaceDef.
Definition at line 78 of file namespacedef.cpp.
{ return m_usingDirList; }
References m_usingDirList.
hasDetailedDescription()
bool NamespaceDefImpl::hasDetailedDescription () const virtual
Implements NamespaceDef.
Definition at line 554 of file namespacedef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  return ((!briefDescription().isEmpty() && repeatBrief) ||
          !documentation().isEmpty());
}
References DefinitionMixin< NamespaceDefMutable >::briefDescription(), Config_getBool, and DefinitionMixin< NamespaceDefMutable >::documentation().
Referenced by writeBriefDescription(), and writeDetailedDescription().
insertClass()
void NamespaceDefImpl::insertClass (ClassDef * cd) virtual
Implements NamespaceDefMutable.
Definition at line 371 of file namespacedef.cpp.
{
  ClassLinkedRefMap &d = classes;
  if (Config_getBool(OPTIMIZE_OUTPUT_SLICE))
  {
    if (cd->compoundType()==ClassDef::Interface)
    {
      d = interfaces;
    }
    else if (cd->compoundType()==ClassDef::Struct)
    {
      d = structs;
    }
    else if (cd->compoundType()==ClassDef::Exception)
    {
      d = exceptions;
    }
  }
  d.add(cd->name(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), classes, ClassDef::compoundType(), Config_getBool, ClassDef::Exception, exceptions, ClassDef::Interface, interfaces, Definition::name(), ClassDef::Struct, and structs.
Referenced by addInnerCompound().
insertConcept()
void NamespaceDefImpl::insertConcept (ConceptDef * cd) virtual
Implements NamespaceDefMutable.
Definition at line 394 of file namespacedef.cpp.
{
  m_concepts.add(cd->name(),cd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), m_concepts, and Definition::name().
Referenced by addInnerCompound().
insertMember()
void NamespaceDefImpl::insertMember (MemberDef * md) virtual
Implements NamespaceDefMutable.
Definition at line 426 of file namespacedef.cpp.
{
  //printf("%s::insertMember(%s) isInline=%d hasDocs=%d\n",qPrint(name()),qPrint(md->name()),
  //    isInline(),hasDocumentation());
  if (md->isHidden()) return;
  MemberDefMutable *mdm = toMemberDefMutable(md);
  // if this is an inline namespace that is not documented, then insert the
  // member in the parent scope instead
  if (isInline() && !hasDocumentation())
  {
    Definition *outerScope = getOuterScope();
    if (outerScope)
    {
      if (outerScope->definitionType()==Definition::TypeNamespace)
      {
        NamespaceDefMutable *nd = toNamespaceDefMutable(outerScope);
        if (nd)
        {
          nd->insertMember(md);
          if (mdm)
          {
            mdm->setNamespace(nd);
          }
        }
      }
      else if (outerScope->definitionType()==Definition::TypeFile)
      {
        FileDef *fd = toFileDef(outerScope);
        fd->insertMember(md);
        if (mdm)
        {
          mdm->setFileDef(fd);
          mdm->setOuterScope(fd);
        }
      }
    }
  }
  else // member is a non-inline namespace or a documented inline namespace
  {
    MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
    if (allMemberList==0)
    {
      m_memberLists.emplace_back(std::make_unique<MemberList>(MemberListType_allMembersList,MemberListContainer::Namespace));
      allMemberList = m_memberLists.back().get();
    }
    allMemberList->push_back(md);
    //printf("%s::m_allMembersDict->append(%s)\n",qPrint(name()),qPrint(md->localName()));
    m_allMembers.add(md->localName(),md);
    switch(md->memberType())
    {
      case MemberType_Variable:
        addMemberToList(MemberListType_decVarMembers,md);
        addMemberToList(MemberListType_docVarMembers,md);
        break;
      case MemberType_Function:
        addMemberToList(MemberListType_decFuncMembers,md);
        addMemberToList(MemberListType_docFuncMembers,md);
        break;
      case MemberType_Typedef:
        addMemberToList(MemberListType_decTypedefMembers,md);
        addMemberToList(MemberListType_docTypedefMembers,md);
        break;
      case MemberType_Sequence:
        addMemberToList(MemberListType_decSequenceMembers,md);
        addMemberToList(MemberListType_docSequenceMembers,md);
        break;
      case MemberType_Dictionary:
        addMemberToList(MemberListType_decDictionaryMembers,md);
        addMemberToList(MemberListType_docDictionaryMembers,md);
        break;
      case MemberType_Enumeration:
        addMemberToList(MemberListType_decEnumMembers,md);
        addMemberToList(MemberListType_docEnumMembers,md);
        break;
      case MemberType_EnumValue:
        break;
      case MemberType_Define:
        addMemberToList(MemberListType_decDefineMembers,md);
        addMemberToList(MemberListType_docDefineMembers,md);
        break;
      default:
        err("NamespaceDefImpl::insertMembers(): "
            "member '%s' with unexpected type id %d and class scope '%s' inserted in namespace scope '%s'!\n",
            qPrint(md->name()),
            md->memberType(),
            md->getClassDef() ? qPrint(md->getClassDef()->name()) : "",
            qPrint(name()));
    }
    // if this is an inline namespace, then insert an alias of this member in the outer scope.
    if (isInline())
    {
      Definition *outerScope = getOuterScope();
      if (outerScope)
      {
        std::unique_ptr<MemberDef> aliasMd;
        if (outerScope->definitionType()==Definition::TypeNamespace)
        {
          aliasMd.reset(createMemberDefAlias(outerScope,md));
          NamespaceDefMutable *ndm = toNamespaceDefMutable(outerScope);
          if (ndm)
          {
            ndm->insertMember(aliasMd.get());
          }
        }
        else if (outerScope->definitionType()==Definition::TypeFile)
        {
          aliasMd.reset(createMemberDefAlias(outerScope,md));
          toFileDef(outerScope)->insertMember(aliasMd.get());
        }
        if (aliasMd)
        {
          MemberName *mn;
          QCString name = md->name();
          mn = Doxygen::functionNameLinkedMap->add(name);
          mn->push_back(std::move(aliasMd));
        }
      }
    }
  }
}
References LinkedMap< T, Hash, KeyEqual, Map >::add(), LinkedRefMap< T, Hash, KeyEqual, Map >::add(), addMemberToList(), createMemberDefAlias(), Definition::definitionType(), err(), Doxygen::functionNameLinkedMap, MemberLists::get(), MemberDef::getClassDef(), getMemberList(), DefinitionMixin< NamespaceDefMutable >::getOuterScope(), DefinitionMixin< NamespaceDefMutable >::hasDocumentation(), FileDef::insertMember(), NamespaceDefMutable::insertMember(), Definition::isHidden(), isInline(), Definition::localName(), m_allMembers, m_memberLists, MemberListType_allMembersList, MemberListType_decDefineMembers, MemberListType_decDictionaryMembers, MemberListType_decEnumMembers, MemberListType_decFuncMembers, MemberListType_decSequenceMembers, MemberListType_decTypedefMembers, MemberListType_decVarMembers, MemberListType_docDefineMembers, MemberListType_docDictionaryMembers, MemberListType_docEnumMembers, MemberListType_docFuncMembers, MemberListType_docSequenceMembers, MemberListType_docTypedefMembers, MemberListType_docVarMembers, MemberDef::memberType(), MemberType_Define, MemberType_Dictionary, MemberType_Enumeration, MemberType_EnumValue, MemberType_Function, MemberType_Sequence, MemberType_Typedef, MemberType_Variable, DefinitionMixin< NamespaceDefMutable >::name(), Definition::name(), MemberVector::push_back(), MemberName::push_back(), qPrint(), MemberDefMutable::setFileDef(), MemberDefMutable::setNamespace(), DefinitionMutable::setOuterScope(), toFileDef(), toMemberDefMutable(), toNamespaceDefMutable(), Definition::TypeFile, and Definition::TypeNamespace.
insertNamespace()
void NamespaceDefImpl::insertNamespace (NamespaceDef * nd) virtual
Implements NamespaceDefMutable.
Definition at line 399 of file namespacedef.cpp.
{
  namespaces.add(nd->name(),nd);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::add(), Definition::name(), and namespaces.
Referenced by addInnerCompound().
insertUsedFile()
void NamespaceDefImpl::insertUsedFile (FileDef * fd) virtual
Implements NamespaceDefMutable.
Definition at line 343 of file namespacedef.cpp.
{
  if (fd==0) return;
  auto it = std::find(files.begin(),files.end(),fd);
  if (it==files.end())
  {
    files.push_back(fd);
  }
}
References files.
isConstantGroup()
virtual bool NamespaceDefImpl::isConstantGroup () const inline virtual
Implements NamespaceDef.
Definition at line 85 of file namespacedef.cpp.
{ return CONSTANT_GROUP == m_type; }
References CONSTANT_GROUP, and m_type.
Referenced by addNamespaceAttributes(), compoundTypeString(), title(), and writeNamespaceDeclarations().
isInline()
virtual bool NamespaceDefImpl::isInline () const inline virtual
Implements NamespaceDef.
Definition at line 88 of file namespacedef.cpp.
{ return m_inline; }
References m_inline.
Referenced by insertMember(), and setInline().
isLibrary()
virtual bool NamespaceDefImpl::isLibrary () const inline virtual
Implements NamespaceDef.
Definition at line 87 of file namespacedef.cpp.
{ return LIBRARY == m_type; }
References LIBRARY, and m_type.
Referenced by compoundTypeString().
isLinkable()
bool NamespaceDefImpl::isLinkable () const virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements NamespaceDef.
Definition at line 1487 of file namespacedef.cpp.
{
  return isLinkableInProject() || isReference();
}
References isLinkableInProject(), and DefinitionMixin< NamespaceDefMutable >::isReference().
isLinkableInProject()
bool NamespaceDefImpl::isLinkableInProject () const virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements NamespaceDef.
Definition at line 1469 of file namespacedef.cpp.
{
  int i = name().findRev("::");
  if (i==-1) i=0; else i+=2;
  bool extractAnonNs = Config_getBool(EXTRACT_ANON_NSPACES);
  if (extractAnonNs &&                             // extract anonymous ns
      name().mid(i,20)=="anonymous_namespace{"     // correct prefix
     )                                             // not disabled by config
  {
    return TRUE;
  }
  return !name().isEmpty() && name().at(i)!='@' && // not anonymous
    (hasDocumentation() || getLanguage()==SrcLangExt_CSharp) &&  // documented
    !isReference() &&      // not an external reference
    !isHidden() &&         // not hidden
    !isArtificial();       // or artificial
}
References QCString::at(), Config_getBool, QCString::findRev(), DefinitionMixin< NamespaceDefMutable >::getLanguage(), DefinitionMixin< NamespaceDefMutable >::hasDocumentation(), DefinitionMixin< NamespaceDefMutable >::isArtificial(), QCString::isEmpty(), DefinitionMixin< NamespaceDefMutable >::isHidden(), DefinitionMixin< NamespaceDefMutable >::isReference(), DefinitionMixin< NamespaceDefMutable >::name(), SrcLangExt_CSharp, and TRUE.
Referenced by isLinkable().
isModule()
virtual bool NamespaceDefImpl::isModule () const inline virtual
Implements NamespaceDef.
Definition at line 86 of file namespacedef.cpp.
{ return NAMESPACE == m_type || MODULE == m_type; }
References m_type, MODULE, and NAMESPACE.
Referenced by compoundTypeString().
localName()
QCString NamespaceDefImpl::localName () const virtual
Returns the local name without any scope qualifiers.
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
Definition at line 1237 of file namespacedef.cpp.
{
  QCString result=name();
  int i=result.findRev("::");
  if (i!=-1)
  {
    result=result.mid(i+2);
  }
  return result;
}
References QCString::findRev(), QCString::mid(), and DefinitionMixin< NamespaceDefMutable >::name().
numDocMembers()
int NamespaceDefImpl::numDocMembers () const virtual
Implements NamespaceDef.
Definition at line 1164 of file namespacedef.cpp.
{
  MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
  return (allMemberList ? allMemberList->numDocMembers() : 0) + static_cast<int>(m_innerCompounds.size());
}
References getMemberList(), m_innerCompounds, MemberListType_allMembersList, MemberList::numDocMembers(), and LinkedRefMap< T, Hash, KeyEqual, Map >::size().
setFileName()
void NamespaceDefImpl::setFileName (const QCString & fn) virtual
Implements NamespaceDefMutable.
Definition at line 306 of file namespacedef.cpp.
{
  if (isReference())
  {
    fileName = "namespace"+fn;
  }
  else
  {
    fileName = convertNameToFile("namespace"+fn);
  }
}
References convertNameToFile(), fileName, and DefinitionMixin< NamespaceDefMutable >::isReference().
Referenced by NamespaceDefImpl().
setInline()
virtual void NamespaceDefImpl::setInline (bool isInline) inline virtual
Implements NamespaceDefMutable.
Definition at line 84 of file namespacedef.cpp.
{ m_inline = isInline; }
References isInline(), and m_inline.
setMetaData()
void NamespaceDefImpl::setMetaData (const QCString & m) virtual
Implements NamespaceDefMutable.
Definition at line 1559 of file namespacedef.cpp.
{
  metaData = m;
}
References metaData.
sortMemberLists()
void NamespaceDefImpl::sortMemberLists () virtual
Implements NamespaceDefMutable.
Definition at line 1416 of file namespacedef.cpp.
{
  for (auto &ml : m_memberLists)
  {
    if (ml->needsSorting()) { ml->sort(); ml->setNeedsSorting(FALSE); }
  }
  auto classComp = [](const ClassLinkedRefMap::Ptr &c1,const ClassLinkedRefMap::Ptr &c2)
  {
    return Config_getBool(SORT_BY_SCOPE_NAME)     ?
      qstricmp(c1->name(), c2->name())<0          :
      qstricmp(c1->className(), c2->className())<0;
  };
  std::sort(classes.begin(),   classes.end(),   classComp);
  std::sort(interfaces.begin(),interfaces.end(),classComp);
  std::sort(structs.begin(),   structs.end(),   classComp);
  std::sort(exceptions.begin(),exceptions.end(),classComp);
  auto namespaceComp = [](const NamespaceLinkedRefMap::Ptr &n1,const NamespaceLinkedRefMap::Ptr &n2)
  {
    return qstricmp(n1->name(),n2->name())<0;
  };
  std::sort(namespaces.begin(),namespaces.end(),namespaceComp);
}
References LinkedRefMap< T, Hash, KeyEqual, Map >::begin(), classes, ClassDef::className(), Config_getBool, LinkedRefMap< T, Hash, KeyEqual, Map >::end(), exceptions, FALSE, interfaces, m_memberLists, Definition::name(), namespaces, qstricmp(), and structs.
startMemberDeclarations()
void NamespaceDefImpl::startMemberDeclarations (OutputList & ol) private
Definition at line 744 of file namespacedef.cpp.
{
  ol.startMemberSections();
}
References OutputList::startMemberSections().
Referenced by writeDocumentation().
startMemberDocumentation()
void NamespaceDefImpl::startMemberDocumentation (OutputList & ol) private
Definition at line 754 of file namespacedef.cpp.
{
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    ol.disable(OutputType::Html);
    Doxygen::suppressDocWarnings = TRUE;
  }
}
References Config_getBool, OutputList::disable(), Doxygen::suppressDocWarnings, and TRUE.
Referenced by writeDocumentation().
subGrouping()
virtual bool NamespaceDefImpl::subGrouping () const inline virtual
Implements NamespaceDef.
Definition at line 100 of file namespacedef.cpp.
{ return m_subGrouping; }
References m_subGrouping.
title()
QCString NamespaceDefImpl::title () const virtual
Implements NamespaceDef.
Definition at line 1497 of file namespacedef.cpp.
{
  SrcLangExt lang = getLanguage();
  QCString pageTitle;
  if (lang==SrcLangExt_Java)
  {
    pageTitle = theTranslator->trPackage(displayName());
  }
  else if (lang==SrcLangExt_Fortran || lang==SrcLangExt_Slice)
  {
    pageTitle = theTranslator->trModuleReference(displayName());
  }
  else if (lang==SrcLangExt_IDL)
  {
    pageTitle = isConstantGroup()
        ? theTranslator->trConstantGroupReference(displayName())
        : theTranslator->trModuleReference(displayName());
  }
  else
  {
    pageTitle = theTranslator->trNamespaceReference(displayName());
  }
  return pageTitle;
}
References displayName(), DefinitionMixin< NamespaceDefMutable >::getLanguage(), isConstantGroup(), SrcLangExt_Fortran, SrcLangExt_IDL, SrcLangExt_Java, SrcLangExt_Slice, theTranslator, Translator::trConstantGroupReference(), Translator::trModuleReference(), Translator::trNamespaceReference(), and Translator::trPackage().
Referenced by writeClassDeclarations(), writeConcepts(), writeDetailedDescription(), writeDocumentation(), writeMemberDeclarations(), writeMemberDocumentation(), and writeNamespaceDeclarations().
writeAuthorSection()
void NamespaceDefImpl::writeAuthorSection (OutputList & ol) private
Definition at line 805 of file namespacedef.cpp.
{
  // write Author section (Man only)
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Man);
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), and TRUE.
Referenced by writeDocumentation().
writeBriefDescription()
void NamespaceDefImpl::writeBriefDescription (OutputList & ol) private
Definition at line 684 of file namespacedef.cpp.
{
  if (hasBriefDescription())
  {
    auto parser { createDocParser() };
    auto ast    { validatingParseDoc(*parser.get(),
                                     briefFile(),briefLine(),this,0,
                                     briefDescription(),TRUE,FALSE,
                                     QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startParagraph();
      ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Man);
      ol.writeString(" - ");
      ol.popGeneratorState();
      ol.writeDoc(ast.get(),this,0);
      ol.pushGeneratorState();
      ol.disable(OutputType::RTF);
      ol.writeString(" \n");
      ol.enable(OutputType::RTF);
      if (hasDetailedDescription())
      {
        ol.disableAllBut(OutputType::Html);
        ol.startTextLink(getOutputFileBase(),"details");
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
      }
      ol.popGeneratorState();
      ol.endParagraph();
    }
    // FIXME:PARA
    //ol.pushGeneratorState();
    //ol.disable(OutputType::RTF);
    //ol.newParagraph();
    //ol.popGeneratorState();
  }
  // Write a summary of the Slice definition including metadata.
  if (getLanguage() == SrcLangExt_Slice)
  {
    ol.startParagraph();
    ol.startTypewriter();
    if (!metaData.isEmpty())
    {
      ol.docify(metaData);
      ol.lineBreak();
    }
    ol.docify("module ");
    ol.docify(stripScope(name()));
    ol.docify(" { ... }");
    ol.endTypewriter();
    ol.endParagraph();
  }
  ol.writeSynopsis();
}
References DefinitionMixin< NamespaceDefMutable >::briefDescription(), DefinitionMixin< NamespaceDefMutable >::briefFile(), DefinitionMixin< NamespaceDefMutable >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), OutputList::endTypewriter(), FALSE, DefinitionMixin< NamespaceDefMutable >::getLanguage(), getOutputFileBase(), DefinitionMixin< NamespaceDefMutable >::hasBriefDescription(), hasDetailedDescription(), QCString::isEmpty(), OutputList::lineBreak(), metaData, DefinitionMixin< NamespaceDefMutable >::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), SrcLangExt_Slice, OutputList::startParagraph(), OutputList::startTextLink(), OutputList::startTypewriter(), stripScope(), theTranslator, Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeClassDeclarations()
void NamespaceDefImpl::writeClassDeclarations (OutputList & ol, const QCString & title, const ClassLinkedRefMap & d) private
Definition at line 772 of file namespacedef.cpp.
{
  d.writeDeclaration(ol,0,title,TRUE);
}
References title(), TRUE, and ClassLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeClassesToTagFile()
void NamespaceDefImpl::writeClassesToTagFile (TextStream & tagFile, const ClassLinkedRefMap & d) private
Definition at line 903 of file namespacedef.cpp.
{
  for (const auto &cd : list)
  {
    if (cd->isLinkableInProject())
    {
      tagFile << "    <class kind=\"" << cd->compoundTypeString()
              << "\">" << convertToXML(cd->name()) << "</class>\n";
    }
  }
}
References convertToXML().
Referenced by writeTagFile().
writeConcepts()
void NamespaceDefImpl::writeConcepts (OutputList & ol, const QCString & title) private
Definition at line 777 of file namespacedef.cpp.
{
  m_concepts.writeDeclaration(ol,title,TRUE);
}
References m_concepts, title(), TRUE, and ConceptLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeConceptsToTagFile()
void NamespaceDefImpl::writeConceptsToTagFile (TextStream & tagFile) private
Definition at line 915 of file namespacedef.cpp.
{
  for (const auto &cd : m_concepts)
  {
    if (cd->isLinkableInProject())
    {
      tagFile << "    <concept>" << convertToXML(cd->name()) << "</concept>\n";
    }
  }
}
References convertToXML(), and m_concepts.
Referenced by writeTagFile().
writeDetailedDescription()
void NamespaceDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) private
Definition at line 640 of file namespacedef.cpp.
{
  if (hasDetailedDescription())
  {
    ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Html);
      ol.writeAnchor(QCString(),"details");
    ol.popGeneratorState();
    ol.startGroupHeader();
    ol.parseText(title);
    ol.endGroupHeader();
    ol.startTextBlock();
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF))
    {
      ol.generateDoc(briefFile(),briefLine(),this,0,briefDescription(),FALSE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    if (!briefDescription().isEmpty() && Config_getBool(REPEAT_BRIEF) &&
        !documentation().isEmpty())
    {
      ol.pushGeneratorState();
        ol.disable(OutputType::Man);
        ol.disable(OutputType::RTF);
        //ol.newParagraph(); // FIXME:PARA
        ol.enableAll();
        ol.disableAllBut(OutputType::Man);
        ol.enable(OutputType::Latex);
        ol.writeString("\n\n");
      ol.popGeneratorState();
    }
    if (!documentation().isEmpty())
    {
      ol.generateDoc(docFile(),docLine(),this,0,documentation()+"\n",TRUE,FALSE,
                     QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    ol.endTextBlock();
  }
}
References DefinitionMixin< NamespaceDefMutable >::briefDescription(), DefinitionMixin< NamespaceDefMutable >::briefFile(), DefinitionMixin< NamespaceDefMutable >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< NamespaceDefMutable >::docFile(), DefinitionMixin< NamespaceDefMutable >::docLine(), DefinitionMixin< NamespaceDefMutable >::documentation(), OutputList::enable(), OutputList::enableAll(), OutputList::endGroupHeader(), OutputList::endTextBlock(), FALSE, OutputList::generateDoc(), hasDetailedDescription(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), OutputList::startTextBlock(), title(), TRUE, OutputList::writeAnchor(), OutputList::writeRuler(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDocumentation()
void NamespaceDefImpl::writeDocumentation (OutputList & ol) virtual
Implements NamespaceDefMutable.
Definition at line 926 of file namespacedef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  //bool outputJava = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
  //bool fortranOpt = Config_getBool(OPTIMIZE_FOR_FORTRAN);
  QCString pageTitle = title();
  startFile(ol,getOutputFileBase(),name(),pageTitle,HighlightedItem::NamespaceVisible,!generateTreeView);
  if (!generateTreeView)
  {
    if (getOuterScope()!=Doxygen::globalScope)
    {
      writeNavigationPath(ol);
    }
    ol.endQuickIndices();
  }
  startTitle(ol,getOutputFileBase(),this);
  ol.parseText(pageTitle);
  addGroupListToTitle(ol,this);
  addNamespaceAttributes(ol);
  endTitle(ol,getOutputFileBase(),displayName());
  ol.startContents();
  //if (Doxygen::searchIndex)
  //{
  //  Doxygen::searchIndex->setCurrentDoc(this,anchor(),FALSE);
  //  Doxygen::searchIndex->addWord(localName(),TRUE);
  //}
  //Doxygen::indexList->addIndexItem(this,0);
  //---------------------------------------- start flexible part -------------------------------
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Namespace))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
        startMemberDeclarations(ol);
        break;
      case LayoutDocEntry::NamespaceClasses:
        {
          if (ls) writeClassDeclarations(ol,ls->title(lang),classes);
        }
        break;
      case LayoutDocEntry::NamespaceInterfaces:
        {
          if (ls) writeClassDeclarations(ol,ls->title(lang),interfaces);
        }
        break;
      case LayoutDocEntry::NamespaceStructs:
        {
          if (ls) writeClassDeclarations(ol,ls->title(lang),structs);
        }
        break;
      case LayoutDocEntry::NamespaceExceptions:
        {
          if (ls) writeClassDeclarations(ol,ls->title(lang),exceptions);
        }
        break;
      case LayoutDocEntry::NamespaceConcepts:
        {
          if (ls) writeConcepts(ol,ls->title(lang));
        }
        break;
      case LayoutDocEntry::NamespaceNestedNamespaces:
        {
          if (ls) writeNamespaceDeclarations(ol,ls->title(lang),false);
        }
        break;
      case LayoutDocEntry::NamespaceNestedConstantGroups:
        {
          if (ls) writeNamespaceDeclarations(ol,ls->title(lang),true);
        }
        break;
      case LayoutDocEntry::MemberGroups:
        writeMemberGroups(ol);
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd) writeMemberDeclarations(ol,lmd->type,lmd->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDeclEnd:
        endMemberDeclarations(ol);
        break;
      case LayoutDocEntry::DetailedDesc:
        {
          if (ls) writeDetailedDescription(ol,ls->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDefStart:
        startMemberDocumentation(ol);
        break;
      case LayoutDocEntry::NamespaceInlineClasses:
        writeInlineClasses(ol);
        break;
      case LayoutDocEntry::MemberDef:
        {
          const LayoutDocEntryMemberDef *lmd = dynamic_cast<const LayoutDocEntryMemberDef*>(lde.get());
          if (lmd) writeMemberDocumentation(ol,lmd->type,lmd->title(lang));
        }
        break;
      case LayoutDocEntry::MemberDefEnd:
        endMemberDocumentation(ol);
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::ClassIncludes:
      case LayoutDocEntry::ClassInheritanceGraph:
      case LayoutDocEntry::ClassNestedClasses:
      case LayoutDocEntry::ClassCollaborationGraph:
      case LayoutDocEntry::ClassAllMembersLink:
      case LayoutDocEntry::ClassUsedFiles:
      case LayoutDocEntry::ClassInlineClasses:
      case LayoutDocEntry::ConceptDefinition:
      case LayoutDocEntry::FileClasses:
      case LayoutDocEntry::FileConcepts:
      case LayoutDocEntry::FileInterfaces:
      case LayoutDocEntry::FileStructs:
      case LayoutDocEntry::FileExceptions:
      case LayoutDocEntry::FileNamespaces:
      case LayoutDocEntry::FileConstantGroups:
      case LayoutDocEntry::FileIncludes:
      case LayoutDocEntry::FileIncludeGraph:
      case LayoutDocEntry::FileIncludedByGraph:
      case LayoutDocEntry::FileSourceLink:
      case LayoutDocEntry::FileInlineClasses:
      case LayoutDocEntry::GroupClasses:
      case LayoutDocEntry::GroupConcepts:
      case LayoutDocEntry::GroupInlineClasses:
      case LayoutDocEntry::GroupNamespaces:
      case LayoutDocEntry::GroupDirs:
      case LayoutDocEntry::GroupNestedGroups:
      case LayoutDocEntry::GroupFiles:
      case LayoutDocEntry::GroupGraph:
      case LayoutDocEntry::GroupPageDocs:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::Namespace entry list\n",lde->kind());
        break;
    }
  }
  //---------------------------------------- end flexible part -------------------------------
  ol.endContents();
  endFileWithNavPath(ol,this);
  if (Config_getBool(SEPARATE_MEMBER_PAGES))
  {
    MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
    if (allMemberList) allMemberList->sort();
    writeMemberPages(ol);
  }
}
References addGroupListToTitle(), addNamespaceAttributes(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, classes, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, LayoutDocEntry::ConceptDefinition, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, displayName(), OutputList::endContents(), endFileWithNavPath(), endMemberDeclarations(), endMemberDocumentation(), OutputList::endQuickIndices(), endTitle(), err(), exceptions, LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::FileStructs, DefinitionMixin< NamespaceDefMutable >::getLanguage(), getMemberList(), DefinitionMixin< NamespaceDefMutable >::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, LayoutDocManager::instance(), interfaces, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, MemberListType_allMembersList, DefinitionMixin< NamespaceDefMutable >::name(), LayoutDocManager::Namespace, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, LayoutDocEntry::NamespaceStructs, OutputList::parseText(), MemberVector::sort(), OutputList::startContents(), startFile(), startMemberDeclarations(), startMemberDocumentation(), startTitle(), structs, title(), LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), LayoutDocEntryMemberDef::title(), LayoutDocEntryMemberDecl::type, LayoutDocEntryMemberDef::type, writeAuthorSection(), writeBriefDescription(), writeClassDeclarations(), writeConcepts(), writeDetailedDescription(), writeInlineClasses(), writeMemberDeclarations(), writeMemberDocumentation(), writeMemberGroups(), writeMemberPages(), writeNamespaceDeclarations(), and DefinitionMixin< NamespaceDefMutable >::writeNavigationPath().
writeInlineClasses()
void NamespaceDefImpl::writeInlineClasses (OutputList & ol) private
Definition at line 782 of file namespacedef.cpp.
{
  classes.writeDocumentation(ol,this);
}
References classes, and ClassLinkedRefMap::writeDocumentation().
Referenced by writeDocumentation().
writeMemberDeclarations()
void NamespaceDefImpl::writeMemberDeclarations (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1456 of file namespacedef.cpp.
{
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDeclarations(ol,0,this,0,0,title,QCString());
}
References getMemberList(), title(), and MemberList::writeDeclarations().
Referenced by writeDocumentation().
writeMemberDocumentation()
void NamespaceDefImpl::writeMemberDocumentation (OutputList & ol, MemberListType lt, const QCString & title) private
Definition at line 1462 of file namespacedef.cpp.
{
  MemberList * ml = getMemberList(lt);
  if (ml) ml->writeDocumentation(ol,displayName(),this,title);
}
References displayName(), getMemberList(), title(), and MemberList::writeDocumentation().
Referenced by writeDocumentation().
writeMemberGroups()
void NamespaceDefImpl::writeMemberGroups (OutputList & ol) private
Definition at line 793 of file namespacedef.cpp.
{
  /* write user defined member groups */
  for (const auto &mg : m_memberGroups)
  {
    if (!mg->allMembersInSameSection() || !m_subGrouping)
    {
      mg->writeDeclarations(ol,0,this,0,0);
    }
  }
}
References m_memberGroups, and m_subGrouping.
Referenced by writeDocumentation().
writeMemberPages()
void NamespaceDefImpl::writeMemberPages (OutputList & ol) virtual
Implements NamespaceDefMutable.
Definition at line 1094 of file namespacedef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  for (const auto &ml : m_memberLists)
  {
    if (ml->listType()&MemberListType_documentationLists)
    {
      ml->writeDocumentationPage(ol,displayName(),this);
    }
  }
  ol.popGeneratorState();
}
References OutputList::disableAllBut(), displayName(), m_memberLists, MemberListType_documentationLists, OutputList::popGeneratorState(), and OutputList::pushGeneratorState().
Referenced by writeDocumentation().
writeNamespaceDeclarations()
void NamespaceDefImpl::writeNamespaceDeclarations (OutputList & ol, const QCString & title, bool isConstantGroup = false) private
Definition at line 787 of file namespacedef.cpp.
{
  namespaces.writeDeclaration(ol,title,isConstantGroup,TRUE);
}
References isConstantGroup(), namespaces, title(), TRUE, and NamespaceLinkedRefMap::writeDeclaration().
Referenced by writeDocumentation().
writeQuickMemberLinks()
void NamespaceDefImpl::writeQuickMemberLinks (OutputList & ol, const MemberDef * currentMd) const virtual
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
Definition at line 1109 of file namespacedef.cpp.
{
  bool createSubDirs=Config_getBool(CREATE_SUBDIRS);
  ol.writeString("      <div class=\"navtab\">\n");
  ol.writeString("        <table>\n");
  MemberList *allMemberList = getMemberList(MemberListType_allMembersList);
  if (allMemberList)
  {
    for (const auto &md : *allMemberList)
    {
      if (md->getNamespaceDef()==this && md->isLinkable() && !md->isEnumValue())
      {
        if (md->isLinkableInProject())
        {
          if (md==currentMd) // selected item => highlight
          {
            ol.writeString("          <tr><td class=\"navtabHL\">");
          }
          else
          {
            ol.writeString("          <tr><td class=\"navtab\">");
          }
          ol.writeString("<a class=\"navtab\" ");
          ol.writeString("href=\"");
          if (createSubDirs) ol.writeString("../../");
          ol.writeString(addHtmlExtensionIfMissing(md->getOutputFileBase())+"#"+md->anchor());
          ol.writeString("\">");
          ol.writeString(convertToHtml(md->localName()));
          ol.writeString("</a>");
          ol.writeString("</td></tr>\n");
        }
      }
    }
  }
  ol.writeString("        </table>\n");
  ol.writeString("      </div>\n");
}
References addHtmlExtensionIfMissing(), Config_getBool, convertToHtml(), createSubDirs(), getMemberList(), MemberListType_allMembersList, and OutputList::writeString().
writeSummaryLinks()
void NamespaceDefImpl::writeSummaryLinks (OutputList & ol) const private virtual
Reimplemented from DefinitionMixin< NamespaceDefMutable >.
Definition at line 817 of file namespacedef.cpp.
{
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Html);
  bool first=TRUE;
  SrcLangExt lang = getLanguage();
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Namespace))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    if (lde->kind()==LayoutDocEntry::NamespaceClasses && classes.declVisible() && ls)
    {
      QCString label = "nested-classes";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceInterfaces && interfaces.declVisible() && ls)
    {
      QCString label = "interfaces";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceStructs && structs.declVisible() && ls)
    {
      QCString label = "structs";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceExceptions && exceptions.declVisible() && ls)
    {
      QCString label = "exceptions";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceNestedNamespaces && namespaces.declVisible(false) && ls)
    {
      QCString label = "namespaces";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceNestedConstantGroups && namespaces.declVisible(true) && ls)
    {
      QCString label = "constantgroups";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()==LayoutDocEntry::NamespaceConcepts && m_concepts.declVisible() && ls)
    {
      QCString label = "concepts";
      ol.writeSummaryLink(QCString(),label,ls->title(lang),first);
      first=FALSE;
    }
    else if (lde->kind()== LayoutDocEntry::MemberDecl)
    {
      const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
      if (lmd)
      {
        MemberList * ml = getMemberList(lmd->type);
        if (ml && ml->declVisible())
        {
          ol.writeSummaryLink(QCString(),MemberList::listTypeAsString(ml->listType()),lmd->title(lang),first);
          first=FALSE;
        }
      }
    }
  }
  if (!first)
  {
    ol.writeString("  </div>\n");
  }
  ol.popGeneratorState();
}
References classes, ConceptLinkedRefMap::declVisible(), MemberList::declVisible(), NamespaceLinkedRefMap::declVisible(), ClassLinkedRefMap::declVisible(), OutputList::disableAllBut(), exceptions, FALSE, DefinitionMixin< NamespaceDefMutable >::getLanguage(), getMemberList(), LayoutDocManager::instance(), interfaces, MemberList::listType(), MemberList::listTypeAsString(), m_concepts, LayoutDocEntry::MemberDecl, LayoutDocManager::Namespace, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, namespaces, LayoutDocEntry::NamespaceStructs, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), structs, LayoutDocEntrySection::title(), LayoutDocEntryMemberDecl::title(), TRUE, LayoutDocEntryMemberDecl::type, OutputList::writeString(), and OutputList::writeSummaryLink().
writeTagFile()
void NamespaceDefImpl::writeTagFile (TextStream & tagFile) virtual
Implements NamespaceDefMutable.
Definition at line 561 of file namespacedef.cpp.
{
  tagFile << "  <compound kind=\"namespace\">\n";
  tagFile << "    <name>" << convertToXML(name()) << "</name>\n";
  tagFile << "    <filename>" << addHtmlExtensionIfMissing(getOutputFileBase()) << "</filename>\n";
  QCString idStr = id();
  if (!idStr.isEmpty())
  {
    tagFile << "    <clangid>" << convertToXML(idStr) << "</clangid>\n";
  }
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Namespace))
  {
    switch (lde->kind())
    {
      case LayoutDocEntry::NamespaceNestedNamespaces:
        {
          for (const auto &nd : namespaces)
          {
            if (nd->isLinkableInProject())
            {
              tagFile << "    <namespace>" << convertToXML(nd->name()) << "</namespace>\n";
            }
          }
        }
        break;
      case LayoutDocEntry::NamespaceClasses:
        {
          writeClassesToTagFile(tagFile, classes);
        }
        break;
      case LayoutDocEntry::NamespaceInterfaces:
        {
          writeClassesToTagFile(tagFile, interfaces);
        }
        break;
      case LayoutDocEntry::NamespaceStructs:
        {
          writeClassesToTagFile(tagFile, structs);
        }
        break;
      case LayoutDocEntry::NamespaceExceptions:
        {
          writeClassesToTagFile(tagFile, exceptions);
        }
        break;
      case LayoutDocEntry::NamespaceConcepts:
        {
          writeConceptsToTagFile(tagFile);
        }
        break;
      case LayoutDocEntry::MemberDecl:
        {
          const LayoutDocEntryMemberDecl *lmd = dynamic_cast<const LayoutDocEntryMemberDecl*>(lde.get());
          if (lmd)
          {
            MemberList * ml = getMemberList(lmd->type);
            if (ml)
            {
              ml->writeTagFile(tagFile);
            }
          }
        }
        break;
      case LayoutDocEntry::MemberGroups:
        {
          for (const auto &mg : m_memberGroups)
          {
            mg->writeTagFile(tagFile);
          }
        }
        break;
      default:
        break;
    }
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << "  </compound>\n";
}
References addHtmlExtensionIfMissing(), classes, convertToXML(), exceptions, getMemberList(), getOutputFileBase(), DefinitionMixin< NamespaceDefMutable >::id(), LayoutDocManager::instance(), interfaces, QCString::isEmpty(), m_memberGroups, LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberGroups, DefinitionMixin< NamespaceDefMutable >::name(), LayoutDocManager::Namespace, LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedNamespaces, namespaces, LayoutDocEntry::NamespaceStructs, structs, LayoutDocEntryMemberDecl::type, writeClassesToTagFile(), writeConceptsToTagFile(), DefinitionMixin< NamespaceDefMutable >::writeDocAnchorsToTagFile(), and MemberList::writeTagFile().
Member Data Documentation
classes
ClassLinkedRefMap NamespaceDefImpl::classes private
Definition at line 151 of file namespacedef.cpp.
Referenced by getClasses(), insertClass(), sortMemberLists(), writeDocumentation(), writeInlineClasses(), writeSummaryLinks(), and writeTagFile().
exceptions
ClassLinkedRefMap NamespaceDefImpl::exceptions private
Definition at line 154 of file namespacedef.cpp.
Referenced by getExceptions(), insertClass(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
fileName
QCString NamespaceDefImpl::fileName private
Definition at line 141 of file namespacedef.cpp.
Referenced by getOutputFileBase(), NamespaceDefImpl(), and setFileName().
files
FileList NamespaceDefImpl::files private
Definition at line 142 of file namespacedef.cpp.
Referenced by insertUsedFile().
interfaces
ClassLinkedRefMap NamespaceDefImpl::interfaces private
Definition at line 152 of file namespacedef.cpp.
Referenced by getInterfaces(), insertClass(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
m_allMembers
MemberLinkedRefMap NamespaceDefImpl::m_allMembers private
Definition at line 148 of file namespacedef.cpp.
Referenced by getMemberByName(), and insertMember().
m_concepts
ConceptLinkedRefMap NamespaceDefImpl::m_concepts private
Definition at line 155 of file namespacedef.cpp.
Referenced by getConcepts(), insertConcept(), writeConcepts(), writeConceptsToTagFile(), and writeSummaryLinks().
m_inline
bool NamespaceDefImpl::m_inline = false private
Definition at line 161 of file namespacedef.cpp.
Referenced by isInline(), NamespaceDefImpl(), and setInline().
m_innerCompounds
LinkedRefMap<const Definition> NamespaceDefImpl::m_innerCompounds private
Definition at line 146 of file namespacedef.cpp.
Referenced by addInnerCompound(), findInnerCompound(), and numDocMembers().
m_isPublished
bool NamespaceDefImpl::m_isPublished = false private
Definition at line 159 of file namespacedef.cpp.
Referenced by addNamespaceAttributes().
m_memberGroups
MemberGroupList NamespaceDefImpl::m_memberGroups private
Definition at line 150 of file namespacedef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), countMembers(), distributeMemberGroupDocumentation(), findSectionsInDocumentation(), getMemberGroups(), writeMemberGroups(), and writeTagFile().
m_memberLists
MemberLists NamespaceDefImpl::m_memberLists private
Definition at line 149 of file namespacedef.cpp.
Referenced by addListReferences(), addMembersToMemberGroup(), addMemberToList(), countMembers(), findSectionsInDocumentation(), getMemberList(), getMemberLists(), insertMember(), sortMemberLists(), and writeMemberPages().
m_subGrouping
bool NamespaceDefImpl::m_subGrouping = false private
Definition at line 157 of file namespacedef.cpp.
Referenced by addMembersToMemberGroup(), NamespaceDefImpl(), subGrouping(), and writeMemberGroups().
[]
enum { ... } NamespaceDefImpl::m_type
Referenced by isConstantGroup(), isLibrary(), isModule(), and NamespaceDefImpl().
m_usingDeclList
LinkedRefMap<ClassDef> NamespaceDefImpl::m_usingDeclList private
Definition at line 145 of file namespacedef.cpp.
Referenced by addUsingDeclaration(), findInnerCompound(), and getUsedClasses().
m_usingDirList
LinkedRefMap<NamespaceDef> NamespaceDefImpl::m_usingDirList private
Definition at line 144 of file namespacedef.cpp.
Referenced by addUsingDirective(), combineUsingRelations(), findInnerCompound(), and getUsedNamespaces().
metaData
QCString NamespaceDefImpl::metaData private
Definition at line 160 of file namespacedef.cpp.
Referenced by setMetaData(), and writeBriefDescription().
namespaces
NamespaceLinkedRefMap NamespaceDefImpl::namespaces private
Definition at line 156 of file namespacedef.cpp.
Referenced by getNamespaces(), insertNamespace(), sortMemberLists(), writeNamespaceDeclarations(), writeSummaryLinks(), and writeTagFile().
structs
ClassLinkedRefMap NamespaceDefImpl::structs private
Definition at line 153 of file namespacedef.cpp.
Referenced by getStructs(), insertClass(), sortMemberLists(), writeDocumentation(), writeSummaryLinks(), and writeTagFile().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/namespacedef.cpp