Doxygen: /home/runner/work/doxygen/doxygen/src/qcstring.h File Reference
qcstring.h File Reference
#include <string>
#include <algorithm>
#include <cctype>
#include <cstring>
#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <ostream>
#include "utf8.h"
Classes
class QCString
This is an alternative implementation of QCString.
Macros
#define FALSE false
#define TRUE true
#define ASSERT(x)
#define qsnprintf snprintf
#define HAS_IMPLICIT_CAST_TO_PLAIN_C_STRING 0
#define HAS_CHARACTER_APPEND_OPERATOR 1
Typedefs
typedef unsigned char uchar
typedef unsigned short ushort
typedef unsigned uint
typedef unsigned long ulong
typedef int64_t int64
typedef uint64_t uint64
Functions
void * qmemmove (void *dst, const void *src, size_t len)
char * qstrdup (const char *)
uint cstrlen (const char *str)
uint qstrlen (const char *str)
char * cstrcpy (char *dst, const char *src)
char * qstrcpy (char *dst, const char *src)
char * qstrncpy (char *dst, const char *src, size_t len)
int cstrcmp (const char *str1, const char *str2)
bool qisempty (const char *s)
int qstrcmp (const char *str1, const char *str2)
int cstrncmp (const char *str1, const char *str2, size_t len)
int qstrncmp (const char *str1, const char *str2, size_t len)
bool qisspace (char c)
int qstricmp (const char *str1, const char *str2)
int qstrnicmp (const char *str1, const char *str2, size_t len)
bool operator== (const QCString &s1, const QCString &s2)
bool operator== (const QCString &s1, const char *s2)
bool operator== (const char *s1, const QCString &s2)
bool operator!= (const QCString &s1, const QCString &s2)
bool operator!= (const QCString &s1, const char *s2)
bool operator!= (const char *s1, const QCString &s2)
bool operator< (const QCString &s1, const QCString &s2)
bool operator< (const QCString &s1, const char *s2)
bool operator< (const char *s1, const QCString &s2)
bool operator<= (const QCString &s1, const char *s2)
bool operator<= (const char *s1, const QCString &s2)
bool operator> (const QCString &s1, const char *s2)
bool operator> (const char *s1, const QCString &s2)
bool operator>= (const QCString &s1, const char *s2)
bool operator>= (const char *s1, const QCString &s2)
QCString operator+ (const QCString &s1, const QCString &s2)
QCString operator+ (const QCString &s1, const char *s2)
QCString operator+ (const char *s1, const QCString &s2)
const char * qPrint (const char *s)
const char * qPrint (const QCString &s)
const char * qPrint (const std::string &s)
std::string toStdString (const QCString &s)
int qstricmp (const QCString &str1, const char *str2)
int qstricmp (const char *str1, const QCString &str2)
int qstricmp (const QCString &str1, const QCString &str2)
int qstrnicmp (const QCString &str1, const char *str2, size_t len)
int qstrnicmp (const char *str1, const QCString &str2, size_t len)
int qstrnicmp (const QCString &str1, const QCString &str2, size_t len)
QCString substitute (const QCString &str, const QCString &find, const QCString &replace)
substitute all occurrences of src in s by dst
QCString substitute (const QCString &str, const char *find, const char *replace)
QCString substitute (const QCString &s, const QCString &src, const QCString &dst, int skip_seq)
substitute all occurrences of src in s by dst, but skip each consecutive sequence of src where the number consecutive src matches skip_seq; if skip_seq is negative, skip any number of consecutive src
QCString substitute (const QCString &s, char srcChar, char dstChar)
std::ostream & operator<< (std::ostream &os, const QCString &s)
Macro Definition Documentation
ASSERT
#define ASSERT (x)
Value:
        if ( !(x) )\
        fprintf(stderr,"ASSERT: \"%s\" in %s (%d)\n",#x,__FILE__,__LINE__)
Definition at line 44 of file qcstring.h.
FALSE
#define FALSE false
Definition at line 33 of file qcstring.h.
HAS_CHARACTER_APPEND_OPERATOR
#define HAS_CHARACTER_APPEND_OPERATOR 1
Definition at line 508 of file qcstring.h.
HAS_IMPLICIT_CAST_TO_PLAIN_C_STRING
#define HAS_IMPLICIT_CAST_TO_PLAIN_C_STRING 0
Definition at line 475 of file qcstring.h.
qsnprintf
#define qsnprintf snprintf
Definition at line 57 of file qcstring.h.
TRUE
#define TRUE true
Definition at line 36 of file qcstring.h.
Typedef Documentation
int64
typedef int64_t int64
Definition at line 42 of file qcstring.h.
uchar
typedef unsigned char uchar
Definition at line 38 of file qcstring.h.
uint
typedef unsigned uint
Definition at line 40 of file qcstring.h.
uint64
typedef uint64_t uint64
Definition at line 43 of file qcstring.h.
ulong
typedef unsigned long ulong
Definition at line 41 of file qcstring.h.
ushort
typedef unsigned short ushort
Definition at line 39 of file qcstring.h.
Function Documentation
cstrcmp()
int cstrcmp (const char * str1, const char * str2) inline
Definition at line 76 of file qcstring.h.
{ return strcmp(str1,str2); }
cstrcpy()
char * cstrcpy (char * dst, const char * src) inline
Definition at line 68 of file qcstring.h.
{ return strcpy(dst,src); }
cstrlen()
uint cstrlen (const char * str) inline
Definition at line 62 of file qcstring.h.
{ return static_cast<uint>(strlen(str)); }
cstrncmp()
int cstrncmp (const char * str1, const char * str2, size_t len) inline
Definition at line 88 of file qcstring.h.
{ return strncmp(str1,str2,len); }
operator!=() [1/3]
bool operator!= (const char * s1, const QCString & s2) inline
Definition at line 563 of file qcstring.h.
{ return qstrcmp(s1,s2.data()) != 0; }
References QCString::data(), and qstrcmp().
operator!=() [2/3]
bool operator!= (const QCString & s1, const char * s2) inline
Definition at line 560 of file qcstring.h.
{ return qstrcmp(s1.data(),s2) != 0; }
References QCString::data(), and qstrcmp().
operator!=() [3/3]
bool operator!= (const QCString & s1, const QCString & s2) inline
Definition at line 557 of file qcstring.h.
{ return s1.str() != s2.str(); }
References QCString::str().
operator+() [1/3]
QCString operator+ (const char * s1, const QCString & s2) inline
Definition at line 606 of file qcstring.h.
{
    QCString tmp(s1);
    tmp.append(s2);
    return tmp;
}
References QCString::append().
operator+() [2/3]
QCString operator+ (const QCString & s1, const char * s2) inline
Definition at line 599 of file qcstring.h.
{
    QCString tmp(s1);
    tmp.append(s2);
    return tmp;
}
References QCString::append().
operator+() [3/3]
QCString operator+ (const QCString & s1, const QCString & s2) inline
Definition at line 593 of file qcstring.h.
{
  return QCString(s1.str()+s2.str());
}
References QCString::str().
operator<() [1/3]
bool operator< (const char * s1, const QCString & s2) inline
Definition at line 572 of file qcstring.h.
{ return qstrcmp(s1,s2.data()) < 0; }
References QCString::data(), and qstrcmp().
operator<() [2/3]
bool operator< (const QCString & s1, const char * s2) inline
Definition at line 569 of file qcstring.h.
{ return qstrcmp(s1.data(),s2) < 0; }
References QCString::data(), and qstrcmp().
operator<() [3/3]
bool operator< (const QCString & s1, const QCString & s2) inline
Definition at line 566 of file qcstring.h.
{ return qstrcmp(s1.data(),s2.data()) < 0; }
References QCString::data(), and qstrcmp().
operator<<()
std::ostream & operator<< (std::ostream & os, const QCString & s) inline
Definition at line 680 of file qcstring.h.
{
    os << s.str();
    return os;
}
References QCString::str().
operator<=() [1/2]
bool operator<= (const char * s1, const QCString & s2) inline
Definition at line 578 of file qcstring.h.
{ return qstrcmp(s1,s2.data()) <= 0; }
References QCString::data(), and qstrcmp().
operator<=() [2/2]
bool operator<= (const QCString & s1, const char * s2) inline
Definition at line 575 of file qcstring.h.
{ return qstrcmp(s1.data(),s2) <= 0; }
References QCString::data(), and qstrcmp().
operator==() [1/3]
bool operator== (const char * s1, const QCString & s2) inline
Definition at line 554 of file qcstring.h.
{ return qstrcmp(s1,s2.data()) == 0; }
References QCString::data(), and qstrcmp().
operator==() [2/3]
bool operator== (const QCString & s1, const char * s2) inline
Definition at line 551 of file qcstring.h.
{ return qstrcmp(s1.data(),s2) == 0; }
References QCString::data(), and qstrcmp().
operator==() [3/3]
bool operator== (const QCString & s1, const QCString & s2) inline
Definition at line 548 of file qcstring.h.
{ return s1.str() == s2.str(); }
References QCString::str().
operator>() [1/2]
bool operator> (const char * s1, const QCString & s2) inline
Definition at line 584 of file qcstring.h.
{ return qstrcmp(s1,s2.data()) > 0; }
References QCString::data(), and qstrcmp().
operator>() [2/2]
bool operator> (const QCString & s1, const char * s2) inline
Definition at line 581 of file qcstring.h.
{ return qstrcmp(s1.data(),s2) > 0; }
References QCString::data(), and qstrcmp().
operator>=() [1/2]
bool operator>= (const char * s1, const QCString & s2) inline
Definition at line 590 of file qcstring.h.
{ return qstrcmp(s1,s2.data()) >= 0; }
References QCString::data(), and qstrcmp().
operator>=() [2/2]
bool operator>= (const QCString & s1, const char * s2) inline
Definition at line 587 of file qcstring.h.
{ return qstrcmp(s1.data(),s2) >= 0; }
References QCString::data(), and qstrcmp().
qisempty()
bool qisempty (const char * s) inline
Definition at line 79 of file qcstring.h.
{ return s==0 || *s==0; }
Referenced by qstrcmp(), and qstrncmp().
qisspace()
bool qisspace (char c) inline
Definition at line 97 of file qcstring.h.
{ return c==' ' || c=='\t' || c=='\n' || c=='\r'; }
Referenced by Markdown::processQuotations(), QCString::quoted(), QCString::removeWhiteSpace(), QCString::simplifyWhiteSpace(), QCString::stripWhiteSpace(), QCString::toLong(), QCString::toUInt64(), QCString::toULong(), and DotAttributes::updateValue().
qmemmove()
void * qmemmove (void * dst, const void * src, size_t len)
Definition at line 402 of file qcstring.cpp.
{
    char *d;
    const char *s;
    if ( dst > src ) {
        d = static_cast<char *>(dst) + len - 1;
        s = static_cast<const char *>(src) + len - 1;
        while ( len-- )
            *d-- = *s--;
    } else if ( dst < src ) {
        d = static_cast<char *>(dst);
        s = static_cast<const char *>(src);
        while ( len-- )
            *d++ = *s++;
    }
    return dst;
}
Referenced by BufStr::dropFromStart().
qPrint() [1/3]
const char * qPrint (const char * s) inline
Definition at line 613 of file qcstring.h.
{
  if (s) return s; else return "";
}
Referenced by MemberDefImpl::_writeCallerGraph(), MemberDefImpl::_writeCallGraph(), FileDefImpl::acquireFileVersion(), addAnchor(), addClassToContext(), addConceptToContext(), addGroupToGroups(), addIncludeFile(), addLocalObjCMethod(), addMemberDocs(), addMemberFunction(), addMemberToGroups(), addModule(), addRelatedPage(), addSection(), addSubprogram(), addVariable(), addVariableToClass(), addVariableToFile(), addXRefItem(), adjustColorStyleSetting(), adjustConfiguration(), adjustStringSetting(), ExprAstFilter::apply(), buildExampleList(), buildFileList(), buildGroupListFiltered(), Config::checkAndCorrect(), DocParser::checkArgumentName(), checkFileName(), checkList(), checkPageRelations(), checkPngResult(), DocParser::checkRetvalName(), DocParser::checkUnOrMultipleDocumentedParams(), classInheritedProtectionLevel(), TemplateContextImpl::closeSubIndex(), codifyLines(), computeClassRelations(), computePageRelations(), computeTemplateClassRelations(), computeVerifiedDotPath(), config_err(), config_term(), config_warn(), configFileToString(), configStringRecode(), convertCppComments(), DotFilePatcher::convertMapFile(), convertMapFile(), ConfigEnum::convertStrToVal(), ConfigInt::convertStrToVal(), ConfigBool::convertStrToVal(), copyExtraFiles(), copyFile(), copyLatexStyleSheet(), copyLogo(), ResourceMgr::copyResourceAs(), copyStyleSheet(), MemberList::countDecMembers(), createCroppedEPS(), createCroppedPDF(), createDVIFile(), createEPSbboxFile(), createOutputDirectory(), PerlModGenerator::createOutputFile(), createPNG(), createPostscriptFile(), HtmlHelp::Private::createProjectFile(), DotManager::createRunner(), createSubDirs(), createSVGFromPDF(), createSVGFromPDFviaInkscape(), DocSymbol::decodeSymbol(), DocParser::defaultHandleTitleAndSize(), DocParser::defaultHandleToken(), DocAnchor::DocAnchor(), DocCite::DocCite(), DocEmoji::DocEmoji(), DocHtmlCaption::DocHtmlCaption(), DocLink::DocLink(), DocRef::DocRef(), dumpDocNodeList(), elemIsVisible(), encodeForOutput(), DocGroup::enterCompound(), DocParser::errorHandleDefaultToken(), extractBoundingBox(), fileToString(), filterMemberDocumentation(), DocParser::findAndCopyImage(), findClassRelation(), findDefineDocumentation(), findDirDocumentation(), findEnumDocumentation(), findGlobalMember(), findInheritedTemplateInstances(), FlowChart::findLabel(), findMainPage(), findMember(), findMemberLink(), DocTokenizer::findSections(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsedTemplateInstances(), findUsingDeclarations(), VhdlDocGen::findVhdlClass(), generateClassMemberLink(), generateClassOrGlobalLink(), generateConceptDocs(), generateConfigFile(), generateDEF(), generateDocsForClassList(), generateExampleDocs(), generateFileDocs(), generateFileSources(), generateFormula(), generateFunctionLink(), FormulaManager::generateImages(), generateMemberLink(), generateNamespaceClassDocs(), generateNamespaceConceptDocs(), generateNamespaceDocs(), generateOutput(), CitationManager::generatePage(), generatePageDocs(), generatePHPVariableLink(), generateTemplateFiles(), generateXML(), generateXMLForClass(), generateXMLForConcept(), generateXMLForDir(), generateXMLForFile(), generateXMLForGroup(), generateXMLForNamespace(), generateXMLForPage(), TemplateContextImpl::get(), DotGfxHierarchyTable::getBaseName(), getCurrentDateTime(), getDefs(), FilterCache::getFileContentsPipe(), getLink(), getLinkInScope(), getMscImageMapFromFile(), ExpressionParser::getNextToken(), MemberDefImpl::getOutputFileBase(), getResolvedNamespace(), DocParser::handleAnchor(), DocPara::handleCite(), DocPara::handleCommand(), handleCommentBlock(), DocPara::handleEmoji(), handleExample(), DocPara::handleFile(), handleFileInfo(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlStartTag(), DocParser::handleImage(), DocPara::handleInclude(), DocPara::handleIncludeOperator(), DocParser::handleInternalRef(), DocPara::handleLink(), DocParser::handleLinkedWord(), DocPara::handleRef(), DocPara::handleSection(), DocPara::handleShowDate(), DocParser::handleStyleArgument(), DocParser::handleStyleLeave(), handleToc(), DocParser::handleUnclosedStyleCommands(), hasNonReferenceSuperClassRec(), ConfigImpl::init(), DocbookGenerator::init(), HtmlGenerator::init(), LatexGenerator::init(), ManGenerator::init(), RTFGenerator::init(), FormulaManager::initFromRepository(), DocSets::initialize(), EclipseHelp::initialize(), HtmlHelpRecoder::initialize(), HtmlHelp::initialize(), PlantumlManager::insert(), CitationManager::insertCrossReferencesForBibFile(), GroupDefImpl::insertMember(), FileDefImpl::insertMember(), NamespaceDefImpl::insertMember(), ClassDefImpl::insertTemplateInstance(), ClassDefImpl::internalInsertMember(), ClassDefImpl::isBaseClass(), ClassDefImpl::isSubClass(), VhdlDocGen::isSubClass(), TemplateEngine::Private::loadByName(), loadExtensions(), Htags::loadFilemap(), loadStylesheet(), minClassDistance(), TemplateContextImpl::openSubIndex(), PerlModDocVisitor::operator()(), DocbookDocVisitor::operator()(), HtmlDocVisitor::operator()(), LatexDocVisitor::operator()(), RTFDocVisitor::operator()(), PrintDocVisitor::operator()(), CondParser::parse(), ConfigImpl::parse(), DocInclude::parse(), DocIncOperator::parse(), DocIndexEntry::parse(), DocDotFile::parse(), DocMscFile::parse(), DocDiaFile::parse(), DocHRef::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocSection::parse(), DocSecRefItem::parse(), DocSecRefList::parse(), DocHtmlList::parse(), DocPara::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocText::parse(), DocRoot::parse(), DocLink::parse(), DocParamList::parse(), TemplateParser::parse(), CCodeParser::parseCode(), FortranCodeParser::parseCode(), PythonCodeParser::parseCode(), VHDLCodeParser::parseCode(), LexCodeParser::parseCode(), SQLCodeParser::parseCode(), XMLCodeParser::parseCode(), CommentScanner::parseCommentBlock(), parseFile(), ExpressionParser::parseFilter(), ExpressionParser::parseIdentifier(), ExpressionParser::parseIdentifierOptionalArgs(), parseInput(), FortranOutlineParser::parseInput(), LexOutlineParser::parseInput(), MarkdownOutlineParser::parseInput(), PythonOutlineParser::parseInput(), COutlineParser::parseInput(), ExpressionParser::parseLiteral(), parseMain(), DocHtmlList::parseXml(), DocHtmlRow::parseXml(), popScope(), DotGraph::prepareDotFile(), RTFGenerator::preProcessFileInplace(), TemplateEngine::Private::printIncludeContext(), printlex(), printNavTree(), FlowChart::printNode(), Markdown::process(), DocParser::processCopyDoc(), Preprocessor::processFile(), processList(), processSection(), Markdown::processSpecialCommand(), processString(), pushBuffer(), pushScope(), DotRunner::readBoundingBox(), readCodeFragment(), readConfiguration(), readDir(), readFileOrDirectory(), readIncludeFile(), readInputFile(), readTagFile(), DocParser::readTextFileByName(), TemplateNodeCreate::render(), TemplateNodeFor::render(), TemplateNodeExtend::render(), TemplateNodeInclude::render(), TemplateNodeTree::renderChildren(), DotNode::renumberNodes(), resetPDFSize(), ExprAstVariable::resolve(), resolveClassNestingRelations(), rtfFormatBmkStr(), DotRunner::run(), DotFilePatcher::run(), runHtmlHelpCompiler(), runPlantumlContent(), runQHelpGenerator(), saveObjCContext(), scanner_abort(), setCallContextForVar(), setClassScope(), TemplateContextImpl::setEncoding(), setTranslator(), startCodeLine(), LayoutParser::startElement(), LayoutParser::startNavEntry(), OutputGenerator::startPlainFile(), stripClassName(), subrHandleCommentBlock(), Portable::system(), TemplateNodeBlock::TemplateNodeBlock(), TemplateNodeCloseSubIndex::TemplateNodeCloseSubIndex(), TemplateNodeCreate::TemplateNodeCreate(), TemplateNodeCycle::TemplateNodeCycle(), TemplateNodeEncoding::TemplateNodeEncoding(), TemplateNodeExtend::TemplateNodeExtend(), TemplateNodeFor::TemplateNodeFor(), TemplateNodeIf::TemplateNodeIf(), TemplateNodeInclude::TemplateNodeInclude(), TemplateNodeIndexEntry::TemplateNodeIndexEntry(), TemplateNodeMarkers::TemplateNodeMarkers(), TemplateNodeOpenSubIndex::TemplateNodeOpenSubIndex(), TemplateNodeRange::TemplateNodeRange(), TemplateNodeRepeat::TemplateNodeRepeat(), TemplateNodeResource::TemplateNodeResource(), TemplateNodeSet::TemplateNodeSet(), TemplateNodeTree::TemplateNodeTree(), TemplateNodeVariable::TemplateNodeVariable(), TemplateNodeWith::TemplateNodeWith(), testRTFOutput(), Trace::trace(), Trace::Trace(), transcodeCharacterBuffer(), transcodeCharacterStringToUTF8(), tryPath(), updateEPSBoundingBox(), updateLanguageMapping(), LayoutNavEntry::url(), usage(), version(), MemberDefImpl::virtualness(), MemberDefImpl::warnIfUndocumented(), MemberDefImpl::warnIfUndocumentedParams(), SearchIndexExternal::write(), ResourceMgr::writeCategory(), writeCombineScript(), writeDefaultLayoutFile(), writeDiaGraphFromFile(), DirDefImpl::writeDirectoryGraph(), writeDirTreeNode(), ClassDefImpl::writeDocumentationForInnerClasses(), writeDotGraphFromFile(), writeDotImageMapFromFile(), writeExceptionListImpl(), HtmlGenerator::writeExternalSearchPage(), ClassDiagram::writeFigure(), FlowChart::writeFlowChart(), DotGfxHierarchyTable::writeGraph(), GroupDefImpl::writeGroupGraph(), writeGroupTreeNode(), FileDefImpl::writeIncludedByGraph(), FileDefImpl::writeIncludeGraph(), ClassDefImpl::writeInheritanceGraph(), writeJavaScriptSearchIndex(), writeLatexMakefile(), writeMakeBat(), writeMscGraphFromFile(), writeMultiLineCodeLink(), writeObjCMethodCall(), VhdlDocGen::writeOverview(), PlantumlManager::writePlantUMLSource(), HtmlGenerator::writeSearchPage(), HtmlGenerator::writeStyleInfo(), writeTagFile(), and Trace::~Trace().
qPrint() [2/3]
const char * qPrint (const QCString & s) inline
Definition at line 618 of file qcstring.h.
{
  if (!s.isEmpty()) return s.data(); else return "";
}
References QCString::data(), and QCString::isEmpty().
qPrint() [3/3]
const char * qPrint (const std::string & s) inline
Definition at line 623 of file qcstring.h.
{
  return s.c_str();
}
qstrcmp()
int qstrcmp (const char * str1, const char * str2) inline
Definition at line 82 of file qcstring.h.
{ return (str1 && str2) ? strcmp(str1,str2) :     // both non-empty
         (qisempty(str1) && qisempty(str2)) ? 0 : // both empty
         qisempty(str1) ? -1 : 1;                 // one empty, other non-empty
}
References qisempty().
Referenced by convertMapFile(), KeywordHash::find(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), and readConfiguration().
qstrcpy()
char * qstrcpy (char * dst, const char * src) inline
Definition at line 71 of file qcstring.h.
{ return src ? strcpy(dst, src) : 0; }
Referenced by clearBlock(), SymbolResolver::Private::getResolvedSymbolRec(), SymbolResolver::Private::getResolvedTypeRec(), and substitute().
qstrdup()
char * qstrdup (const char * str)
Definition at line 420 of file qcstring.cpp.
{
    if ( !str )
        return 0;
    char *dst = new char[qstrlen(str)+1];
    return strcpy( dst, str );
}
References qstrlen().
qstricmp() [1/4]
int qstricmp (const char * str1, const char * str2)
Definition at line 438 of file qcstring.cpp.
{
    if ( !s1 || !s2 )
    {
      return s1 == s2 ? 0 : static_cast<int>(s2 - s1);
    }
    int res;
    char c;
    for ( ; !(res = ((c=toLowerChar(*s1)) - toLowerChar(*s2))); s1++, s2++ )
    {
      if ( !c )                         // strings are equal
        break;
    }
    return res;
}
References toLowerChar().
Referenced by buildDirectories(), compareDirDefs(), compareFileDefs(), compareString(), VhdlDocGen::findAllArchitectures(), DocGroup::findExistingGroup(), FlowChart::findLabel(), VhdlDocGen::findVhdlClass(), genericCompareMembers(), mainPageHasOwnTitle(), DirDefImpl::matchPath(), parseInput(), qstricmp(), readConfiguration(), searchInputFiles(), FileDefImpl::sortMemberLists(), GroupDefImpl::sortMemberLists(), NamespaceDefImpl::sortMemberLists(), stripFromPath(), transcodeCharacterBuffer(), transcodeCharacterStringToUTF8(), writeColumn(), FlowChart::writeFlowLinks(), ClassDefImpl::writeIncludeFilesForSlice(), writeIndex(), and VhdlDocGen::writeProcedureProto().
qstricmp() [2/4]
int qstricmp (const char * str1, const QCString & str2) inline
Definition at line 640 of file qcstring.h.
{
  return qstricmp(str1,str2.data());
}
References QCString::data(), and qstricmp().
qstricmp() [3/4]
int qstricmp (const QCString & str1, const char * str2) inline
Definition at line 635 of file qcstring.h.
{
  return qstricmp(str1.data(),str2);
}
References QCString::data(), and qstricmp().
qstricmp() [4/4]
int qstricmp (const QCString & str1, const QCString & str2) inline
Definition at line 645 of file qcstring.h.
{
  return qstricmp(str1.data(),str2.data());
}
References QCString::data(), and qstricmp().
qstrlen()
uint qstrlen (const char * str) inline
Definition at line 65 of file qcstring.h.
{ return str ? static_cast<uint>(strlen(str)) : 0; }
Referenced by clearBlock(), QCString::contains(), QCString::find(), DocParser::findDocsForMemberOrCompound(), QCString::findRev(), getArg(), QCString::insert(), VhdlDocGen::prepareComment(), qstrdup(), substituteKeywords(), writeClassTreeInsideNamespaceElement(), MemberDefImpl::writeMemberDocSimple(), writeNamespaceIndex(), and writeNamespaceTreeElement().
qstrncmp()
int qstrncmp (const char * str1, const char * str2, size_t len) inline
Definition at line 91 of file qcstring.h.
{ return (str1 && str2) ? strncmp(str1,str2,len) :  // both non-empty
         (qisempty(str1) && qisempty(str2)) ? 0 :   // both empty
         qisempty(str1) ? -1 : 1;                   // one empty other non-empty
}
References qisempty().
Referenced by QCString::contains(), convertMapFile(), extractCopyDocId(), Markdown::findEmphasisChar(), Markdown::findEndOfLine(), QCString::findRev(), getConvertLatexMacro(), isExplicitPage(), isNewline(), Markdown::process(), Markdown::processBlocks(), Markdown::processNmdash(), Markdown::processQuotations(), Markdown::processSpecialCommand(), readSVGSize(), removeIdsAndMarkers(), skipToEndMarker(), stripLeadingAndTrailingEmptyLines(), stripTrailingWhiteSpace(), substitute(), and substituteKeywords().
qstrncpy()
char * qstrncpy (char * dst, const char * src, size_t len)
Definition at line 428 of file qcstring.cpp.
{
    if ( !src )
        return 0;
    strncpy( dst, src, len );
    if ( len > 0 )
        dst[len-1] = '\0';
    return dst;
}
Referenced by do_warn().
qstrnicmp() [1/4]
int qstrnicmp (const char * str1, const char * str2, size_t len)
Definition at line 454 of file qcstring.cpp.
{
    if ( !s1 || !s2 )
    {
      return static_cast<int>(s2 - s1);
    }
    for ( ; len--; s1++, s2++ )
    {
        char c = toLowerChar(*s1);
        int res = c-toLowerChar(*s2);
        if ( res!=0 ) // strings are not equal
            return res;
        if ( c==0 ) // strings are equal
            break;
    }
    return 0;
}
References toLowerChar().
Referenced by QCString::contains(), QCString::find(), QCString::findRev(), and qstrnicmp().
qstrnicmp() [2/4]
int qstrnicmp (const char * str1, const QCString & str2, size_t len) inline
Definition at line 655 of file qcstring.h.
{
  return qstrnicmp(str1,str2.data(),len);
}
References QCString::data(), and qstrnicmp().
qstrnicmp() [3/4]
int qstrnicmp (const QCString & str1, const char * str2, size_t len) inline
Definition at line 650 of file qcstring.h.
{
  return qstrnicmp(str1.data(),str2,len);
}
References QCString::data(), and qstrnicmp().
qstrnicmp() [4/4]
int qstrnicmp (const QCString & str1, const QCString & str2, size_t len) inline
Definition at line 660 of file qcstring.h.
{
  return qstrnicmp(str1.data(),str2.data(),len);
}
References QCString::data(), and qstrnicmp().
substitute() [1/4]
QCString substitute (const QCString & s, char srcChar, char dstChar) inline
Definition at line 673 of file qcstring.h.
{
  std::string ss = s.str();
  std::replace(ss.begin(),ss.end(),srcChar,dstChar);
  return QCString(ss);
}
References QCString::str().
substitute() [2/4]
QCString substitute (const QCString & s, const QCString & src, const QCString & dst, int skip_seq)
substitute all occurrences of src in s by dst, but skip each consecutive sequence of src where the number consecutive src matches skip_seq; if skip_seq is negative, skip any number of consecutive src
Definition at line 514 of file qcstring.cpp.
{
  if (s.isEmpty() || src.isEmpty()) return s;
  const char *p, *q;
  int srcLen = src.length();
  int dstLen = dst.length();
  int resLen;
  if (srcLen!=dstLen)
  {
    int count;
    for (count=0, p=s.data(); (q=strstr(p,src.data()))!=0; p=q+srcLen) count++;
    resLen = s.length()+count*(dstLen-srcLen);
  }
  else // result has same size as s
  {
    resLen = s.length();
  }
  QCString result(resLen+1);
  char *r;
  for (r=result.rawData(), p=s.data(); (q=strstr(p,src.data()))!=0; p=q+srcLen)
  {
    // search a consecutive sequence of src
    int seq = 0, skip = 0;
    if (skip_seq)
    {
      for (const char *n=q+srcLen; qstrncmp(n,src.data(),srcLen)==0; seq=1+skip, n+=srcLen)
        ++skip; // number of consecutive src after the current one
      // verify the allowed number of consecutive src to skip
      if (skip_seq > 0 && skip_seq != seq)
        seq = skip = 0;
    }
    // skip a consecutive sequence of src when necessary
    int l = static_cast<int>((q + seq * srcLen)-p);
    memcpy(r,p,l);
    r+=l;
    if (skip)
    {
      // skip only the consecutive src found after the current one
      q += skip * srcLen;
      // the next loop will skip the current src, aka (p=q+srcLen)
      continue;
    }
    if (dstLen>0) memcpy(r,dst.data(),dstLen);
    r+=dstLen;
  }
  qstrcpy(r,p);
  result.resize(static_cast<int>(strlen(result.data())+1));
  //printf("substitute(%s,%s,%s)->%s\n",s,src,dst,result.data());
  return result;
}
References QCString::data(), QCString::isEmpty(), QCString::length(), qstrcpy(), qstrncmp(), QCString::rawData(), and QCString::resize().
substitute() [3/4]
QCString substitute (const QCString & str, const char * find, const char * replace) inline
Definition at line 667 of file qcstring.h.
{
  return substitute(str,QCString(find),QCString(replace));
}
References substitute().
substitute() [4/4]
QCString substitute (const QCString & str, const QCString & find, const QCString & replace)
substitute all occurrences of src in s by dst
Definition at line 473 of file qcstring.cpp.
{
  if (s.isEmpty() || src.isEmpty()) return s;
  const char *p, *q;
  int srcLen = src.length();
  int dstLen = dst.length();
  int resLen;
  if (srcLen!=dstLen)
  {
    int count;
    for (count=0, p=s.data(); (q=strstr(p,src.data()))!=0; p=q+srcLen) count++;
    resLen = s.length()+count*(dstLen-srcLen);
  }
  else // result has same size as s
  {
    resLen = s.length();
  }
  QCString result(resLen+1);
  char *r;
  for (r=result.rawData(), p=s.data(); (q=strstr(p,src.data()))!=0; p=q+srcLen)
  {
    int l = static_cast<int>(q-p);
    memcpy(r,p,l);
    r+=l;
    if (dstLen>0) memcpy(r,dst.data(),dstLen);
    r+=dstLen;
  }
  if (r)
  {
    qstrcpy(r,p);
  }
  //printf("substitute(%s,%s,%s)->%s\n",s,src,dst,result.data());
  return result;
}
References QCString::data(), QCString::isEmpty(), QCString::length(), qstrcpy(), and QCString::rawData().
Referenced by abbreviate(), addEnumValuesToEnums(), FlowChart::addFlowChart(), addFrom(), addMemberFunction(), addModule(), addPageToContext(), Markdown::addStrEscapeUtf8Nbsp(), addVariable(), addVariableToClass(), FilterNoWrap::apply(), buildListOfUsingDecls(), buildNamespaceList(), DocParser::checkUnOrMultipleDocumentedParams(), convertFileId2Var(), ResourceMgr::copyResourceAs(), Portable::correct_path(), MemberDefImpl::displayDefinition(), RTFGenerator::endIndexSection(), field2URL(), findDirDocumentation(), DocParser::findDocsForMemberOrCompound(), findGlobalMember(), findGroupScope(), findMember(), findUsingDeclarations(), findUsingDirectives(), fixSpaces(), format_warn(), generateClassOrGlobalLink(), RefList::generatePage(), FTVHelp::generateTreeViewScripts(), VhdlDocGen::getClassName(), getDefsOld(), DocPara::handleStartCode(), InheritedMemberInfoContext::Private::id(), linkToText(), makeDisplayName(), matchExcludedSymbols(), Markdown::process(), Markdown::processLink(), processTagLessClasses(), replaceAliasArguments(), resolveRef(), DotFilePatcher::run(), selectBlock(), SearchIndex::setCurrentDoc(), substitute(), substituteHtmlKeywords(), substituteLatexKeywords(), Portable::system(), ConfigImpl::takeStartComment(), ConfigImpl::takeStoreRepl(), ConfigImpl::takeUserComment(), unescapeCRef(), warn_line(), writeAlphabeticalClassList(), writeColumn(), MemberDefImpl::writeDeclaration(), MemberList::writeDeclarations(), writeDefaultLayoutFile(), MemberDefImpl::writeDocumentation(), HtmlGenerator::writeNavigationPath(), HtmlGenerator::writeSearchData(), HtmlGenerator::writeSearchPage(), and VhdlDocGen::writeVHDLTypeDocumentation().
toStdString()
std::string toStdString (const QCString & s) inline
Definition at line 628 of file qcstring.h.
{
  return s.str();
}
References QCString::str().
Referenced by SectionRefs::add(), expandExpression(), and replaceFunctionMacro().