Doxygen: DocbookCodeGenerator Class Reference
DocbookCodeGenerator Class Reference
#include <docbookgen.h>
Public Member Functions
DocbookCodeGenerator (TextStream &t)
OutputType type () const override
void codify (const QCString &text) override
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip) override
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &) override
void startCodeLine (bool) override
void endCodeLine () override
void startFontClass (const QCString &colorClass) override
void endFontClass () override
void writeCodeAnchor (const QCString &) override
void writeLineNumber (const QCString &extRef, const QCString &compId, const QCString &anchorId, int l, bool writeLineAnchor) override
void startCodeFragment (const QCString &style) override
void endCodeFragment (const QCString &style) override
void setRelativePath (const QCString &path)
void setSourceFileName (const QCString &sourceFileName)
QCString sourceFileName ()
void finish ()
Public Member Functions inherited from CodeOutputInterface
CodeOutputInterface ()=default
CodeOutputInterface (const CodeOutputInterface &)=delete
CodeOutputInterface & operator= (const CodeOutputInterface &)=delete
virtual ~CodeOutputInterface ()=default
virtual OutputType type () const =0
virtual int id () const
Identifier for the output file.
virtual void setId (int id)
virtual void setEnabled (bool e)
virtual bool isEnabled () const
virtual void codify (const QCString &s)=0
virtual void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)=0
virtual void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)=0
virtual void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)=0
virtual void startCodeLine (bool hasLineNumbers)=0
virtual void endCodeLine ()=0
virtual void startFontClass (const QCString &clsName)=0
virtual void endFontClass ()=0
virtual void writeCodeAnchor (const QCString &name)=0
virtual void setCurrentDoc (const Definition *context, const QCString &anchor, bool isSourceFile)
virtual void addWord (const QCString &word, bool hiPriority)
virtual void startCodeFragment (const QCString &style)=0
virtual void endCodeFragment (const QCString &style)=0
Private Member Functions
void writeCodeLinkLine (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip, bool)
Private Attributes
TextStream & m_t
QCString m_refId
QCString m_external
int m_lineNumber = -1
int m_col = 0
bool m_insideCodeLine = false
bool m_insideSpecialHL = false
QCString m_relPath
QCString m_sourceFileName
Detailed Description
Definition at line 44 of file docbookgen.h.
Constructor & Destructor Documentation
DocbookCodeGenerator()
DocbookCodeGenerator::DocbookCodeGenerator (TextStream & t)
Definition at line 147 of file docbookgen.cpp.
                                                        : m_t(t)
{
}
Member Function Documentation
codify()
void DocbookCodeGenerator::codify (const QCString & s) override virtual
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 151 of file docbookgen.cpp.
{
  Docbook_DB(("(codify \"%s\")\n",text));
  writeDocbookCodeString(m_t,text,m_col);
}
References Docbook_DB, m_col, m_t, and writeDocbookCodeString().
Referenced by writeLineNumber().
endCodeFragment()
void DocbookCodeGenerator::endCodeFragment (const QCString & style) override virtual
Ends a block of code
Implements CodeOutputInterface.
Definition at line 266 of file docbookgen.cpp.
{
DB_GEN_C1(m_t)
  //endCodeLine checks is there is still an open code line, if so closes it.
  endCodeLine();
  m_t << "</programlisting>";
}
References DB_GEN_C1, endCodeLine(), and m_t.
endCodeLine()
void DocbookCodeGenerator::endCodeLine () override virtual
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 195 of file docbookgen.cpp.
{
  if (m_insideCodeLine) m_t << "\n";
  Docbook_DB(("(endCodeLine)\n"));
  m_lineNumber = -1;
  m_refId.resize(0);
  m_external.resize(0);
  m_insideCodeLine=FALSE;
}
References Docbook_DB, FALSE, m_external, m_insideCodeLine, m_lineNumber, m_refId, m_t, and QCString::resize().
Referenced by endCodeFragment(), and finish().
endFontClass()
void DocbookCodeGenerator::endFontClass () override virtual
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 212 of file docbookgen.cpp.
{
  Docbook_DB(("(endFontClass)\n"));
  m_t << "</emphasis>"; // non DocBook
  m_insideSpecialHL=FALSE;
}
References Docbook_DB, FALSE, m_insideSpecialHL, and m_t.
finish()
void DocbookCodeGenerator::finish ()
Definition at line 255 of file docbookgen.cpp.
{
  endCodeLine();
}
References endCodeLine().
setRelativePath()
void DocbookCodeGenerator::setRelativePath (const QCString & path) inline
Definition at line 69 of file docbookgen.h.
{ m_relPath = path; }
References m_relPath.
Referenced by DocbookGenerator::startFile().
setSourceFileName()
void DocbookCodeGenerator::setSourceFileName (const QCString & sourceFileName) inline
Definition at line 70 of file docbookgen.h.
{ m_sourceFileName = sourceFileName; }
References m_sourceFileName, and sourceFileName().
Referenced by DocbookGenerator::endFile(), and DocbookGenerator::startFile().
sourceFileName()
QCString DocbookCodeGenerator::sourceFileName () inline
Definition at line 71 of file docbookgen.h.
{ return m_sourceFileName; }
References m_sourceFileName.
Referenced by DocbookGenerator::endFile(), and setSourceFileName().
startCodeFragment()
void DocbookCodeGenerator::startCodeFragment (const QCString & style) override virtual
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 260 of file docbookgen.cpp.
{
DB_GEN_C1(m_t)
  m_t << "<programlisting linenumbering=\"unnumbered\">";
}
References DB_GEN_C1, and m_t.
startCodeLine()
void DocbookCodeGenerator::startCodeLine (bool) override virtual
Implements CodeOutputInterface.
Definition at line 188 of file docbookgen.cpp.
{
  Docbook_DB(("(startCodeLine)\n"));
  m_insideCodeLine=TRUE;
  m_col=0;
}
References Docbook_DB, m_col, m_insideCodeLine, and TRUE.
startFontClass()
void DocbookCodeGenerator::startFontClass (const QCString & clsName) override virtual
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 205 of file docbookgen.cpp.
{
  Docbook_DB(("(startFontClass)\n"));
  m_t << "<emphasis role=\"" << colorClass << "\">";
  m_insideSpecialHL=TRUE;
}
References Docbook_DB, m_insideSpecialHL, m_t, and TRUE.
type()
OutputType DocbookCodeGenerator::type () const inline override virtual
Implements CodeOutputInterface.
Definition at line 49 of file docbookgen.h.
{ return OutputType::Docbook; }
writeCodeAnchor()
void DocbookCodeGenerator::writeCodeAnchor (const QCString & name) override virtual
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 219 of file docbookgen.cpp.
{
  Docbook_DB(("(writeCodeAnchor)\n"));
}
References Docbook_DB.
writeCodeLink()
void DocbookCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) override virtual
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 157 of file docbookgen.cpp.
{
  Docbook_DB(("(writeCodeLink)\n"));
  writeDocbookLink(m_t,ref,file,anchor,name,tooltip);
  m_col+=name.length();
}
References Docbook_DB, QCString::length(), m_col, m_t, and writeDocbookLink().
Referenced by writeLineNumber().
writeCodeLinkLine()
void DocbookCodeGenerator::writeCodeLinkLine (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip, bool writeLineAnchor) private
Definition at line 167 of file docbookgen.cpp.
{
  Docbook_DB(("(writeCodeLinkLine)\n"));
  if (!writeLineAnchor) return;
  m_t << "<anchor xml:id=\"_" << stripExtensionGeneral(stripPath(file),".xml");
  m_t << "_1l";
  writeDocbookString(m_t,name);
  m_t << "\"/>";
  m_col+=name.length();
}
References Docbook_DB, QCString::length(), m_col, m_t, stripExtensionGeneral(), stripPath(), and writeDocbookString().
Referenced by writeLineNumber().
writeLineNumber()
void DocbookCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) override virtual
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 224 of file docbookgen.cpp.
{
  Docbook_DB(("(writeLineNumber)\n"));
  m_insideCodeLine = TRUE;
  if (Config_getBool(SOURCE_BROWSER))
  {
    QCString lineNumber;
    lineNumber.sprintf("%05d",l);
    if (!m_sourceFileName.isEmpty())
    {
      writeCodeLinkLine(CodeSymbolType::Default,ref,m_sourceFileName,anchor,lineNumber,QCString(),writeLineAnchor);
    }
    if (!fileName.isEmpty())
    {
      writeCodeLink(CodeSymbolType::Default,ref,fileName,anchor,lineNumber,QCString());
    }
    else
    {
      codify(lineNumber);
    }
    m_t << " ";
  }
  else
  {
    m_t << l << " ";
  }
  m_col=0;
}
References codify(), Config_getBool, Docbook_DB, QCString::isEmpty(), m_col, m_insideCodeLine, m_sourceFileName, m_t, QCString::sprintf(), TRUE, writeCodeLink(), and writeCodeLinkLine().
writeTooltip()
void DocbookCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) override virtual
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 181 of file docbookgen.cpp.
{
  Docbook_DB(("(writeToolTip)\n"));
}
References Docbook_DB.
Member Data Documentation
m_col
int DocbookCodeGenerator::m_col = 0 private
Definition at line 83 of file docbookgen.h.
Referenced by codify(), startCodeLine(), writeCodeLink(), writeCodeLinkLine(), and writeLineNumber().
m_external
QCString DocbookCodeGenerator::m_external private
Definition at line 81 of file docbookgen.h.
Referenced by endCodeLine().
m_insideCodeLine
bool DocbookCodeGenerator::m_insideCodeLine = false private
Definition at line 84 of file docbookgen.h.
Referenced by endCodeLine(), startCodeLine(), and writeLineNumber().
m_insideSpecialHL
bool DocbookCodeGenerator::m_insideSpecialHL = false private
Definition at line 85 of file docbookgen.h.
Referenced by endFontClass(), and startFontClass().
m_lineNumber
int DocbookCodeGenerator::m_lineNumber = -1 private
Definition at line 82 of file docbookgen.h.
Referenced by endCodeLine().
m_refId
QCString DocbookCodeGenerator::m_refId private
Definition at line 80 of file docbookgen.h.
Referenced by endCodeLine().
m_relPath
QCString DocbookCodeGenerator::m_relPath private
Definition at line 86 of file docbookgen.h.
Referenced by setRelativePath().
m_sourceFileName
QCString DocbookCodeGenerator::m_sourceFileName private
Definition at line 87 of file docbookgen.h.
Referenced by setSourceFileName(), sourceFileName(), and writeLineNumber().
m_t
TextStream& DocbookCodeGenerator::m_t private
Definition at line 79 of file docbookgen.h.
Referenced by codify(), endCodeFragment(), endCodeLine(), endFontClass(), startCodeFragment(), startFontClass(), writeCodeLink(), writeCodeLinkLine(), and writeLineNumber().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/docbookgen.h
/home/runner/work/doxygen/doxygen/src/docbookgen.cpp