Doxygen: /home/runner/work/doxygen/doxygen/src/classdef.cpp File Reference
classdef.cpp File Reference
#include <cstdio>
#include <algorithm>
#include "types.h"
#include "classdef.h"
#include "classlist.h"
#include "entry.h"
#include "doxygen.h"
#include "membername.h"
#include "message.h"
#include "config.h"
#include "util.h"
#include "diagram.h"
#include "language.h"
#include "htmlhelp.h"
#include "example.h"
#include "outputlist.h"
#include "dot.h"
#include "dotclassgraph.h"
#include "dotrunner.h"
#include "defargs.h"
#include "debug.h"
#include "docparser.h"
#include "searchindex.h"
#include "vhdldocgen.h"
#include "layout.h"
#include "arguments.h"
#include "memberlist.h"
#include "groupdef.h"
#include "filedef.h"
#include "namespacedef.h"
#include "membergroup.h"
#include "definitionimpl.h"
#include "symbolresolver.h"
#include "fileinfo.h"
Classes
class ClassDefImpl
Implementation of the ClassDef interface.
class ClassDefAliasImpl
class ClassDefImpl::IMPL
Private data associated with a ClassDef object.
Functions
static QCString makeQualifiedNameWithTemplateParameters (const ClassDef *cd, const ArgumentLists *actualParams, uint *actualParamIndex)
static QCString makeDisplayName (const ClassDef *cd, bool includeScope)
ClassDefMutable * createClassDef (const QCString &fileName, int startLine, int startColumn, const QCString &name, ClassDef::CompoundType ct, const QCString &ref, const QCString &fName, bool isSymbol, bool isJavaEnum)
Factory method to create a new ClassDef object.
ClassDef * createClassDefAlias (const Definition *newScope, const ClassDef *cd)
static void writeInheritanceSpecifier (OutputList &ol, const BaseClassDef &bcd)
static void searchTemplateSpecs (const Definition *d, ArgumentLists &result, QCString &name, SrcLangExt lang)
static bool hasNonReferenceSuperClassRec (const ClassDef *cd, int level)
static bool isStandardFunc (const MemberDef *md)
ClassDef * toClassDef (Definition *d)
ClassDef * toClassDef (DefinitionMutable *md)
const ClassDef * toClassDef (const Definition *d)
ClassDefMutable * toClassDefMutable (Definition *d)
ClassDef * getClass (const QCString &n)
bool classHasVisibleRoot (const BaseClassList &bcl)
bool classHasVisibleChildren (const ClassDef *cd)
bool classVisibleInIndex (const ClassDef *cd)
int minClassDistance (const ClassDef *cd, const ClassDef *bcd, int level)
Protection classInheritedProtectionLevel (const ClassDef *cd, const ClassDef *bcd, Protection prot, int level)
Function Documentation
classHasVisibleChildren()
bool classHasVisibleChildren (const ClassDef * cd)
Definition at line 5099 of file classdef.cpp.
{
  BaseClassList bcl;
  if (cd->getLanguage()==SrcLangExt_VHDL) // reverse baseClass/subClass relation
  {
    if (cd->baseClasses().empty()) return FALSE;
    bcl=cd->baseClasses();
  }
  else
  {
    if (cd->subClasses().empty()) return FALSE;
    bcl=cd->subClasses();
  }
  for (const auto &bcd : bcl)
  {
    if (bcd.classDef->isVisibleInHierarchy())
    {
      return TRUE;
    }
  }
  return FALSE;
}
References ClassDef::baseClasses(), FALSE, Definition::getLanguage(), SrcLangExt_VHDL, ClassDef::subClasses(), and TRUE.
Referenced by NestingNodeContext::Private::addClasses(), writeClassTreeForList(), and writeClassTreeToOutput().
classHasVisibleRoot()
bool classHasVisibleRoot (const BaseClassList & bcl)
Definition at line 5088 of file classdef.cpp.
{
  for (const auto &bcd : bcl)
  {
    const ClassDef *cd=bcd.classDef;
    if (cd->isVisibleInHierarchy()) return true;
    if (classHasVisibleRoot(cd->baseClasses())) return true;
  }
  return false;
}
References ClassDef::baseClasses(), classHasVisibleRoot(), and ClassDef::isVisibleInHierarchy().
Referenced by NestingContext::Private::addClassHierarchy(), DotGfxHierarchyTable::addClassList(), NestingContext::Private::addDerivedClasses(), DotGfxHierarchyTable::addHierarchy(), classHasVisibleRoot(), countClassesInTreeList(), writeClassTreeForList(), and writeClassTreeToOutput().
classInheritedProtectionLevel()
Protection classInheritedProtectionLevel (const ClassDef * cd, const ClassDef * bcd, Protection prot, int level)
Definition at line 5159 of file classdef.cpp.
{
  if (bcd->categoryOf()) // use class that is being extended in case of
    // an Objective-C category
  {
    bcd=bcd->categoryOf();
  }
  if (cd==bcd)
  {
    goto exit;
  }
  if (level==256)
  {
    err("Internal inconsistency: found class %s seem to have a recursive "
        "inheritance relation! Please send a bug report to doxygen@gmail.com\n",qPrint(cd->name()));
  }
  else if (prot!=Protection::Private)
  {
    for (const auto &bcdi : cd->baseClasses())
    {
      Protection baseProt = classInheritedProtectionLevel(bcdi.classDef,bcd,bcdi.prot,level+1);
      if (baseProt==Protection::Private)        prot=Protection::Private;
      else if (baseProt==Protection::Protected) prot=Protection::Protected;
    }
  }
exit:
  //printf("classInheritedProtectionLevel(%s,%s)=%d\n",qPrint(cd->name()),qPrint(bcd->name()),prot);
  return prot;
}
References ClassDef::baseClasses(), ClassDef::categoryOf(), classInheritedProtectionLevel(), err(), Definition::name(), Private, Protected, and qPrint().
Referenced by classInheritedProtectionLevel().
classVisibleInIndex()
bool classVisibleInIndex (const ClassDef * cd)
Definition at line 5124 of file classdef.cpp.
{
  bool allExternals = Config_getBool(ALLEXTERNALS);
  return (allExternals && cd->isLinkable()) || cd->isLinkableInProject();
}
References Config_getBool, ClassDef::isLinkable(), and ClassDef::isLinkableInProject().
Referenced by NestingContext::Private::addClass(), and writeClassTree().
createClassDef()
ClassDefMutable * createClassDef (const QCString & fileName, int startLine, int startColumn, const QCString & name, ClassDef::CompoundType ct, const QCString & ref, const QCString & fName, bool isSymbol, bool isJavaEnum)
Factory method to create a new ClassDef object.
Definition at line 364 of file classdef.cpp.
{
  return new ClassDefImpl(fileName,startLine,startColumn,name,ct,ref,fName,isSymbol,isJavaEnum);
}
Referenced by addClassToContext(), createTagLessInstance(), findClassRelation(), findUsedClassesForClass(), and findUsingDeclarations().
createClassDefAlias()
ClassDef * createClassDefAlias (const Definition * newScope, const ClassDef * cd)
Definition at line 587 of file classdef.cpp.
{
  ClassDef *acd = new ClassDefAliasImpl(newScope,cd);
  //printf("cd name=%s localName=%s qualifiedName=%s qualifiedNameWith=%s displayName()=%s\n",
  //    qPrint(acd->name()),qPrint(acd->localName()),qPrint(acd->qualifiedName()),
  //    qPrint(acd->qualifiedNameWithTemplateParameters()),qPrint(acd->displayName()));
  return acd;
}
Referenced by resolveClassNestingRelations().
getClass()
ClassDef * getClass (const QCString & n)
Get a class definition given its name. Returns 0 if the class is not found.
Definition at line 5082 of file classdef.cpp.
{
  if (n.isEmpty()) return 0;
  return Doxygen::classLinkedMap->find(n);
}
References Doxygen::classLinkedMap, LinkedMap< T, Hash, KeyEqual, Map >::find(), and QCString::isEmpty().
Referenced by buildScopeFromQualifiedName(), extractNamespaceName(), findClassWithinClassContext(), findEnumDocumentation(), findEnums(), findInheritedTemplateInstances(), findMember(), findUsedTemplateInstances(), generateClassOrGlobalLink(), generateMemberLink(), MemberDefImpl::getClassDefOfAnonymousType(), getClassMutable(), getScopeDefs(), getTemplateArgumentsFromName(), DocParser::handleLinkedWord(), if(), insertTemplateSpecifierInScope(), MemberDefImpl::isDocumentedFriendClass(), SymbolResolver::resolveClass(), resolveLink(), resolveRef(), setCallContextForVar(), stripTemplateSpecifiersFromScope(), and MemberDefImpl::writeDeclaration().
hasNonReferenceSuperClassRec()
static bool hasNonReferenceSuperClassRec (const ClassDef * cd, int level) static
Definition at line 3244 of file classdef.cpp.
{
  bool found=!cd->isReference() && cd->isLinkableInProject() && !cd->isHidden();
  if (found)
  {
    return TRUE; // we're done if this class is not a reference
  }
  for (const auto &ibcd : cd->subClasses())
  {
    const ClassDef *bcd=ibcd.classDef;
    if (level>256)
    {
      err("Possible recursive class relation while inside %s and looking for base class %s\n",qPrint(cd->name()),qPrint(bcd->name()));
      return FALSE;
    }
    // recurse into the super class branch
    found = found || hasNonReferenceSuperClassRec(bcd,level+1);
    if (!found)
    {
      // look for template instances that might have non-reference super classes
      for (const auto &cil : bcd->getTemplateInstances())
      {
        // recurse into the template instance branch
        found = hasNonReferenceSuperClassRec(cil.classDef,level+1);
        if (found) break;
      }
    }
    else
    {
      break;
    }
  }
  return found;
}
References err(), FALSE, found, ClassDef::getTemplateInstances(), hasNonReferenceSuperClassRec(), Definition::isHidden(), ClassDef::isLinkableInProject(), ClassDef::isReference(), Definition::name(), qPrint(), ClassDef::subClasses(), and TRUE.
Referenced by ClassDefImpl::hasNonReferenceSuperClass(), and hasNonReferenceSuperClassRec().
isStandardFunc()
static bool isStandardFunc (const MemberDef * md) static
Definition at line 3470 of file classdef.cpp.
{
  return md->name()=="operator=" || // assignment operator
         md->isConstructor() ||     // constructor
         md->isDestructor();        // destructor
}
References MemberDef::isConstructor(), MemberDef::isDestructor(), and Definition::name().
Referenced by ClassDefImpl::mergeMembers().
makeDisplayName()
static QCString makeDisplayName (const ClassDef * cd, bool includeScope) static
Definition at line 108 of file classdef.cpp.
{
  //bool optimizeOutputForJava = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
  SrcLangExt lang = cd->getLanguage();
  //bool vhdlOpt = Config_getBool(OPTIMIZE_OUTPUT_VHDL);
  QCString n;
  if (lang==SrcLangExt_VHDL)
  {
    n = VhdlDocGen::getClassName(cd);
  }
  else
  {
    if (includeScope)
    {
      n=cd->qualifiedNameWithTemplateParameters();
    }
    else
    {
      n=cd->className();
    }
  }
  if (cd->isAnonymous())
  {
    n = removeAnonymousScopes(n);
  }
  QCString sep=getLanguageSpecificSeparator(lang);
  if (sep!="::")
  {
    n=substitute(n,"::",sep);
  }
  if (cd->compoundType()==ClassDef::Protocol && n.endsWith("-p"))
  {
    n="<"+n.left(n.length()-2)+">";
  }
  return n;
}
References ClassDef::className(), ClassDef::compoundType(), QCString::endsWith(), VhdlDocGen::getClassName(), Definition::getLanguage(), getLanguageSpecificSeparator(), Definition::isAnonymous(), QCString::left(), QCString::length(), ClassDef::Protocol, ClassDef::qualifiedNameWithTemplateParameters(), removeAnonymousScopes(), SrcLangExt_VHDL, and substitute().
Referenced by ClassDefImpl::displayName(), and ClassDefAliasImpl::displayName().
makeQualifiedNameWithTemplateParameters()
static QCString makeQualifiedNameWithTemplateParameters (const ClassDef * cd, const ArgumentLists * actualParams, uint * actualParamIndex) static
Definition at line 56 of file classdef.cpp.
{
  //bool optimizeOutputJava = Config_getBool(OPTIMIZE_OUTPUT_JAVA);
  bool hideScopeNames = Config_getBool(HIDE_SCOPE_NAMES);
  //printf("qualifiedNameWithTemplateParameters() localName=%s\n",qPrint(localName()));
  QCString scName;
  const Definition *d=cd->getOuterScope();
  if (d)
  {
    if (d->definitionType()==Definition::TypeClass)
    {
      const ClassDef *ocd=toClassDef(d);
      scName = ocd->qualifiedNameWithTemplateParameters(actualParams,actualParamIndex);
    }
    else if (!hideScopeNames)
    {
      scName = d->qualifiedName();
    }
  }
  SrcLangExt lang = cd->getLanguage();
  QCString scopeSeparator = getLanguageSpecificSeparator(lang);
  if (!scName.isEmpty()) scName+=scopeSeparator;
  bool isSpecialization = cd->localName().find('<')!=-1;
  QCString clName = cd->className();
  scName+=clName;
  if (!cd->templateArguments().empty())
  {
    if (actualParams && *actualParamIndex<actualParams->size())
    {
      const ArgumentList &al = actualParams->at(*actualParamIndex);
      if (!isSpecialization)
      {
        scName+=tempArgListToString(al,lang);
      }
      (*actualParamIndex)++;
    }
    else
    {
      if (!isSpecialization)
      {
        scName+=tempArgListToString(cd->templateArguments(),lang);
      }
    }
  }
  //printf("qualifiedNameWithTemplateParameters: scope=%s qualifiedName=%s\n",qPrint(name()),qPrint(scName));
  return scName;
}
References ArgumentList::at(), ClassDef::className(), Config_getBool, Definition::definitionType(), ArgumentList::empty(), QCString::find(), Definition::getLanguage(), getLanguageSpecificSeparator(), Definition::getOuterScope(), QCString::isEmpty(), isSpecialization(), Definition::localName(), Definition::qualifiedName(), ClassDef::qualifiedNameWithTemplateParameters(), tempArgListToString(), ClassDef::templateArguments(), toClassDef(), and Definition::TypeClass.
Referenced by ClassDefImpl::qualifiedNameWithTemplateParameters(), and ClassDefAliasImpl::qualifiedNameWithTemplateParameters().
minClassDistance()
int minClassDistance (const ClassDef * cd, const ClassDef * bcd, int level)
Definition at line 5134 of file classdef.cpp.
{
  const int maxInheritanceDepth = 100000;
  if (bcd->categoryOf()) // use class that is being extended in case of
    // an Objective-C category
  {
    bcd=bcd->categoryOf();
  }
  if (cd==bcd) return level;
  if (level==256)
  {
    warn_uncond("class %s seem to have a recursive "
        "inheritance relation!\n",qPrint(cd->name()));
    return -1;
  }
  int m=maxInheritanceDepth;
  for (const auto &bcdi : cd->baseClasses())
  {
    int mc=minClassDistance(bcdi.classDef,bcd,level+1);
    if (mc<m) m=mc;
    if (m<0) break;
  }
  return m;
}
References ClassDef::baseClasses(), ClassDef::categoryOf(), maxInheritanceDepth, minClassDistance(), Definition::name(), qPrint(), and warn_uncond().
Referenced by computeMemberRelations(), getDefsOld(), ClassDefImpl::getMemberByName(), and minClassDistance().
searchTemplateSpecs()
static void searchTemplateSpecs (const Definition * d, ArgumentLists & result, QCString & name, SrcLangExt lang) static
Definition at line 1299 of file classdef.cpp.
{
  if (d->definitionType()==Definition::TypeClass)
  {
    if (d->getOuterScope())
    {
      searchTemplateSpecs(d->getOuterScope(),result,name,lang);
    }
    const ClassDef *cd=toClassDef(d);
    if (!name.isEmpty()) name+="::";
    QCString clName = d->localName();
    if (clName.endsWith("-p"))
    {
      clName = clName.left(clName.length()-2);
    }
    name+=clName;
    bool isSpecialization = d->localName().find('<')!=-1;
    if (!cd->templateArguments().empty())
    {
      result.push_back(cd->templateArguments());
      if (!isSpecialization)
      {
        name+=tempArgListToString(cd->templateArguments(),lang);
      }
    }
  }
  else
  {
    name+=d->qualifiedName();
  }
}
References Definition::definitionType(), ArgumentList::empty(), QCString::endsWith(), QCString::find(), Definition::getOuterScope(), QCString::isEmpty(), isSpecialization(), QCString::left(), QCString::length(), Definition::localName(), Definition::qualifiedName(), searchTemplateSpecs(), tempArgListToString(), ClassDef::templateArguments(), toClassDef(), and Definition::TypeClass.
Referenced by searchTemplateSpecs(), and ClassDefImpl::writeTemplateSpec().
toClassDef() [1/3]
const ClassDef * toClassDef (const Definition * d)
Definition at line 5053 of file classdef.cpp.
{
  if (d && (typeid(*d)==typeid(ClassDefImpl) || typeid(*d)==typeid(ClassDefAliasImpl)))
  {
    return static_cast<const ClassDef*>(d);
  }
  else
  {
    return 0;
  }
}
toClassDef() [2/3]
ClassDef * toClassDef (Definition * d)
Definition at line 5028 of file classdef.cpp.
{
  if (d && (typeid(*d)==typeid(ClassDefImpl) || typeid(*d)==typeid(ClassDefAliasImpl)))
  {
    return static_cast<ClassDef*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by NestingNodeContext::Private::addClasses(), DocSets::addIndexItem(), ClassDefImpl::addInnerCompound(), NamespaceDefImpl::addInnerCompound(), MemberDefImpl::addListReference(), NestingNodeContext::Private::addMembers(), ClassContext::Private::addTemplateDecls(), NestingNodeContext::Private::createClass(), MemberListInfoContext::Private::createInherited(), definitionToName(), findMemberLink(), SymbolResolver::Private::followPath(), generateClassMemberLink(), generateClassOrGlobalLink(), FTVHelp::Private::generateTree(), ClassDefAliasImpl::getCdAlias(), SymbolResolver::Private::getResolvedSymbol(), SymbolResolver::Private::getResolvedType(), SymbolResolver::Private::getResolvedTypeRec(), ClassDefImpl::getTemplateParameterLists(), SymbolResolver::Private::isAccessibleFrom(), SymbolResolver::Private::isAccessibleFromWithExpScope(), makeQualifiedNameWithTemplateParameters(), MemberDefImpl::moveTo(), scopeIsTemplate(), searchTemplateSpecs(), SearchIndex::setCurrentDoc(), updateCallContextForSmartPointer(), writeDefArgumentList(), writeJavaScriptSearchIndex(), MemberDefImpl::writeMemberDocSimple(), writeObjCMethodCall(), MemberList::writeSimpleDocumentation(), and VhdlDocGen::writeVHDLTypeDocumentation().
toClassDef() [3/3]
ClassDef * toClassDef (DefinitionMutable * md)
Definition at line 5040 of file classdef.cpp.
{
  Definition *d = toDefinition(md);
  if (d && typeid(*d)==typeid(ClassDefImpl))
  {
    return static_cast<ClassDef*>(d);
  }
  else
  {
    return 0;
  }
}
References toDefinition().
toClassDefMutable()
ClassDefMutable * toClassDefMutable (Definition * d)
Definition at line 5065 of file classdef.cpp.
{
  if (d && typeid(*d)==typeid(ClassDefImpl))
  {
    return static_cast<ClassDefMutable*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by addClassAndNestedClasses(), addClassToContext(), addClassToGroups(), addListReferences(), addMembersToMemberGroup(), ClassDefImpl::addMembersToTemplateInstance(), addMemberToGroups(), ClassDefImpl::addTypeConstraint(), buildCompleteMemberLists(), computeMemberReferences(), computeTemplateClassRelations(), VhdlDocGen::computeVhdlComponentRelations(), ClassDefImpl::countInheritedDecMembers(), countMembers(), createTagLessInstance(), createTemplateInstanceMembers(), distributeClassGroupRelations(), distributeMemberGroupDocumentation(), findClassRelation(), findInheritedTemplateInstances(), findSectionsInDocumentation(), findTagLessClasses(), findTemplateInstanceRelation(), findUsedClassesForClass(), findUsedTemplateInstances(), findUsingDeclarations(), generateClassDocs(), generateClassOrGlobalLink(), generateNamespaceClassDocs(), MemberDefImpl::getClassDefMutable(), getClassMutable(), ClassDefImpl::insertTemplateInstance(), ClassDefImpl::insertUsedFile(), mergeCategories(), ClassDefImpl::mergeCategory(), ClassDefImpl::mergeMembers(), SymbolResolver::resolveClassMutable(), resolveClassNestingRelations(), setAnonymousEnumType(), ClassDefImpl::setGroupDefForAllMembers(), sortMemberLists(), ClassDefImpl::writeInheritedMemberDeclarations(), and writeTagFile().
writeInheritanceSpecifier()
static void writeInheritanceSpecifier (OutputList & ol, const BaseClassDef & bcd) static
Definition at line 1238 of file classdef.cpp.
{
  if (bcd.prot!=Protection::Public || bcd.virt!=Specifier::Normal)
  {
    ol.startTypewriter();
    ol.docify(" [");
    StringVector sl;
    if      (bcd.prot==Protection::Protected) sl.push_back("protected");
    else if (bcd.prot==Protection::Private)   sl.push_back("private");
    if      (bcd.virt==Specifier::Virtual)    sl.push_back("virtual");
    bool first=true;
    for (const auto &s : sl)
    {
      if (!first) ol.docify(", ");
      ol.docify(s.c_str());
      first=false;
    }
    ol.docify("]");
    ol.endTypewriter();
  }
}
References OutputList::docify(), OutputList::endTypewriter(), Normal, Private, BaseClassDef::prot, Protected, Public, OutputList::startTypewriter(), BaseClassDef::virt, and Virtual.
Referenced by ClassDefImpl::writeInheritanceGraph().