Doxygen: ConceptDefImpl Class Reference
ConceptDefImpl Class Reference
Public Member Functions
ConceptDefImpl (const QCString &fileName, int startLine, int startColumn, const QCString &name, const QCString &tagRef=QCString(), const QCString &tagFile=QCString())
~ConceptDefImpl ()
virtual ConceptDef * resolveAlias ()
virtual DefType definitionType () const
virtual CodeSymbolType codeSymbolType () const
virtual QCString getOutputFileBase () const
virtual bool hasDetailedDescription () const
virtual QCString displayName (bool includeScope=true) const
virtual const IncludeInfo * includeInfo () const
virtual ArgumentList getTemplateParameterList () const
virtual QCString anchor () const
virtual bool isLinkableInProject () const
virtual bool isLinkable () const
virtual QCString initializer () const
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const
virtual const NamespaceDef * getNamespaceDef () const
virtual const FileDef * getFileDef () const
virtual QCString title () const
virtual int groupId () const
virtual void setIncludeFile (FileDef *fd, const QCString &incName, bool local, bool force)
virtual void setTemplateArguments (const ArgumentList &al)
virtual void setNamespace (NamespaceDef *nd)
virtual void setFileDef (FileDef *fd)
virtual void writeTagFile (TextStream &)
virtual void writeDocumentation (OutputList &)
virtual void setInitializer (const QCString &init)
virtual void findSectionsInDocumentation ()
virtual void setGroupId (int id)
void writeBriefDescription (OutputList &) const
void writeAuthorSection (OutputList &ol) const
void writeIncludeFiles (OutputList &ol) const
void writeDetailedDescription (OutputList &ol, const QCString &title) const
void writeDefinition (OutputList &ol, const QCString &title) const
Public Member Functions inherited from DefinitionMixin< ConceptDefMutable >
DefinitionMixin (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const char *b=0, const char *d=0, bool isSymbol=TRUE)
virtual ~DefinitionMixin ()=default
virtual bool isAlias () const
virtual QCString name () const
virtual bool isAnonymous () const
virtual QCString localName () const
virtual QCString qualifiedName () const
virtual QCString symbolName () const
virtual QCString getSourceFileBase () const
virtual QCString getSourceAnchor () const
virtual QCString documentation () const
virtual int docLine () const
virtual QCString docFile () const
virtual QCString briefDescription (bool abbreviate=FALSE) const
virtual QCString briefDescriptionAsTooltip () const
virtual int briefLine () const
virtual QCString inbodyDocumentation () const
virtual QCString inbodyFile () const
virtual int inbodyLine () const
virtual QCString briefFile () const
virtual QCString getDefFileName () const
virtual QCString getDefFileExtension () const
virtual int getDefLine () const
virtual int getDefColumn () const
virtual bool hasDocumentation () const
virtual bool hasUserDocumentation () const
virtual bool isVisibleInProject () const
virtual bool isVisible () const
virtual bool isHidden () const
virtual bool isArtificial () const
virtual QCString getReference () const
virtual bool isReference () const
virtual QCString externalReference (const QCString &relPath) const
virtual int getStartDefLine () const
virtual int getStartBodyLine () const
virtual int getEndBodyLine () const
virtual const FileDef * getBodyDef () const
virtual SrcLangExt getLanguage () const
virtual const GroupList & partOfGroups () const
virtual bool isLinkableViaGroup () const
virtual const RefItemVector & xrefListItems () const
virtual const Definition * findInnerCompound (const QCString &name) const
virtual Definition * getOuterScope () const
virtual const MemberVector & getReferencesMembers () const
virtual const MemberVector & getReferencedByMembers () const
virtual bool hasSections () const
virtual bool hasSources () const
virtual bool hasBriefDescription () const
virtual QCString id () const
virtual const SectionRefs & getSectionRefs () const
virtual void setName (const QCString &name)
virtual void setId (const QCString &name)
virtual void setDefFile (const QCString &df, int defLine, int defColumn)
virtual void setDocumentation (const QCString &doc, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)
virtual void setBriefDescription (const QCString &brief, const QCString &briefFile, int briefLine)
virtual void setInbodyDocumentation (const QCString &doc, const QCString &docFile, int docLine)
virtual void setReference (const QCString &r)
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)
virtual void setBodySegment (int defLine, int bls, int ble)
virtual void setBodyDef (const FileDef *fd)
virtual void addSourceReferencedBy (MemberDef *md)
virtual void addSourceReferences (MemberDef *md)
virtual void setRefItems (const RefItemVector &sli)
virtual void mergeRefItems (Definition *def)
virtual void mergeReferences (const Definition *other)
virtual void mergeReferencedBy (const Definition *other)
virtual void addInnerCompound (Definition *def)
virtual void setOuterScope (Definition *def)
virtual void setHidden (bool b)
virtual void setArtificial (bool b)
virtual void setLanguage (SrcLangExt lang)
virtual void writeSourceDef (OutputList &ol, const QCString &scopeName) const
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const
virtual bool hasSourceRefs () const
virtual bool hasSourceReffedBy () const
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const
virtual void makePartOfGroup (GroupDef *gd)
virtual void writeNavigationPath (OutputList &ol) const
virtual QCString navigationPathAsString () const
virtual void writeQuickMemberLinks (OutputList &ol, const MemberDef *md) const
virtual void writeSummaryLinks (OutputList &ol) const
virtual QCString pathFragment () const
virtual void writeDocAnchorsToTagFile (TextStream &fs) const
virtual void setLocalName (const QCString &name)
virtual void addSectionsToIndex ()
virtual void writeToc (OutputList &ol, const LocalToc &lt) const
virtual void computeTooltip ()
virtual void _setSymbolName (const QCString &name)
virtual QCString _symbolName () const
virtual void setIncludeFile (FileDef *fd, const QCString &incName, bool local, bool force)=0
virtual void setTemplateArguments (const ArgumentList &al)=0
virtual void setNamespace (NamespaceDef *nd)=0
virtual void setFileDef (FileDef *fd)=0
virtual void writeTagFile (TextStream &)=0
virtual void writeDocumentation (OutputList &ol)=0
virtual void setInitializer (const QCString &init)=0
virtual void findSectionsInDocumentation ()=0
virtual void setGroupId (int id)=0
Public Member Functions inherited from DefinitionMutable
virtual void setName (const QCString &name)=0
virtual void setId (const QCString &name)=0
virtual void setDefFile (const QCString &df, int defLine, int defColumn)=0
virtual void setDocumentation (const QCString &d, const QCString &docFile, int docLine, bool stripWhiteSpace=TRUE)=0
virtual void setBriefDescription (const QCString &b, const QCString &briefFile, int briefLine)=0
virtual void setInbodyDocumentation (const QCString &d, const QCString &docFile, int docLine)=0
virtual void setReference (const QCString &r)=0
virtual void setBodySegment (int defLine, int bls, int ble)=0
virtual void setBodyDef (const FileDef *fd)=0
virtual void setRefItems (const RefItemVector &sli)=0
virtual void setOuterScope (Definition *d)=0
virtual void setHidden (bool b)=0
virtual void setArtificial (bool b)=0
virtual void setLanguage (SrcLangExt lang)=0
virtual void setLocalName (const QCString &name)=0
virtual void makePartOfGroup (GroupDef *gd)=0
virtual void addSectionsToDefinition (const std::vector< const SectionInfo * > &anchorList)=0
virtual void addSourceReferencedBy (MemberDef *d)=0
virtual void addSourceReferences (MemberDef *d)=0
virtual void mergeRefItems (Definition *d)=0
virtual void addInnerCompound (Definition *d)=0
virtual void addSectionsToIndex ()=0
virtual void mergeReferences (const Definition *other)=0
virtual void mergeReferencedBy (const Definition *other)=0
virtual void computeTooltip ()=0
virtual void writeSourceDef (OutputList &ol, const QCString &scopeName) const =0
virtual void writeInlineCode (OutputList &ol, const QCString &scopeName) const =0
virtual bool hasSourceRefs () const =0
virtual bool hasSourceReffedBy () const =0
virtual void writeSourceRefs (OutputList &ol, const QCString &scopeName) const =0
virtual void writeSourceReffedBy (OutputList &ol, const QCString &scopeName) const =0
virtual void writeNavigationPath (OutputList &ol) const =0
virtual void writeQuickMemberLinks (OutputList &, const MemberDef *) const =0
virtual void writeSummaryLinks (OutputList &) const =0
virtual void writeDocAnchorsToTagFile (TextStream &) const =0
virtual void writeToc (OutputList &ol, const LocalToc &lt) const =0
virtual ~DefinitionMutable ()=default
virtual DefType definitionType () const =0
virtual QCString getOutputFileBase () const =0
virtual bool hasDetailedDescription () const =0
virtual QCString displayName (bool includeScope=true) const =0
virtual const IncludeInfo * includeInfo () const =0
virtual ArgumentList getTemplateParameterList () const =0
virtual QCString anchor () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual QCString initializer () const =0
virtual void writeDeclarationLink (OutputList &ol, bool &found, const QCString &header, bool localNames) const =0
virtual const NamespaceDef * getNamespaceDef () const =0
virtual const FileDef * getFileDef () const =0
virtual QCString title () const =0
virtual int groupId () const =0
Public Member Functions inherited from Definition
virtual DefType definitionType () const =0
virtual CodeSymbolType codeSymbolType () const =0
virtual bool isAlias () const =0
virtual QCString name () const =0
virtual bool isAnonymous () const =0
virtual QCString displayName (bool includeScope=TRUE) const =0
virtual QCString localName () const =0
virtual QCString qualifiedName () const =0
virtual QCString symbolName () const =0
virtual QCString getOutputFileBase () const =0
virtual QCString anchor () const =0
virtual QCString getSourceFileBase () const =0
virtual QCString getSourceAnchor () const =0
virtual QCString documentation () const =0
virtual int docLine () const =0
virtual QCString docFile () const =0
virtual QCString briefDescription (bool abbreviate=FALSE) const =0
virtual QCString briefDescriptionAsTooltip () const =0
virtual int briefLine () const =0
virtual QCString inbodyDocumentation () const =0
virtual QCString inbodyFile () const =0
virtual int inbodyLine () const =0
virtual QCString briefFile () const =0
virtual QCString getDefFileName () const =0
virtual QCString getDefFileExtension () const =0
virtual int getDefLine () const =0
virtual int getDefColumn () const =0
virtual bool hasDocumentation () const =0
virtual bool hasUserDocumentation () const =0
virtual bool isLinkableInProject () const =0
virtual bool isLinkable () const =0
virtual bool isVisibleInProject () const =0
virtual bool isVisible () const =0
virtual bool isHidden () const =0
virtual bool isArtificial () const =0
virtual QCString getReference () const =0
virtual bool isReference () const =0
virtual QCString externalReference (const QCString &relPath) const =0
virtual int getStartDefLine () const =0
virtual int getStartBodyLine () const =0
virtual int getEndBodyLine () const =0
virtual const FileDef * getBodyDef () const =0
virtual SrcLangExt getLanguage () const =0
Returns the programming language this definition was written in.
virtual const GroupList & partOfGroups () const =0
virtual bool isLinkableViaGroup () const =0
virtual const RefItemVector & xrefListItems () const =0
virtual const Definition * findInnerCompound (const QCString &name) const =0
virtual Definition * getOuterScope () const =0
virtual const MemberVector & getReferencesMembers () const =0
virtual const MemberVector & getReferencedByMembers () const =0
virtual bool hasSections () const =0
virtual bool hasSources () const =0
virtual bool hasBriefDescription () const =0
returns TRUE if this class has a brief description
virtual QCString id () const =0
virtual const SectionRefs & getSectionRefs () const =0
returns the section dictionary, only of importance for pagedef
virtual QCString navigationPathAsString () const =0
virtual QCString pathFragment () const =0
virtual void _setSymbolName (const QCString &name)=0
virtual QCString _symbolName () const =0
virtual ~Definition ()=default
Private Attributes
QCString m_fileName
std::unique_ptr< IncludeInfo > m_incInfo
NamespaceDef * m_nspace = 0
FileDef * m_fileDef = 0
ArgumentList m_tArgList
QCString m_initializer
int m_groupId = -1
Additional Inherited Members
Public Types inherited from Definition
enum DefType {
TypeClass = 0 , TypeFile = 1 , TypeNamespace = 2 , TypeMember = 3 ,
TypeGroup = 4 , TypePackage = 5 , TypePage = 6 , TypeDir = 7 ,
TypeConcept = 8
}
Protected Member Functions inherited from DefinitionMixin< ConceptDefMutable >
DefinitionMixin (const DefinitionMixin &def)=default
Detailed Description
Definition at line 31 of file conceptdef.cpp.
Constructor & Destructor Documentation
ConceptDefImpl()
ConceptDefImpl::ConceptDefImpl (const QCString & fileName, int startLine, int startColumn, const QCString & name, const QCString & tagRef = QCString(), const QCString & tagFile = QCString())
Definition at line 152 of file conceptdef.cpp.
                                                                         : DefinitionMixin(fileName,startLine,startColumn,name)
{
  if (!tagFile.isEmpty())
  {
    if (!tagRef.isEmpty())
    {
      m_fileName = stripExtension(tagFile);
    }
    else
    {
      m_fileName = convertNameToFile(stripExtension(tagFile));
    }
  }
  else
  {
    m_fileName = convertNameToFile(QCString("concept")+name);
  }
  setReference(tagRef);
}
References convertNameToFile(), QCString::isEmpty(), m_fileName, DefinitionMixin< ConceptDefMutable >::name(), DefinitionMixin< ConceptDefMutable >::setReference(), and stripExtension().
~ConceptDefImpl()
ConceptDefImpl::~ConceptDefImpl ()
Definition at line 173 of file conceptdef.cpp.
{
}
Member Function Documentation
anchor()
QCString ConceptDefImpl::anchor () const virtual
Returns the anchor within a page where this item can be found
Implements ConceptDef.
Definition at line 196 of file conceptdef.cpp.
{
  return "";
}
Referenced by writeDeclarationLink().
codeSymbolType()
virtual CodeSymbolType ConceptDefImpl::codeSymbolType () const inline virtual
Used for syntax highlighting symbol class
Implements Definition.
Definition at line 42 of file conceptdef.cpp.
{ return CodeSymbolType::Concept; }
definitionType()
Definition::DefType ConceptDefImpl::definitionType () const virtual
Use this for dynamic inspection of the type of the derived class
Implements ConceptDef.
Definition at line 177 of file conceptdef.cpp.
{
  return TypeConcept;
}
References Definition::TypeConcept.
displayName()
QCString ConceptDefImpl::displayName (bool includeScope = true) const virtual
Returns the name of the definition as it appears in the output
Implements ConceptDef.
Definition at line 201 of file conceptdef.cpp.
{
  return includeScope ? name() : localName();
}
References DefinitionMixin< ConceptDefMutable >::localName(), and DefinitionMixin< ConceptDefMutable >::name().
Referenced by title(), writeDeclarationLink(), and writeDocumentation().
findSectionsInDocumentation()
void ConceptDefImpl::findSectionsInDocumentation () virtual
Implements ConceptDefMutable.
Definition at line 654 of file conceptdef.cpp.
{
  docFindSections(briefDescription(),this,docFile());
  docFindSections(documentation(),this,docFile());
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::docFile(), docFindSections(), and DefinitionMixin< ConceptDefMutable >::documentation().
getFileDef()
const FileDef * ConceptDefImpl::getFileDef () const virtual
Implements ConceptDef.
Definition at line 267 of file conceptdef.cpp.
{
  return m_fileDef;
}
References m_fileDef.
getNamespaceDef()
const NamespaceDef * ConceptDefImpl::getNamespaceDef () const virtual
Implements ConceptDef.
Definition at line 257 of file conceptdef.cpp.
{
  return m_nspace;
}
References m_nspace.
getOutputFileBase()
QCString ConceptDefImpl::getOutputFileBase () const virtual
Returns the base file name (without extension) of this definition. as it is referenced to/written to disk.
Implements ConceptDef.
Definition at line 182 of file conceptdef.cpp.
{
  return m_fileName;
}
References m_fileName.
Referenced by writeBriefDescription(), writeDeclarationLink(), writeDocumentation(), and writeTagFile().
getTemplateParameterList()
ArgumentList ConceptDefImpl::getTemplateParameterList () const virtual
Implements ConceptDef.
Definition at line 211 of file conceptdef.cpp.
{
  return m_tArgList;
}
References m_tArgList.
groupId()
int ConceptDefImpl::groupId () const virtual
Implements ConceptDef.
Definition at line 277 of file conceptdef.cpp.
{
  return m_groupId;
}
References m_groupId.
hasDetailedDescription()
bool ConceptDefImpl::hasDetailedDescription () const virtual
Implements ConceptDef.
Definition at line 187 of file conceptdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  bool sourceBrowser = Config_getBool(SOURCE_BROWSER);
  return ((!briefDescription().isEmpty() && repeatBrief) ||
          !documentation().isEmpty() ||
          (sourceBrowser && getStartBodyLine()!=-1 && getBodyDef()));
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), Config_getBool, DefinitionMixin< ConceptDefMutable >::documentation(), DefinitionMixin< ConceptDefMutable >::getBodyDef(), and DefinitionMixin< ConceptDefMutable >::getStartBodyLine().
Referenced by writeBriefDescription(), and writeDetailedDescription().
includeInfo()
const IncludeInfo * ConceptDefImpl::includeInfo () const virtual
Implements ConceptDef.
Definition at line 206 of file conceptdef.cpp.
{
  return m_incInfo.get();
}
References m_incInfo.
initializer()
QCString ConceptDefImpl::initializer () const virtual
Implements ConceptDef.
Definition at line 407 of file conceptdef.cpp.
{
  return m_initializer;
}
References m_initializer.
isLinkable()
bool ConceptDefImpl::isLinkable () const virtual
Returns TRUE iff it is possible to link to this item. This can be a link to another project imported via a tag file.
Implements ConceptDef.
Definition at line 224 of file conceptdef.cpp.
{
  return isLinkableInProject() || isReference();
}
References isLinkableInProject(), and DefinitionMixin< ConceptDefMutable >::isReference().
Referenced by writeDeclarationLink().
isLinkableInProject()
bool ConceptDefImpl::isLinkableInProject () const virtual
Returns TRUE iff it is possible to link to this item within this project.
Implements ConceptDef.
Definition at line 216 of file conceptdef.cpp.
{
  bool hideUndoc = Config_getBool(HIDE_UNDOC_CLASSES);
  return (hasDocumentation() || !hideUndoc) && /* documented */
         !isHidden() &&                        /* not hidden */
         !isReference();                       /* not an external reference */
}
References Config_getBool, DefinitionMixin< ConceptDefMutable >::hasDocumentation(), DefinitionMixin< ConceptDefMutable >::isHidden(), and DefinitionMixin< ConceptDefMutable >::isReference().
Referenced by isLinkable().
resolveAlias()
virtual ConceptDef * ConceptDefImpl::resolveAlias () inline virtual
Definition at line 38 of file conceptdef.cpp.
{ return this; }
setFileDef()
void ConceptDefImpl::setFileDef (FileDef * fd) virtual
Implements ConceptDefMutable.
Definition at line 262 of file conceptdef.cpp.
{
  m_fileDef=fd;
}
References m_fileDef.
setGroupId()
void ConceptDefImpl::setGroupId (int id) virtual
Implements ConceptDefMutable.
Definition at line 282 of file conceptdef.cpp.
{
  m_groupId = id;
}
References DefinitionMixin< ConceptDefMutable >::id(), and m_groupId.
setIncludeFile()
void ConceptDefImpl::setIncludeFile (FileDef * fd, const QCString & incName, bool local, bool force) virtual
Implements ConceptDefMutable.
Definition at line 229 of file conceptdef.cpp.
{
  if (!m_incInfo) m_incInfo = std::make_unique<IncludeInfo>();
  if ((!incName.isEmpty() && m_incInfo->includeName.isEmpty()) ||
      (fd!=0 && m_incInfo->fileDef==0)
     )
  {
    m_incInfo->fileDef     = fd;
    m_incInfo->includeName = incName;
    m_incInfo->local       = local;
  }
  if (force && !incName.isEmpty())
  {
    m_incInfo->includeName = incName;
    m_incInfo->local       = local;
  }
}
References QCString::isEmpty(), and m_incInfo.
setInitializer()
void ConceptDefImpl::setInitializer (const QCString & init) virtual
Implements ConceptDefMutable.
Definition at line 402 of file conceptdef.cpp.
{
  m_initializer = templateSpec(m_tArgList)+"\nconcept "+name()+" = "+init;
}
References m_initializer, m_tArgList, DefinitionMixin< ConceptDefMutable >::name(), and templateSpec().
setNamespace()
void ConceptDefImpl::setNamespace (NamespaceDef * nd) virtual
Implements ConceptDefMutable.
Definition at line 252 of file conceptdef.cpp.
{
  m_nspace = nd;
}
References m_nspace.
setTemplateArguments()
void ConceptDefImpl::setTemplateArguments (const ArgumentList & al) virtual
Implements ConceptDefMutable.
Definition at line 247 of file conceptdef.cpp.
{
  m_tArgList = al;
}
References m_tArgList.
title()
QCString ConceptDefImpl::title () const virtual
Implements ConceptDef.
Definition at line 272 of file conceptdef.cpp.
{
  return theTranslator->trConceptReference(displayName());
}
References displayName(), theTranslator, and Translator::trConceptReference().
Referenced by writeDefinition(), and writeDetailedDescription().
writeAuthorSection()
void ConceptDefImpl::writeAuthorSection (OutputList & ol) const
Definition at line 478 of file conceptdef.cpp.
{
  // write Author section (Man only)
  ol.pushGeneratorState();
  ol.disableAllBut(OutputType::Man);
  ol.startGroupHeader();
  ol.parseText(theTranslator->trAuthor(TRUE,TRUE));
  ol.endGroupHeader();
  ol.parseText(theTranslator->trGeneratedAutomatically(Config_getString(PROJECT_NAME)));
  ol.popGeneratorState();
}
References Config_getString, OutputList::disableAllBut(), OutputList::endGroupHeader(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), theTranslator, Translator::trAuthor(), Translator::trGeneratedAutomatically(), and TRUE.
Referenced by writeDocumentation().
writeBriefDescription()
void ConceptDefImpl::writeBriefDescription (OutputList & ol) const
Definition at line 301 of file conceptdef.cpp.
{
  if (hasBriefDescription())
  {
    auto parser { createDocParser() };
    auto ast    { validatingParseDoc(
                        *parser.get(),briefFile(),briefLine(),this,0,
                        briefDescription(),TRUE,FALSE,
                        QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
    if (!ast->isEmpty())
    {
      ol.startParagraph();
      ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Man);
      ol.writeString(" - ");
      ol.popGeneratorState();
      ol.writeDoc(ast.get(),this,0);
      ol.pushGeneratorState();
      ol.disable(OutputType::RTF);
      ol.writeString(" \n");
      ol.enable(OutputType::RTF);
      if (hasDetailedDescription())
      {
        ol.disableAllBut(OutputType::Html);
        ol.startTextLink(getOutputFileBase(),"details");
        ol.parseText(theTranslator->trMore());
        ol.endTextLink();
      }
      ol.popGeneratorState();
      ol.endParagraph();
    }
  }
  ol.writeSynopsis();
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::briefFile(), DefinitionMixin< ConceptDefMutable >::briefLine(), Config_getBool, createDocParser(), OutputList::disable(), OutputList::disableAllBut(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTextLink(), FALSE, getOutputFileBase(), DefinitionMixin< ConceptDefMutable >::hasBriefDescription(), hasDetailedDescription(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startParagraph(), OutputList::startTextLink(), theTranslator, Translator::trMore(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeString(), and OutputList::writeSynopsis().
Referenced by writeDocumentation().
writeDeclarationLink()
void ConceptDefImpl::writeDeclarationLink (OutputList & ol, bool & found, const QCString & header, bool localNames) const virtual
Implements ConceptDef.
Definition at line 596 of file conceptdef.cpp.
{
  if (isLinkable())
  {
    if (!found) // first concept
    {
      ol.startMemberHeader("concepts");
      if (!header.isEmpty())
      {
        ol.parseText(header);
      }
      else
      {
        theTranslator->trConcept(true,false);
      }
      ol.endMemberHeader();
      ol.startMemberList();
      found=TRUE;
    }
    ol.startMemberDeclaration();
    ol.startMemberItem(anchor(),OutputGenerator::MemberItemType::Normal);
    ol.writeString("concept ");
    QCString cname = displayName(!localNames);
    ol.insertMemberAlign();
    if (isLinkable())
    {
      ol.writeObjectLink(getReference(),
          getOutputFileBase(),
          anchor(),
          cname
          );
    }
    else
    {
      ol.startBold();
      ol.docify(cname);
      ol.endBold();
    }
    ol.endMemberItem(OutputGenerator::MemberItemType::Normal);
    // add the brief description if available
    if (!briefDescription().isEmpty() && Config_getBool(BRIEF_MEMBER_DESC))
    {
      auto parser { createDocParser() };
      auto ast    { validatingParseDoc(
                                *parser.get(),briefFile(),briefLine(),this,0,
                                briefDescription(),FALSE,FALSE,
                                QCString(),TRUE,FALSE,Config_getBool(MARKDOWN_SUPPORT)) };
      if (!ast->isEmpty())
      {
        ol.startMemberDescription(anchor());
        ol.writeDoc(ast.get(),this,0);
        ol.endMemberDescription();
      }
    }
    ol.endMemberDeclaration(anchor(),QCString());
  }
}
References anchor(), DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::briefFile(), DefinitionMixin< ConceptDefMutable >::briefLine(), Config_getBool, createDocParser(), displayName(), OutputList::docify(), OutputList::endBold(), OutputList::endMemberDeclaration(), OutputList::endMemberDescription(), OutputList::endMemberHeader(), OutputList::endMemberItem(), FALSE, found, getOutputFileBase(), DefinitionMixin< ConceptDefMutable >::getReference(), OutputList::insertMemberAlign(), QCString::isEmpty(), isLinkable(), OutputGenerator::Normal, OutputList::parseText(), OutputList::startBold(), OutputList::startMemberDeclaration(), OutputList::startMemberDescription(), OutputList::startMemberHeader(), OutputList::startMemberItem(), OutputList::startMemberList(), theTranslator, Translator::trConcept(), TRUE, validatingParseDoc(), OutputList::writeDoc(), OutputList::writeObjectLink(), and OutputList::writeString().
writeDefinition()
void ConceptDefImpl::writeDefinition (OutputList & ol, const QCString & title) const
Definition at line 412 of file conceptdef.cpp.
{
    ol.startGroupHeader();
      ol.parseText(title);
    ol.endGroupHeader();
    auto intf = Doxygen::parserManager->getCodeParser(".cpp");
    intf->resetCodeParserState();
    auto &codeOL = ol.codeGenerators();
    codeOL.startCodeFragment("DoxyCode");
    QCString scopeName;
    if (getOuterScope()!=Doxygen::globalScope) scopeName=getOuterScope()->name();
    TextStream conceptDef;
    conceptDef << m_initializer;
    intf->parseCode(codeOL,scopeName,conceptDef.str(),SrcLangExt_Cpp,false,QCString(),
                    m_fileDef, -1,-1,true,0,false,this);
    codeOL.endCodeFragment("DoxyCode");
}
References OutputList::codeGenerators(), OutputList::endGroupHeader(), ParserManager::getCodeParser(), DefinitionMixin< ConceptDefMutable >::getOuterScope(), Doxygen::globalScope, m_fileDef, m_initializer, Definition::name(), Doxygen::parserManager, OutputList::parseText(), SrcLangExt_Cpp, OutputCodeList::startCodeFragment(), OutputList::startGroupHeader(), TextStream::str(), and title().
Referenced by writeDocumentation().
writeDetailedDescription()
void ConceptDefImpl::writeDetailedDescription (OutputList & ol, const QCString & title) const
Definition at line 431 of file conceptdef.cpp.
{
  bool repeatBrief = Config_getBool(REPEAT_BRIEF);
  if (hasDetailedDescription())
  {
    ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.writeRuler();
    ol.popGeneratorState();
    ol.pushGeneratorState();
      ol.disableAllBut(OutputType::Html);
      ol.writeAnchor(QCString(),"details");
    ol.popGeneratorState();
    ol.startGroupHeader();
      ol.parseText(title);
    ol.endGroupHeader();
    ol.startTextBlock();
    // repeat brief description
    if (!briefDescription().isEmpty() && repeatBrief)
    {
      ol.generateDoc(briefFile(),briefLine(),this,0,briefDescription(),FALSE,FALSE,
          QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    if (!briefDescription().isEmpty() && repeatBrief &&
        !documentation().isEmpty())
    {
      ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.writeString("\n\n");
      ol.popGeneratorState();
    }
    // write documentation
    if (!documentation().isEmpty())
    {
      ol.generateDoc(docFile(),docLine(),this,0,documentation(),TRUE,FALSE,
          QCString(),FALSE,FALSE,Config_getBool(MARKDOWN_SUPPORT));
    }
    writeSourceDef(ol,name());
    ol.endTextBlock();
  }
}
References DefinitionMixin< ConceptDefMutable >::briefDescription(), DefinitionMixin< ConceptDefMutable >::briefFile(), DefinitionMixin< ConceptDefMutable >::briefLine(), Config_getBool, OutputList::disable(), OutputList::disableAllBut(), DefinitionMixin< ConceptDefMutable >::docFile(), DefinitionMixin< ConceptDefMutable >::docLine(), DefinitionMixin< ConceptDefMutable >::documentation(), OutputList::endGroupHeader(), OutputList::endTextBlock(), FALSE, OutputList::generateDoc(), hasDetailedDescription(), DefinitionMixin< ConceptDefMutable >::name(), OutputList::parseText(), OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startGroupHeader(), OutputList::startTextBlock(), title(), TRUE, OutputList::writeAnchor(), OutputList::writeRuler(), DefinitionMixin< ConceptDefMutable >::writeSourceDef(), and OutputList::writeString().
Referenced by writeDocumentation().
writeDocumentation()
void ConceptDefImpl::writeDocumentation (OutputList & ol) virtual
Implements ConceptDefMutable.
Definition at line 490 of file conceptdef.cpp.
{
  bool generateTreeView = Config_getBool(GENERATE_TREEVIEW);
  QCString pageTitle = theTranslator->trConceptReference(displayName());
  startFile(ol,getOutputFileBase(),name(),pageTitle,HighlightedItem::ConceptVisible,!generateTreeView);
  // ---- navigation part
  if (!generateTreeView)
  {
    if (getOuterScope()!=Doxygen::globalScope)
    {
      writeNavigationPath(ol);
    }
    ol.endQuickIndices();
  }
  // ---- title part
  startTitle(ol,getOutputFileBase(),this);
  ol.parseText(pageTitle);
  addGroupListToTitle(ol,this);
  endTitle(ol,getOutputFileBase(),displayName());
  // ---- contents part
  ol.startContents();
  //---------------------------------------- start flexible part -------------------------------
  for (const auto &lde : LayoutDocManager::instance().docEntries(LayoutDocManager::Concept))
  {
    const LayoutDocEntrySection *ls = dynamic_cast<const LayoutDocEntrySection*>(lde.get());
    switch (lde->kind())
    {
      case LayoutDocEntry::BriefDesc:
        writeBriefDescription(ol);
        break;
      case LayoutDocEntry::ConceptDefinition:
        if (ls) writeDefinition(ol,ls->title(getLanguage()));
        break;
      case LayoutDocEntry::DetailedDesc:
        if (ls) writeDetailedDescription(ol,ls->title(getLanguage()));
        break;
      case LayoutDocEntry::AuthorSection:
        writeAuthorSection(ol);
        break;
      case LayoutDocEntry::ClassIncludes:
        writeIncludeFiles(ol);
        break;
      case LayoutDocEntry::MemberDeclStart:
      case LayoutDocEntry::NamespaceClasses:
      case LayoutDocEntry::NamespaceInterfaces:
      case LayoutDocEntry::NamespaceStructs:
      case LayoutDocEntry::NamespaceExceptions:
      case LayoutDocEntry::NamespaceConcepts:
      case LayoutDocEntry::NamespaceNestedNamespaces:
      case LayoutDocEntry::NamespaceNestedConstantGroups:
      case LayoutDocEntry::MemberGroups:
      case LayoutDocEntry::MemberDecl:
      case LayoutDocEntry::MemberDeclEnd:
      case LayoutDocEntry::MemberDefStart:
      case LayoutDocEntry::NamespaceInlineClasses:
      case LayoutDocEntry::MemberDef:
      case LayoutDocEntry::MemberDefEnd:
      case LayoutDocEntry::ClassInheritanceGraph:
      case LayoutDocEntry::ClassNestedClasses:
      case LayoutDocEntry::ClassCollaborationGraph:
      case LayoutDocEntry::ClassAllMembersLink:
      case LayoutDocEntry::ClassUsedFiles:
      case LayoutDocEntry::ClassInlineClasses:
      case LayoutDocEntry::FileClasses:
      case LayoutDocEntry::FileConcepts:
      case LayoutDocEntry::FileInterfaces:
      case LayoutDocEntry::FileStructs:
      case LayoutDocEntry::FileExceptions:
      case LayoutDocEntry::FileNamespaces:
      case LayoutDocEntry::FileConstantGroups:
      case LayoutDocEntry::FileIncludes:
      case LayoutDocEntry::FileIncludeGraph:
      case LayoutDocEntry::FileIncludedByGraph:
      case LayoutDocEntry::FileInlineClasses:
      case LayoutDocEntry::FileSourceLink:
      case LayoutDocEntry::GroupClasses:
      case LayoutDocEntry::GroupConcepts:
      case LayoutDocEntry::GroupInlineClasses:
      case LayoutDocEntry::GroupNamespaces:
      case LayoutDocEntry::GroupDirs:
      case LayoutDocEntry::GroupNestedGroups:
      case LayoutDocEntry::GroupFiles:
      case LayoutDocEntry::GroupGraph:
      case LayoutDocEntry::GroupPageDocs:
      case LayoutDocEntry::DirSubDirs:
      case LayoutDocEntry::DirFiles:
      case LayoutDocEntry::DirGraph:
        err("Internal inconsistency: member %d should not be part of "
            "LayoutDocManager::Namespace entry list\n",lde->kind());
        break;
    }
  }
  //---------------------------------------- end flexible part -------------------------------
  ol.endContents();
  endFileWithNavPath(ol,this);
}
References addGroupListToTitle(), LayoutDocEntry::AuthorSection, LayoutDocEntry::BriefDesc, LayoutDocEntry::ClassAllMembersLink, LayoutDocEntry::ClassCollaborationGraph, LayoutDocEntry::ClassIncludes, LayoutDocEntry::ClassInheritanceGraph, LayoutDocEntry::ClassInlineClasses, LayoutDocEntry::ClassNestedClasses, LayoutDocEntry::ClassUsedFiles, LayoutDocManager::Concept, LayoutDocEntry::ConceptDefinition, Config_getBool, LayoutDocEntry::DetailedDesc, LayoutDocEntry::DirFiles, LayoutDocEntry::DirGraph, LayoutDocEntry::DirSubDirs, displayName(), OutputList::endContents(), endFileWithNavPath(), OutputList::endQuickIndices(), endTitle(), err(), LayoutDocEntry::FileClasses, LayoutDocEntry::FileConcepts, LayoutDocEntry::FileConstantGroups, LayoutDocEntry::FileExceptions, LayoutDocEntry::FileIncludedByGraph, LayoutDocEntry::FileIncludeGraph, LayoutDocEntry::FileIncludes, LayoutDocEntry::FileInlineClasses, LayoutDocEntry::FileInterfaces, LayoutDocEntry::FileNamespaces, LayoutDocEntry::FileSourceLink, LayoutDocEntry::FileStructs, DefinitionMixin< ConceptDefMutable >::getLanguage(), DefinitionMixin< ConceptDefMutable >::getOuterScope(), getOutputFileBase(), Doxygen::globalScope, LayoutDocEntry::GroupClasses, LayoutDocEntry::GroupConcepts, LayoutDocEntry::GroupDirs, LayoutDocEntry::GroupFiles, LayoutDocEntry::GroupGraph, LayoutDocEntry::GroupInlineClasses, LayoutDocEntry::GroupNamespaces, LayoutDocEntry::GroupNestedGroups, LayoutDocEntry::GroupPageDocs, LayoutDocManager::instance(), LayoutDocEntry::MemberDecl, LayoutDocEntry::MemberDeclEnd, LayoutDocEntry::MemberDeclStart, LayoutDocEntry::MemberDef, LayoutDocEntry::MemberDefEnd, LayoutDocEntry::MemberDefStart, LayoutDocEntry::MemberGroups, DefinitionMixin< ConceptDefMutable >::name(), LayoutDocEntry::NamespaceClasses, LayoutDocEntry::NamespaceConcepts, LayoutDocEntry::NamespaceExceptions, LayoutDocEntry::NamespaceInlineClasses, LayoutDocEntry::NamespaceInterfaces, LayoutDocEntry::NamespaceNestedConstantGroups, LayoutDocEntry::NamespaceNestedNamespaces, LayoutDocEntry::NamespaceStructs, OutputList::parseText(), OutputList::startContents(), startFile(), startTitle(), theTranslator, LayoutDocEntrySection::title(), Translator::trConceptReference(), writeAuthorSection(), writeBriefDescription(), writeDefinition(), writeDetailedDescription(), writeIncludeFiles(), and DefinitionMixin< ConceptDefMutable >::writeNavigationPath().
writeIncludeFiles()
void ConceptDefImpl::writeIncludeFiles (OutputList & ol) const
Definition at line 337 of file conceptdef.cpp.
{
  if (m_incInfo)
  {
    QCString nm=m_incInfo->includeName.isEmpty() ?
      (m_incInfo->fileDef ?
       m_incInfo->fileDef->docName() : QCString()
      ) :
      m_incInfo->includeName;
    if (!nm.isEmpty())
    {
      ol.startParagraph();
      ol.startTypewriter();
      ol.docify("#include ");
      if (m_incInfo->local)
        ol.docify("\"");
      else
        ol.docify("<");
      ol.pushGeneratorState();
      ol.disable(OutputType::Html);
      ol.docify(nm);
      ol.disableAllBut(OutputType::Html);
      ol.enable(OutputType::Html);
      if (m_incInfo->fileDef)
      {
        ol.writeObjectLink(QCString(),m_incInfo->fileDef->includeName(),QCString(),nm);
      }
      else
      {
        ol.docify(nm);
      }
      ol.popGeneratorState();
      if (m_incInfo->local)
        ol.docify("\"");
      else
        ol.docify(">");
      ol.endTypewriter();
      ol.endParagraph();
    }
  }
}
References OutputList::disable(), OutputList::disableAllBut(), OutputList::docify(), OutputList::enable(), OutputList::endParagraph(), OutputList::endTypewriter(), if(), QCString::isEmpty(), m_incInfo, OutputList::popGeneratorState(), OutputList::pushGeneratorState(), OutputList::startParagraph(), OutputList::startTypewriter(), and OutputList::writeObjectLink().
Referenced by writeDocumentation().
writeTagFile()
void ConceptDefImpl::writeTagFile (TextStream & tagFile) virtual
Implements ConceptDefMutable.
Definition at line 287 of file conceptdef.cpp.
{
  tagFile << "  <compound kind=\"concept\">\n";
  tagFile << "    <name>" << convertToXML(name()) << "</name>\n";
  tagFile << "    <filename>" << convertToXML(addHtmlExtensionIfMissing(getOutputFileBase())) << "</filename>\n";
  QCString idStr = id();
  if (!idStr.isEmpty())
  {
    tagFile << "    <clangid>" << convertToXML(idStr) << "</clangid>\n";
  }
  writeDocAnchorsToTagFile(tagFile);
  tagFile << "  </compound>\n";
}
References addHtmlExtensionIfMissing(), convertToXML(), getOutputFileBase(), DefinitionMixin< ConceptDefMutable >::id(), QCString::isEmpty(), DefinitionMixin< ConceptDefMutable >::name(), and DefinitionMixin< ConceptDefMutable >::writeDocAnchorsToTagFile().
Member Data Documentation
m_fileDef
FileDef* ConceptDefImpl::m_fileDef = 0 private
Definition at line 81 of file conceptdef.cpp.
Referenced by getFileDef(), setFileDef(), and writeDefinition().
m_fileName
QCString ConceptDefImpl::m_fileName private
Definition at line 78 of file conceptdef.cpp.
Referenced by ConceptDefImpl(), and getOutputFileBase().
m_groupId
int ConceptDefImpl::m_groupId = -1 private
Definition at line 84 of file conceptdef.cpp.
Referenced by groupId(), and setGroupId().
m_incInfo
std::unique_ptr<IncludeInfo> ConceptDefImpl::m_incInfo private
Definition at line 79 of file conceptdef.cpp.
Referenced by includeInfo(), setIncludeFile(), and writeIncludeFiles().
m_initializer
QCString ConceptDefImpl::m_initializer private
Definition at line 83 of file conceptdef.cpp.
Referenced by initializer(), setInitializer(), and writeDefinition().
m_nspace
NamespaceDef* ConceptDefImpl::m_nspace = 0 private
Definition at line 80 of file conceptdef.cpp.
Referenced by getNamespaceDef(), and setNamespace().
m_tArgList
ArgumentList ConceptDefImpl::m_tArgList private
Definition at line 82 of file conceptdef.cpp.
Referenced by getTemplateParameterList(), setInitializer(), and setTemplateArguments().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/conceptdef.cpp