Doxygen: ScopedTypeVariant Class Reference
ScopedTypeVariant Class Reference
#include <scopedtypevariant.h>
Public Types
enum Variant { Global , Local , Dummy }
possible variant types
Public Member Functions
ScopedTypeVariant ()
default constructor for creating a variant of type Dummy
ScopedTypeVariant (const Definition *d)
constructor for creating a variant of type Global
ScopedTypeVariant (const QCString &name)
constructor for creating a variant of type Local
ScopedTypeVariant (const ScopedTypeVariant &stv)
copy constructor
ScopedTypeVariant (ScopedTypeVariant &&stv) noexcept
move constructor
ScopedTypeVariant & operator= (ScopedTypeVariant stv)
assignment operator
~ScopedTypeVariant ()
destructor
void setGlobal (const Definition *def)
Turn the variant into a Global type.
LocalDef * setLocal (const QCString &name)
Turn the variant into a Local type.
void setDummy ()
Turn the variant into a Dummy type.
Variant type () const
QCString name () const
LocalDef * localDef () const
const Definition * globalDef () const
Private Attributes
Variant m_variant
QCString m_name
union {
const Definition * globalDef
LocalDef * localDef
} m_u
Friends
void swap (ScopedTypeVariant &first, ScopedTypeVariant &second)
swap function
Detailed Description
Variant class for a scoped type.
Variants:
Dummy: a type used for hiding a global type.
Local: a locally defined type (e.g. found inside a function)
Global: a globally defined type (processed by doxygen in an earlier pass).
Definition at line 45 of file scopedtypevariant.h.
Member Enumeration Documentation
Variant
enum ScopedTypeVariant::Variant
possible variant types
Enumerator
Global
Local
Dummy
Definition at line 49 of file scopedtypevariant.h.
    {
      Global,
      Local,
      Dummy
    };
Constructor & Destructor Documentation
ScopedTypeVariant() [1/5]
ScopedTypeVariant::ScopedTypeVariant () inline
default constructor for creating a variant of type Dummy
Definition at line 56 of file scopedtypevariant.h.
                        : m_variant(Dummy)
    {
      m_u.globalDef = 0;
    }
References m_u.
ScopedTypeVariant() [2/5]
ScopedTypeVariant::ScopedTypeVariant (const Definition * d) inline explicit
constructor for creating a variant of type Global
Definition at line 61 of file scopedtypevariant.h.
    {
      if (d)
      {
        m_name = d->name();
        m_variant = Global;
        m_u.globalDef = d;
      }
      else
      {
        m_variant = Dummy;
        m_u.globalDef = 0;
      }
    }
References Dummy, Global, m_name, m_u, m_variant, and Definition::name().
ScopedTypeVariant() [3/5]
ScopedTypeVariant::ScopedTypeVariant (const QCString & name) inline explicit
constructor for creating a variant of type Local
Definition at line 76 of file scopedtypevariant.h.
    {
      m_name = name;
      m_variant = Local;
      m_u.localDef = new LocalDef;
    }
References Local, m_name, m_u, m_variant, and name().
ScopedTypeVariant() [4/5]
ScopedTypeVariant::ScopedTypeVariant (const ScopedTypeVariant & stv) inline
copy constructor
Definition at line 83 of file scopedtypevariant.h.
    {
      m_variant = stv.m_variant;
      m_name    = stv.m_name;
      if (m_variant==Local)
      {
        m_u.localDef = new LocalDef(*stv.m_u.localDef);
      }
      else if (m_variant==Global)
      {
        m_u.globalDef = stv.m_u.globalDef;
      }
    }
References Global, globalDef, Local, localDef, m_name, m_u, and m_variant.
ScopedTypeVariant() [5/5]
ScopedTypeVariant::ScopedTypeVariant (ScopedTypeVariant && stv) inline noexcept
move constructor
Definition at line 97 of file scopedtypevariant.h.
                                                        : ScopedTypeVariant()
    {
      swap(*this,stv);
    }
References swap.
~ScopedTypeVariant()
ScopedTypeVariant::~ScopedTypeVariant () inline
destructor
Definition at line 108 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
    }
References Local, m_u, and m_variant.
Member Function Documentation
globalDef()
const Definition * ScopedTypeVariant::globalDef () const inline
Definition at line 160 of file scopedtypevariant.h.
{ return m_variant==Global ? m_u.globalDef : 0; }
References Global, m_u, and m_variant.
localDef()
LocalDef * ScopedTypeVariant::localDef () const inline
Definition at line 159 of file scopedtypevariant.h.
{ return m_variant==Local ? m_u.localDef : 0; }
References Local, m_u, and m_variant.
name()
QCString ScopedTypeVariant::name () const inline
Definition at line 158 of file scopedtypevariant.h.
{ return m_name; }
References m_name.
Referenced by generateClassOrGlobalLink(), generateMemberLink(), ScopedTypeVariant(), setCallContextForVar(), and setLocal().
operator=()
ScopedTypeVariant & ScopedTypeVariant::operator= (ScopedTypeVariant stv) inline
assignment operator
Definition at line 102 of file scopedtypevariant.h.
    {
      swap(*this,stv);
      return *this;
    }
References swap.
setDummy()
void ScopedTypeVariant::setDummy () inline
Turn the variant into a Dummy type.
Definition at line 147 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
      m_variant = Dummy;
      m_name = "";
      m_u.localDef=0;
    }
References Dummy, Local, m_name, m_u, and m_variant.
setGlobal()
void ScopedTypeVariant::setGlobal (const Definition * def) inline
Turn the variant into a Global type.
Definition at line 124 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
      m_variant = Global;
      m_name = def->name();
      m_u.globalDef = def;
    }
References Global, Local, m_name, m_u, m_variant, and Definition::name().
setLocal()
LocalDef * ScopedTypeVariant::setLocal (const QCString & name) inline
Turn the variant into a Local type.
Definition at line 135 of file scopedtypevariant.h.
    {
      if (m_variant==Local)
      {
        delete m_u.localDef;
      }
      m_variant = Local;
      m_name = name;
      m_u.localDef = new LocalDef;
      return m_u.localDef;
    }
References Local, m_name, m_u, m_variant, and name().
type()
Variant ScopedTypeVariant::type () const inline
Definition at line 157 of file scopedtypevariant.h.
{ return m_variant; }
References m_variant.
Referenced by generateClassOrGlobalLink(), generateMemberLink(), and setCallContextForVar().
Friends And Related Symbol Documentation
swap
void swap (ScopedTypeVariant & first, ScopedTypeVariant & second) friend
swap function
Definition at line 116 of file scopedtypevariant.h.
    {
      using std::swap; // enable ADL
      swap(first.m_variant,second.m_variant);
      swap(first.m_name,second.m_name);
      swap(first.m_u.globalDef,second.m_u.globalDef);
    }
Referenced by operator=(), and ScopedTypeVariant().
Member Data Documentation
globalDef
const Definition* ScopedTypeVariant::globalDef
Definition at line 167 of file scopedtypevariant.h.
Referenced by ScopedTypeVariant(), and writeObjCMethodCall().
localDef
LocalDef* ScopedTypeVariant::localDef
Definition at line 168 of file scopedtypevariant.h.
Referenced by generateFunctionLink(), generateMemberLink(), and ScopedTypeVariant().
m_name
QCString ScopedTypeVariant::m_name private
Definition at line 164 of file scopedtypevariant.h.
Referenced by name(), ScopedTypeVariant(), setDummy(), setGlobal(), and setLocal().
[union]
union { ... } ScopedTypeVariant::m_u
Referenced by globalDef(), localDef(), ScopedTypeVariant(), setDummy(), setGlobal(), setLocal(), and ~ScopedTypeVariant().
m_variant
Variant ScopedTypeVariant::m_variant private
Definition at line 163 of file scopedtypevariant.h.
Referenced by globalDef(), localDef(), ScopedTypeVariant(), setDummy(), setGlobal(), setLocal(), type(), and ~ScopedTypeVariant().
The documentation for this class was generated from the following file:
/home/runner/work/doxygen/doxygen/src/scopedtypevariant.h