Doxygen: Mappers Struct Reference
Mappers Struct Reference
Class representing a namespace for the doxygen and HTML command mappers.
#include <cmdmapper.h>
Static Public Member Functions
static void freeMappers ()
Static Public Attributes
static Mapper * cmdMapper = new Mapper(cmdMap,true)
static Mapper * htmlTagMapper = new Mapper(htmlTagMap,false)
Detailed Description
Class representing a namespace for the doxygen and HTML command mappers.
Definition at line 241 of file cmdmapper.h.
Member Function Documentation
freeMappers()
void Mappers::freeMappers () static
Definition at line 276 of file cmdmapper.cpp.
{
  delete cmdMapper;     cmdMapper     = 0;
  delete htmlTagMapper; htmlTagMapper = 0;
}
References cmdMapper, and htmlTagMapper.
Referenced by cleanUpDoxygen().
Member Data Documentation
cmdMapper
Mapper * Mappers::cmdMapper = new Mapper(cmdMap,true) static
Definition at line 244 of file cmdmapper.h.
Referenced by DocParser::defaultHandleTitleAndSize(), DocParser::defaultHandleToken(), freeMappers(), DocPara::handleCommand(), DocIndexEntry::parse(), DocHtmlDescTitle::parse(), DocSecRefList::parse(), DocPara::parse(), DocText::parse(), and DocLink::parse().
htmlTagMapper
Mapper * Mappers::htmlTagMapper = new Mapper(htmlTagMap,false) static
Definition at line 245 of file cmdmapper.h.
Referenced by DocParser::defaultHandleToken(), freeMappers(), DocPara::handleHtmlEndTag(), DocPara::handleHtmlStartTag(), DocParser::handleStyleArgument(), DocHRef::parse(), DocHtmlSummary::parse(), DocHtmlHeader::parse(), DocHtmlDescTitle::parse(), DocHtmlDescList::parse(), DocHtmlList::parse(), DocHtmlCell::parse(), DocHtmlCaption::parse(), DocHtmlRow::parse(), DocHtmlTable::parse(), DocHtmlList::parseXml(), DocHtmlCell::parseXml(), DocHtmlTable::parseXml(), DocHtmlRow::parseXml(), and DocParamList::parseXml().
The documentation for this struct was generated from the following files:
/home/runner/work/doxygen/doxygen/src/cmdmapper.h
/home/runner/work/doxygen/doxygen/src/cmdmapper.cpp