Doxygen: /home/runner/work/doxygen/doxygen/src/htmlhelp.cpp File Reference
htmlhelp.cpp File Reference
#include <algorithm>
#include <stdio.h>
#include <stdlib.h>
#include "htmlhelp.h"
#include "config.h"
#include "message.h"
#include "doxygen.h"
#include "language.h"
#include "portable.h"
#include "groupdef.h"
#include "memberdef.h"
#include "filedef.h"
#include "util.h"
#include "linkedmap.h"
#include "regex.h"
#include "fileinfo.h"
Classes
class HtmlHelpRecoder
Helper class to deal with recoding the UTF8 encoded text back to the native encoding specified by CHM_INDEX_ENCODING.
struct IndexField
Class representing a field in the HTML help index.
class HtmlHelpIndex
A helper class for HtmlHelp that manages a two level index in alphabetical order.
class HtmlHelp::Private
Functions
static QCString field2URL (const IndexField *f, bool checkReversed)
Function Documentation
field2URL()
static QCString field2URL (const IndexField * f, bool checkReversed) static
Definition at line 175 of file htmlhelp.cpp.
{
  QCString result = addHtmlExtensionIfMissing(f->url);
  if (!f->anchor.isEmpty() && (!checkReversed || f->reversed))
  {
    // HTML Help needs colons in link anchors to be escaped in the .hhk file.
    result+="#"+substitute(f->anchor,":","%3A");
  }
  return result;
}
References addHtmlExtensionIfMissing(), IndexField::anchor, QCString::isEmpty(), IndexField::reversed, substitute(), and IndexField::url.
Referenced by HtmlHelpIndex::writeFields().