Doxygen: RTFCodeGenerator Class Reference
RTFCodeGenerator Class Reference
Generator for RTF code fragments.
#include <rtfgen.h>
Public Member Functions
RTFCodeGenerator (TextStream &t)
OutputType type () const
void codify (const QCString &text)
void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)
void writeTooltip (const QCString &, const DocLinkInfo &, const QCString &, const QCString &, const SourceLinkInfo &, const SourceLinkInfo &)
void writeLineNumber (const QCString &, const QCString &, const QCString &, int l, bool)
void startCodeLine (bool)
void endCodeLine ()
void startFontClass (const QCString &)
void endFontClass ()
void writeCodeAnchor (const QCString &)
void startCodeFragment (const QCString &style)
void endCodeFragment (const QCString &)
Public Member Functions inherited from CodeOutputInterface
CodeOutputInterface ()=default
CodeOutputInterface (const CodeOutputInterface &)=delete
CodeOutputInterface & operator= (const CodeOutputInterface &)=delete
virtual ~CodeOutputInterface ()=default
virtual OutputType type () const =0
virtual int id () const
Identifier for the output file.
virtual void setId (int id)
virtual void setEnabled (bool e)
virtual bool isEnabled () const
virtual void codify (const QCString &s)=0
virtual void writeCodeLink (CodeSymbolType type, const QCString &ref, const QCString &file, const QCString &anchor, const QCString &name, const QCString &tooltip)=0
virtual void writeLineNumber (const QCString &ref, const QCString &file, const QCString &anchor, int lineNumber, bool writeLineAnchor)=0
virtual void writeTooltip (const QCString &id, const DocLinkInfo &docInfo, const QCString &decl, const QCString &desc, const SourceLinkInfo &defInfo, const SourceLinkInfo &declInfo)=0
virtual void startCodeLine (bool hasLineNumbers)=0
virtual void endCodeLine ()=0
virtual void startFontClass (const QCString &clsName)=0
virtual void endFontClass ()=0
virtual void writeCodeAnchor (const QCString &name)=0
virtual void setCurrentDoc (const Definition *context, const QCString &anchor, bool isSourceFile)
virtual void addWord (const QCString &word, bool hiPriority)
virtual void startCodeFragment (const QCString &style)=0
virtual void endCodeFragment (const QCString &style)=0
Private Member Functions
void setSourceFileName (const QCString &name)
void setIndentLevel (int level)
QCString rtf_Code_DepthStyle ()
Private Attributes
int m_col = 0
TextStream & m_t
bool m_doxyCodeLineOpen = false
QCString m_sourceFileName
int m_indentLevel = 0
Friends
class RTFGenerator
Detailed Description
Generator for RTF code fragments.
Definition at line 25 of file rtfgen.h.
Constructor & Destructor Documentation
RTFCodeGenerator()
RTFCodeGenerator::RTFCodeGenerator (TextStream & t) inline
Definition at line 28 of file rtfgen.h.
: m_t(t) {}
Member Function Documentation
codify()
void RTFCodeGenerator::codify (const QCString & s) virtual
Writes an code fragment to the output. This function should keep spaces visible, should break lines at a newline and should convert tabs to the right number of spaces.
Implements CodeOutputInterface.
Definition at line 132 of file rtfgen.cpp.
{
  // note that RTF does not have a "verbatim", so "\n" means
  // nothing... add a "newParagraph()";
  //static char spaces[]="        ";
  if (!str.isEmpty())
  {
    const char *p=str.data();
    char c;
    int spacesToNextTabStop;
    while (*p)
    {
      //static bool MultiByte = FALSE;
      c=*p++;
      switch(c)
      {
        case '\t':  spacesToNextTabStop = Config_getInt(TAB_SIZE) - (m_col%Config_getInt(TAB_SIZE));
                    m_t << Doxygen::spaces.left(spacesToNextTabStop);
                    m_col+=spacesToNextTabStop;
                    break;
        case '\n':  m_t << "\\par\n";
                    m_col=0;
                    break;
        case '{':   m_t << "\\{"; m_col++;          break;
        case '}':   m_t << "\\}"; m_col++;          break;
        case '\\':  m_t << "\\\\"; m_col++;         break;
        default:    p=writeUTF8Char(m_t,p-1); m_col++; break;
      }
    }
  }
}
References Config_getInt, QCString::data(), QCString::isEmpty(), QCString::left(), m_col, m_t, Doxygen::spaces, and writeUTF8Char().
Referenced by writeCodeLink().
endCodeFragment()
void RTFCodeGenerator::endCodeFragment (const QCString & style) virtual
Ends a block of code
Implements CodeOutputInterface.
Definition at line 174 of file rtfgen.cpp.
{
  endCodeLine();
  DBG_RTF(m_t << "{\\comment (endCodeFragment) }\n")
  m_t << "}\n";
  //m_omitParagraph = TRUE;
}
References DBG_RTF, endCodeLine(), and m_t.
endCodeLine()
void RTFCodeGenerator::endCodeLine () virtual
Ends a line of code started with startCodeLine()
Implements CodeOutputInterface.
Definition at line 232 of file rtfgen.cpp.
{
  if (m_doxyCodeLineOpen) m_t << "\\par\n";
  m_doxyCodeLineOpen = false;
}
References m_doxyCodeLineOpen, and m_t.
Referenced by endCodeFragment().
endFontClass()
void RTFCodeGenerator::endFontClass () virtual
Ends a block started with startFontClass()
Implements CodeOutputInterface.
Definition at line 256 of file rtfgen.cpp.
{
  m_t << "}";
}
References m_t.
rtf_Code_DepthStyle()
QCString RTFCodeGenerator::rtf_Code_DepthStyle () private
Definition at line 261 of file rtfgen.cpp.
{
  QCString n=makeIndexName("CodeExample",m_indentLevel);
  return rtf_Style[n.str()].reference();
}
References m_indentLevel, makeIndexName(), rtf_Style, and QCString::str().
Referenced by startCodeFragment().
setIndentLevel()
void RTFCodeGenerator::setIndentLevel (int level) inline private
Definition at line 54 of file rtfgen.h.
{ m_indentLevel=level; }
References m_indentLevel.
Referenced by RTFGenerator::decIndentLevel(), and RTFGenerator::incIndentLevel().
setSourceFileName()
void RTFCodeGenerator::setSourceFileName (const QCString & name) private
Definition at line 267 of file rtfgen.cpp.
{
  m_sourceFileName = name;
}
References m_sourceFileName.
Referenced by RTFGenerator::setSourceFileName().
startCodeFragment()
void RTFCodeGenerator::startCodeFragment (const QCString & style) virtual
Starts a source code fragment. The fragment will be fed to the code parser (see code.h) for syntax highlighting and cross-referencing. The fragment ends by a call to endCodeFragment()
Parameters
style The kind of code fragment.
Implements CodeOutputInterface.
Definition at line 167 of file rtfgen.cpp.
{
  DBG_RTF(m_t << "{\\comment (startCodeFragment) }\n")
  m_t << "{\n";
  m_t << rtf_Style_Reset << rtf_Code_DepthStyle();
}
References DBG_RTF, m_t, rtf_Code_DepthStyle(), and rtf_Style_Reset.
startCodeLine()
void RTFCodeGenerator::startCodeLine (bool) virtual
Implements CodeOutputInterface.
Definition at line 226 of file rtfgen.cpp.
{
  m_doxyCodeLineOpen = true;
  m_col=0;
}
References m_col, and m_doxyCodeLineOpen.
startFontClass()
void RTFCodeGenerator::startFontClass (const QCString & clsName) virtual
Starts a block with a certain meaning. Used for syntax highlighting, which elements of the same type are rendered using the same 'font class'.
Parameters
clsName The category name.
Implements CodeOutputInterface.
Definition at line 238 of file rtfgen.cpp.
{
  int cod = 2;
  QCString qname(name);
  if (qname == "keyword")            cod = 17;
  else if (qname == "keywordtype")   cod = 18;
  else if (qname == "keywordflow")   cod = 19;
  else if (qname == "comment")       cod = 20;
  else if (qname == "preprocessor")  cod = 21;
  else if (qname == "stringliteral") cod = 22;
  else if (qname == "charliteral")   cod = 23;
  else if (qname == "vhdldigit")     cod = 24;
  else if (qname == "vhdlchar")      cod = 25;
  else if (qname == "vhdlkeyword")   cod = 26;
  else if (qname == "vhdllogic")     cod = 27;
  m_t << "{\\cf" << cod << " ";
}
References m_t.
type()
OutputType RTFCodeGenerator::type () const inline virtual
Implements CodeOutputInterface.
Definition at line 29 of file rtfgen.h.
{ return OutputType::RTF; }
writeCodeAnchor()
void RTFCodeGenerator::writeCodeAnchor (const QCString & name) inline virtual
Write an anchor to a source listing.
Parameters
name The name of the anchor.
Implements CodeOutputInterface.
Definition at line 47 of file rtfgen.h.
{}
writeCodeLink()
void RTFCodeGenerator::writeCodeLink (CodeSymbolType type, const QCString & ref, const QCString & file, const QCString & anchor, const QCString & name, const QCString & tooltip) virtual
Writes a link to an object in a code fragment.
Parameters
type The type of symbol, used for semantic syntax highlighting, may be Default is no info is available.
ref If this is non-zero, the object is to be found in an external documentation file.
file The file in which the object is located.
anchor The anchor uniquely identifying the object within the file.
name The text to display as a placeholder for the link.
tooltip The tooltip to display when the mouse is on the link.
Implements CodeOutputInterface.
Definition at line 99 of file rtfgen.cpp.
{
  if (ref.isEmpty() && Config_getBool(RTF_HYPERLINKS))
  {
    QCString refName;
    if (!f.isEmpty())
    {
      refName+=stripPath(f);
    }
    if (!anchor.isEmpty())
    {
      refName+='_';
      refName+=anchor;
    }
    m_t << "{\\field {\\*\\fldinst { HYPERLINK  \\\\l \"";
    m_t << rtfFormatBmkStr(refName);
    m_t << "\" }{}";
    m_t << "}{\\fldrslt {\\cs37\\ul\\cf2 ";
    codify(name);
    m_t << "}}}\n";
  }
  else
  {
    codify(name);
  }
}
References codify(), Config_getBool, QCString::isEmpty(), m_t, rtfFormatBmkStr(), and stripPath().
Referenced by writeLineNumber().
writeLineNumber()
void RTFCodeGenerator::writeLineNumber (const QCString & ref, const QCString & file, const QCString & anchor, int lineNumber, bool writeLineAnchor) virtual
Writes the line number of a source listing
Parameters
ref External reference (when imported from a tag file)
file The file part of the URL pointing to the docs.
anchor The anchor part of the URL pointing to the docs.
lineNumber The line number to write
writeLineAnchor Indicates if an anchor for the line number needs to be written
Implements CodeOutputInterface.
Definition at line 183 of file rtfgen.cpp.
{
  bool rtfHyperlinks = Config_getBool(RTF_HYPERLINKS);
  m_doxyCodeLineOpen = true;
  if (Config_getBool(SOURCE_BROWSER))
  {
    QCString lineNumber;
    lineNumber.sprintf("%05d",l);
    QCString lineAnchor;
    if (!m_sourceFileName.isEmpty())
    {
      lineAnchor.sprintf("_l%05d",l);
      lineAnchor.prepend(stripExtensionGeneral(stripPath(m_sourceFileName), ".rtf"));
    }
    bool showTarget = rtfHyperlinks && !lineAnchor.isEmpty() && writeLineAnchor;
    if (showTarget)
    {
        m_t << "{\\bkmkstart ";
        m_t << rtfFormatBmkStr(lineAnchor);
        m_t << "}";
        m_t << "{\\bkmkend ";
        m_t << rtfFormatBmkStr(lineAnchor);
        m_t << "}\n";
    }
    if (!fileName.isEmpty())
    {
      writeCodeLink(CodeSymbolType::Default,ref,fileName,anchor,lineNumber,QCString());
    }
    else
    {
      m_t << lineNumber;
    }
    m_t << " ";
  }
  else
  {
    m_t << l << " ";
  }
  m_col=0;
}
References Config_getBool, QCString::isEmpty(), m_col, m_doxyCodeLineOpen, m_sourceFileName, m_t, QCString::prepend(), rtfFormatBmkStr(), QCString::sprintf(), stripExtensionGeneral(), stripPath(), and writeCodeLink().
writeTooltip()
void RTFCodeGenerator::writeTooltip (const QCString & id, const DocLinkInfo & docInfo, const QCString & decl, const QCString & desc, const SourceLinkInfo & defInfo, const SourceLinkInfo & declInfo) inline virtual
Writes a tool tip definition
Parameters
id unique identifier for the tooltip
docInfo Info about the symbol's documentation.
decl full declaration of the symbol (for functions)
desc brief description for the symbol
defInfo Info about the symbol's definition in the source code
declInfo Info about the symbol's declaration in the source code
Implements CodeOutputInterface.
Definition at line 35 of file rtfgen.h.
                       {}
Friends And Related Symbol Documentation
RTFGenerator
friend class RTFGenerator friend
Definition at line 52 of file rtfgen.h.
Member Data Documentation
m_col
int RTFCodeGenerator::m_col = 0 private
Definition at line 56 of file rtfgen.h.
Referenced by codify(), startCodeLine(), and writeLineNumber().
m_doxyCodeLineOpen
bool RTFCodeGenerator::m_doxyCodeLineOpen = false private
Definition at line 58 of file rtfgen.h.
Referenced by endCodeLine(), startCodeLine(), and writeLineNumber().
m_indentLevel
int RTFCodeGenerator::m_indentLevel = 0 private
Definition at line 60 of file rtfgen.h.
Referenced by rtf_Code_DepthStyle(), and setIndentLevel().
m_sourceFileName
QCString RTFCodeGenerator::m_sourceFileName private
Definition at line 59 of file rtfgen.h.
Referenced by setSourceFileName(), and writeLineNumber().
m_t
TextStream& RTFCodeGenerator::m_t private
Definition at line 57 of file rtfgen.h.
Referenced by codify(), endCodeFragment(), endCodeLine(), endFontClass(), startCodeFragment(), startFontClass(), writeCodeLink(), and writeLineNumber().
The documentation for this class was generated from the following files:
/home/runner/work/doxygen/doxygen/src/rtfgen.h
/home/runner/work/doxygen/doxygen/src/rtfgen.cpp