Doxygen: /home/runner/work/doxygen/doxygen/src/namespacedef.cpp File Reference
namespacedef.cpp File Reference
#include "namespacedef.h"
#include "outputlist.h"
#include "util.h"
#include "language.h"
#include "classdef.h"
#include "classlist.h"
#include "memberlist.h"
#include "doxygen.h"
#include "message.h"
#include "docparser.h"
#include "searchindex.h"
#include "vhdldocgen.h"
#include "layout.h"
#include "membergroup.h"
#include "config.h"
#include "definitionimpl.h"
#include "membername.h"
#include "conceptdef.h"
Classes
class NamespaceDefImpl
class NamespaceDefAliasImpl
Functions
static QCString makeDisplayName (const NamespaceDef *nd, bool includeScope)
NamespaceDefMutable * createNamespaceDef (const QCString &defFileName, int defLine, int defColumn, const QCString &name, const QCString &ref, const QCString &refFile, const QCString &type, bool isPublished)
Factory method to create new NamespaceDef instance.
NamespaceDef * createNamespaceDefAlias (const Definition *newScope, const NamespaceDef *nd)
Factory method to create an alias of an existing namespace.
NamespaceDef * toNamespaceDef (Definition *d)
NamespaceDef * toNamespaceDef (DefinitionMutable *md)
const NamespaceDef * toNamespaceDef (const Definition *d)
NamespaceDefMutable * toNamespaceDefMutable (Definition *d)
NamespaceDef * getResolvedNamespace (const QCString &name)
bool namespaceHasNestedNamespace (const NamespaceDef *nd)
bool namespaceHasNestedConcept (const NamespaceDef *nd)
bool namespaceHasNestedClass (const NamespaceDef *nd, bool filterClasses, ClassDef::CompoundType ct)
Function Documentation
createNamespaceDef()
NamespaceDefMutable * createNamespaceDef (const QCString & defFileName, int defLine, int defColumn, const QCString & name, const QCString & ref, const QCString & refFile, const QCString & type, bool isPublished)
Factory method to create new NamespaceDef instance.
Definition at line 164 of file namespacedef.cpp.
{
  //printf("createNamespaceDef(%s)\n",qPrint(name));
  return new NamespaceDefImpl(defFileName,defLine,defColumn,name,ref,refFile,type,isPublished);
}
Referenced by adjustConfiguration(), buildNamespaceList(), buildScopeFromQualifiedName(), and findUsingDirectives().
createNamespaceDefAlias()
NamespaceDef * createNamespaceDefAlias (const Definition * newScope, const NamespaceDef * nd)
Factory method to create an alias of an existing namespace.
Used for inline namespaces.
Definition at line 248 of file namespacedef.cpp.
{
  NamespaceDef *alnd = new NamespaceDefAliasImpl(newScope,nd);
  //printf("alnd name=%s localName=%s qualifiedName=%s displayName()=%s\n",
  //    qPrint(alnd->name()),qPrint(alnd->localName()),qPrint(alnd->qualifiedName()),
  //    qPrint(alnd->displayName()));
  return alnd;
}
Referenced by buildNamespaceList().
getResolvedNamespace()
NamespaceDef * getResolvedNamespace (const QCString & name)
Definition at line 1619 of file namespacedef.cpp.
{
  if (name.isEmpty()) return 0;
  auto it = Doxygen::namespaceAliasMap.find(name.str());
  if (it!=Doxygen::namespaceAliasMap.end())
  {
    int count=0; // recursion detection guard
    StringUnorderedMap::iterator it2;
    while ((it2=Doxygen::namespaceAliasMap.find(it->second))!=Doxygen::namespaceAliasMap.end() &&
           count<10)
    {
      it=it2;
      count++;
    }
    if (count==10)
    {
      warn_uncond("possible recursive namespace alias detected for %s!\n",qPrint(name));
    }
    return Doxygen::namespaceLinkedMap->find(it->second);
  }
  else
  {
    return Doxygen::namespaceLinkedMap->find(name);
  }
}
References end(), LinkedMap< T, Hash, KeyEqual, Map >::find(), QCString::isEmpty(), Doxygen::namespaceAliasMap, Doxygen::namespaceLinkedMap, qPrint(), QCString::str(), and warn_uncond().
Referenced by addMemberFunction(), extractNamespaceName(), findUsedNamespace(), findUsingDirectives(), generateClassOrGlobalLink(), getResolvedNamespaceMutable(), CCodeParser::parseCode(), setCallContextForVar(), and writeAlphabeticalClassList().
makeDisplayName()
static QCString makeDisplayName (const NamespaceDef * nd, bool includeScope) static
Definition at line 38 of file namespacedef.cpp.
{
  QCString result=includeScope ? nd->name() : nd->localName();
  SrcLangExt lang = nd->getLanguage();
  QCString sep = getLanguageSpecificSeparator(lang);
  if (sep!="::")
  {
    result = substitute(result,"::",sep);
  }
  //printf("makeDisplayName() %s->%s lang=%d\n",qPrint(name()),qPrint(result),lang);
  return result;
}
References Definition::getLanguage(), getLanguageSpecificSeparator(), NamespaceDef::localName(), Definition::name(), and substitute().
Referenced by NamespaceDefAliasImpl::displayName(), and NamespaceDefImpl::displayName().
namespaceHasNestedClass()
bool namespaceHasNestedClass (const NamespaceDef * nd, bool filterClasses, ClassDef::CompoundType ct)
Definition at line 1683 of file namespacedef.cpp.
{
  //printf(">namespaceHasNestedClass(%s,filterClasses=%d)\n",qPrint(nd->name()),filterClasses);
  for (const auto &cnd : nd->getNamespaces())
  {
    if (namespaceHasNestedClass(cnd,filterClasses,ct))
    {
      //printf("<namespaceHasNestedClass(%s,filterClasses=%d): case1\n",qPrint(nd->name()),filterClasses);
      return true;
    }
  }
  ClassLinkedRefMap list = nd->getClasses();
  if (filterClasses)
  {
    switch (ct)
    {
      case ClassDef::Interface:
        list = nd->getInterfaces();
        break;
      case ClassDef::Struct:
        list = nd->getStructs();
        break;
      case ClassDef::Exception:
        list = nd->getExceptions();
        break;
      default:
        break;
    }
  }
  for (const auto &cd : list)
  {
    //printf("candidate %s isLinkableInProject()=%d\n",qPrint(cd->name()),cd->isLinkableInProject());
    if (cd->isLinkableInProject())
    {
      //printf("<namespaceHasNestedClass(%s,filterClasses=%d): case2\n",qPrint(nd->name()),filterClasses);
      return true;
    }
  }
  //printf("<namespaceHasNestedClass(%s,filterClasses=%d): case3\n",qPrint(nd->name()),filterClasses);
  return false;
}
References ClassDef::Exception, NamespaceDef::getClasses(), NamespaceDef::getExceptions(), NamespaceDef::getInterfaces(), NamespaceDef::getNamespaces(), NamespaceDef::getStructs(), ClassDef::Interface, namespaceHasNestedClass(), and ClassDef::Struct.
Referenced by NestingContext::Private::addNamespace(), namespaceHasNestedClass(), writeClassTreeInsideNamespaceElement(), and writeNamespaceTreeElement().
namespaceHasNestedConcept()
bool namespaceHasNestedConcept (const NamespaceDef * nd)
Definition at line 1659 of file namespacedef.cpp.
{
  //printf(">namespaceHasNestedConcept(%s)\n",qPrint(nd->name()));
  for (const auto &cnd : nd->getNamespaces())
  {
    if (namespaceHasNestedConcept(cnd))
    {
      //printf("<namespaceHasNestedConcept(%s): case1\n",qPrint(nd->name()));
      return true;
    }
  }
  for (const auto &cnd : nd->getConcepts())
  {
    //printf("candidate %s isLinkableInProject()=%d\n",qPrint(cnd->name()),cnd->isLinkableInProject());
    if (cnd->isLinkableInProject())
    {
      //printf("<namespaceHasNestedConcept(%s): case2\n",qPrint(nd->name()));
      return true;
    }
  }
  //printf("<namespaceHasNestedConcept(%s): case3\n",qPrint(nd->name()));
  return false;
}
References NamespaceDef::getConcepts(), NamespaceDef::getNamespaces(), and namespaceHasNestedConcept().
Referenced by NestingContext::Private::addNamespace(), namespaceHasNestedConcept(), writeConceptTreeInsideNamespaceElement(), and writeNamespaceTreeElement().
namespaceHasNestedNamespace()
bool namespaceHasNestedNamespace (const NamespaceDef * nd)
Definition at line 1647 of file namespacedef.cpp.
{
  for (const auto &cnd : nd->getNamespaces())
  {
    if (cnd->isLinkableInProject() && !cnd->isAnonymous())
    {
      return true;
    }
  }
  return false;
}
References NamespaceDef::getNamespaces().
Referenced by NestingContext::Private::addNamespace(), and writeNamespaceTreeElement().
toNamespaceDef() [1/3]
const NamespaceDef * toNamespaceDef (const Definition * d)
Definition at line 1592 of file namespacedef.cpp.
{
  if (d && (typeid(*d)==typeid(NamespaceDefImpl) || typeid(*d)==typeid(NamespaceDefAliasImpl)))
  {
    return static_cast<const NamespaceDef*>(d);
  }
  else
  {
    return 0;
  }
}
toNamespaceDef() [2/3]
NamespaceDef * toNamespaceDef (Definition * d)
Definition at line 1566 of file namespacedef.cpp.
{
  if (d && (typeid(*d)==typeid(NamespaceDefImpl) || typeid(*d)==typeid(NamespaceDefAliasImpl)))
  {
    return static_cast<NamespaceDef*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by DocSets::addIndexItem(), NamespaceDefImpl::addInnerCompound(), NestingNodeContext::Private::addMembers(), NestingNodeContext::Private::addNamespaces(), buildNamespaceList(), NestingNodeContext::Private::createNamespace(), findGlobalMember(), findUsingDirectives(), SymbolResolver::Private::followPath(), generateClassMemberLink(), NamespaceDefAliasImpl::getNSAlias(), SymbolResolver::Private::isAccessibleFrom(), SymbolResolver::Private::isAccessibleFromWithExpScope(), MemberDefImpl::moveTo(), resolveClassNestingRelations(), and writeJavaScriptSearchIndex().
toNamespaceDef() [3/3]
NamespaceDef * toNamespaceDef (DefinitionMutable * md)
Definition at line 1578 of file namespacedef.cpp.
{
  Definition *d = toDefinition(md);
  if (d && typeid(*d)==typeid(NamespaceDefImpl))
  {
    return static_cast<NamespaceDef*>(d);
  }
  else
  {
    return 0;
  }
}
References toDefinition().
toNamespaceDefMutable()
NamespaceDefMutable * toNamespaceDefMutable (Definition * d)
Definition at line 1604 of file namespacedef.cpp.
{
  if (d && typeid(*d)==typeid(NamespaceDefImpl))
  {
    return static_cast<NamespaceDefMutable*>(d);
  }
  else
  {
    return 0;
  }
}
Referenced by addEnumValuesToEnums(), addListReferences(), addMembersToMemberGroup(), addNamespaceToGroups(), buildNamespaceList(), buildScopeFromQualifiedName(), combineUsingRelations(), FileDefImpl::combineUsingRelations(), NamespaceDefImpl::combineUsingRelations(), computeMemberReferences(), countMembers(), distributeMemberGroupDocumentation(), findEnums(), findScopeFromQualifiedName(), findSectionsInDocumentation(), findUsingDirectives(), generateNamespaceDocs(), getResolvedNamespaceMutable(), NamespaceDefImpl::insertMember(), sortMemberLists(), and writeTagFile().