Doxygen: /home/runner/work/doxygen/doxygen/src/message.h File Reference
message.h File Reference
#include <cstdarg>
#include "qcstring.h"
Macros
#define PRINTFLIKE(FORMAT, PARAM)
Functions
void msg (const char *fmt,...) PRINTFLIKE(1
void void warn (const QCString &file, int line, const char *fmt,...) PRINTFLIKE(3
void void void va_warn (const QCString &file, int line, const char *fmt, va_list args)
void warn_simple (const QCString &file, int line, const char *text)
void warn_undoc (const QCString &file, int line, const char *fmt,...) PRINTFLIKE(3
void void warn_incomplete_doc (const QCString &file, int line, const char *fmt,...) PRINTFLIKE(3
void void void warn_doc_error (const QCString &file, int line, const char *fmt,...) PRINTFLIKE(3
void void void void warn_uncond (const char *fmt,...) PRINTFLIKE(1
void void void void void err (const char *fmt,...) PRINTFLIKE(1
void void void void void void err_full (const QCString &file, int line, const char *fmt,...) PRINTFLIKE(3
void void void void void void void term (const char *fmt,...) PRINTFLIKE(1
void void void void void void void QCString warn_line (const QCString &file, int line)
void initWarningFormat ()
void warn_flush ()
void finishWarnExit ()
void printlex (int dbg, bool enter, const char *lexName, const char *fileName)
Macro Definition Documentation
PRINTFLIKE
#define PRINTFLIKE (FORMAT, PARAM)
Definition at line 25 of file message.h.
Function Documentation
err()
void void void void void err (const char * fmt, ...)
err_full()
void void void void void void err_full (const QCString & file, int line, const char * fmt, ...)
finishWarnExit()
void finishWarnExit ()
Definition at line 301 of file message.cpp.
{
  if (g_warnStat && g_warnBehavior == WARN_AS_ERROR_t::FAIL_ON_WARNINGS)
  {
    Doxygen::terminating=true;
    exit(1);
  }
}
References g_warnBehavior, g_warnStat, and Doxygen::terminating.
Referenced by generateOutput().
initWarningFormat()
void initWarningFormat ()
Definition at line 36 of file message.cpp.
{
  g_warnFormat = Config_getString(WARN_FORMAT);
  g_warnLineFormat = Config_getString(WARN_LINE_FORMAT);
  QCString logFile = Config_getString(WARN_LOGFILE);
  if (!logFile.isEmpty())
  {
    if (logFile == "-")
    {
      g_warnFile = stdout;
    }
    else if (!(g_warnFile = Portable::fopen(logFile,"w")))
    {
      // point it to something valid, because warn() relies on it
      g_warnFile = stderr;
      err("Cannot open '%s' for writing, redirecting 'WARN_LOGFILE' output to 'stderr'\n",logFile.data());
    }
  }
  else
  {
    g_warnFile = stderr;
  }
  g_warnBehavior = Config_getEnum(WARN_AS_ERROR);
  if (g_warnBehavior != WARN_AS_ERROR_t::NO)
  {
    g_warningStr = g_errorStr;
  }
}
References Config_getEnum, Config_getString, QCString::data(), err(), Portable::fopen(), g_errorStr, g_warnBehavior, g_warnFile, g_warnFormat, g_warningStr, g_warnLineFormat, and QCString::isEmpty().
Referenced by checkConfiguration().
msg()
void msg (const char * fmt, ...)
printlex()
void printlex (int dbg, bool enter, const char * lexName, const char * fileName)
Definition at line 273 of file message.cpp.
{
  const char *enter_txt = "entering";
  const char *enter_txt_uc = "Entering";
  if (!enter)
  {
    enter_txt = "finished";
    enter_txt_uc = "Finished";
  }
  std::unique_lock<std::mutex> lock(g_mutex);
  if (dbg)
  {
    if (fileName)
      fprintf(stderr,"--%s lexical analyzer: %s (for: %s)\n",enter_txt, qPrint(lexName), qPrint(fileName));
    else
      fprintf(stderr,"--%s lexical analyzer: %s\n",enter_txt, qPrint(lexName));
  }
  else
  {
    if (fileName)
      Debug::print(Debug::Lex,0,"%s lexical analyzer: %s (for: %s)\n",enter_txt_uc, qPrint(lexName), qPrint(fileName));
    else
      Debug::print(Debug::Lex,0,"%s lexical analyzer: %s\n",enter_txt_uc, qPrint(lexName));
  }
}
References g_mutex, Debug::Lex, Debug::print(), and qPrint().
Referenced by convertCppComments(), DocTokenizer::findSections(), ConstExpressionParser::parse(), ConfigImpl::parse(), CCodeParser::parseCode(), FortranCodeParser::parseCode(), PythonCodeParser::parseCode(), VHDLCodeParser::parseCode(), LexCodeParser::parseCode(), SQLCodeParser::parseCode(), XMLCodeParser::parseCode(), CommentScanner::parseCommentBlock(), parseFuncDecl(), FortranOutlineParser::parseInput(), LexOutlineParser::parseInput(), PythonOutlineParser::parseInput(), COutlineParser::parseInput(), Preprocessor::processFile(), and stringToArgumentList().
term()
void void void void void void void term (const char * fmt, ...)
va_warn()
void void void va_warn (const QCString & file, int line, const char * fmt, va_list args)
Definition at line 187 of file message.cpp.
{
  do_warn(Config_getBool(WARNINGS), file, line, g_warningStr, fmt, args);
}
References Config_getBool, do_warn(), and g_warningStr.
Referenced by TemplateContextImpl::warn(), and TemplateParser::warn().
warn()
void void warn (const QCString & file, int line, const char * fmt, ...)
warn_doc_error()
void void void warn_doc_error (const QCString & file, int line, const char * fmt, ...)
warn_flush()
void warn_flush ()
Definition at line 267 of file message.cpp.
{
  fflush(g_warnFile);
}
References g_warnFile.
Referenced by generateOutput().
warn_incomplete_doc()
void void warn_incomplete_doc (const QCString & file, int line, const char * fmt, ...)
warn_line()
void void void void void void void QCString warn_line (const QCString & file, int line)
Definition at line 167 of file message.cpp.
{
  QCString fileSubst = file.isEmpty() ? "<unknown>" : file;
  QCString lineSubst; lineSubst.setNum(line);
  return  substitute(
            substitute(
              g_warnLineFormat,
              "$file",fileSubst
            ),
            "$line",lineSubst
          );
}
References g_warnLineFormat, QCString::isEmpty(), QCString::setNum(), and substitute().
Referenced by addMemberFunction(), checkPageRelations(), computePageRelations(), and findGlobalMember().
warn_simple()
void warn_simple (const QCString & file, int line, const char * text)
Definition at line 192 of file message.cpp.
{
  if (!Config_getBool(WARNINGS)) return; // warning type disabled
  format_warn(file,line,QCString(g_warningStr) + text);
}
References Config_getBool, format_warn(), and g_warningStr.
Referenced by addMemberFunction().
warn_uncond()
void void void void warn_uncond (const char * fmt, ...)
warn_undoc()
void warn_undoc (const QCString & file, int line, const char * fmt, ...)